---
permalink: sm-storage/add-capacity-to-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, capacity, pool, volume, group 
summary: Vous pouvez ajouter des disques pour augmenter la capacité disponible dans un pool ou un groupe de volumes existant. 
---
= Ajouter de la capacité à un pool ou à un groupe de volumes dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter des disques pour augmenter la capacité disponible dans un pool ou un groupe de volumes existant.

L'extension entraîne l'ajout de capacité disponible dans le pool ou le groupe de volumes. Vous pouvez utiliser cette capacité disponible pour créer des volumes supplémentaires. Les données des volumes restent accessibles lors de cette opération.

.Avant de commencer
* Les disques doivent être en état optimal.
* Les disques doivent avoir le même type de disque (HDD ou SSD).
* Le pool ou le groupe de volumes doit être à l'état optimal.
* Le nombre maximal de volumes autorisés dans un groupe de volumes est de 256.
* Le nombre maximum de volumes autorisé dans un pool dépend du modèle du système de stockage :
+
** 2 048 volumes (EF80, EF600, and E5700 series)
** 1 024 volumes (EF50 et EF300)
** 512 volumes (E4000 et E2800 Series)


* Si le pool ou le groupe de volumes contient tous les lecteurs sécurisés, ajoutez uniquement des lecteurs capables de sécuriser pour continuer à utiliser les capacités de cryptage des lecteurs sécurisés.
+
Les disques sécurisés peuvent être des disques FDE (Full Disk Encryption) ou FIPS (Federal information Processing Standard).



.Description de la tâche
Pour les pools, vous pouvez ajouter jusqu'à 60 disques à la fois. Pour les groupes de volumes, vous pouvez ajouter deux lecteurs au maximum à la fois. Si vous devez ajouter plus de lecteurs que le nombre maximal, répétez la procédure. (Un pool ne peut pas contenir plus de disques que la limite maximale d'un système de stockage.)

[NOTE]
====
Avec l'ajout de lecteurs, il peut être nécessaire d'augmenter votre capacité de conservation. Vous devez envisager d'augmenter votre capacité réservée après une opération d'extension.

====
[NOTE]
====
Évitez d'utiliser des disques compatibles Data Assurance (DA) pour ajouter de la capacité à un pool ou un groupe de volumes qui n'est pas compatible DA. Le pool ou le groupe de volumes ne peut pas tirer parti des capacités du disque compatible DA. Envisagez d'utiliser des disques qui ne sont pas compatibles DA dans cette situation.

====
.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage [Pools and volume groups].
. Sélectionnez le pool ou le groupe de volumes auquel vous souhaitez ajouter des disques, puis cliquez sur menu:icône d’ellipse[Ajouter de la capacité].
+
La boîte de dialogue Ajouter de la capacité s'affiche. Seuls les disques non attribués compatibles avec le pool ou le groupe de volumes apparaissent.

. Sous *Select drives to Add capacity...*, sélectionnez un ou plusieurs disques que vous souhaitez ajouter au pool ou au groupe de volumes existant.
+
Le firmware du contrôleur organise les disques non assignés avec les meilleures options répertoriées en haut. La capacité totale disponible ajoutée au pool ou au groupe de volumes apparaît sous la liste *capacité totale sélectionnée*.

+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Champ | Description 


 a| 
Tiroir
 a| 
Indique l'emplacement du tiroir du disque.



 a| 
Baie
 a| 
Indique l'emplacement de baie du lecteur.



 a| 
Capacité (Gio)
 a| 
Indique la capacité du lecteur.

** Dans la mesure du possible, sélectionnez des disques dont la capacité est égale aux capacités des disques actuels du pool ou du groupe de volumes.
** Si vous devez ajouter des disques non assignés offrant une capacité réduite, notez que la capacité utile de chaque disque actuellement dans le pool ou le groupe de volumes est réduite. La capacité des disques est donc identique sur le pool ou le groupe de volumes.
** Si vous devez ajouter des disques non assignés offrant une plus grande capacité, notez que la capacité utile des disques non assignés que vous ajoutez est réduite de sorte qu'ils correspondent aux capacités actuelles des disques du pool ou du groupe de volumes.




 a| 
Sécurité
 a| 
Indique si le lecteur est sécurisé.

** Pour protéger votre pool ou votre groupe de volumes à l'aide de la fonction de sécurité du lecteur, tous les disques doivent être sécurisés.
** Il est possible de créer un pool ou un groupe de volumes avec un mélange de disques sécurisés et non sécurisés, mais la fonction Drive Security ne peut pas être activée.
** Un pool ou un groupe de volumes disposant de tous les disques sécurisés ne peut pas accepter un disque non sécurisé pour le remplacement ou l'extension, même si la fonctionnalité de chiffrement n'est pas utilisée.
** Les disques signalés comme sécurisés peuvent être des disques FDE (Full Disk Encryption) ou FIPS (Federal information Processing Standard).
** Un disque FIPS peut être de niveau 140-2 ou 140-3, avec le niveau 140-3 comme niveau de sécurité supérieur. Si vous sélectionnez un mélange de 140-2 et 140-3 disques de niveau, le pool ou le groupe de volumes fonctionnera alors au niveau de sécurité inférieur (140-2).




 a| 
Compatible DA
 a| 
Indique si le lecteur est compatible avec Data assurance (DA).

** Il est déconseillé d'utiliser des disques non compatibles avec Data Assurance (DA) pour ajouter de la capacité à un pool ou un groupe de volumes compatible DA. Le pool ou le groupe de volumes ne dispose alors plus des fonctionnalités DA, et vous n'avez plus la possibilité d'activer DA sur les nouveaux volumes créés dans le pool ou le groupe de volumes.
** Il est déconseillé d'utiliser des disques compatibles Data Assurance (DA) pour ajouter de la capacité à un pool ou à un groupe de volumes non DA-capable, car ce pool ou ce groupe de volumes ne pourra pas tirer parti des capacités du disque DA-capable (les attributs des disques ne correspondent pas). Envisagez d'utiliser des disques qui ne sont pas DA-capable dans cette situation.




 a| 
Compatible DULBE
 a| 
Indique si le disque dispose de l’option Deallocated or Unwritten Logical Block Error (DULBE). DULBE est une option sur les disques NVMe qui permet à la baie de stockage EF80, EF50, EF300 ou EF600 de prendre en charge les volumes à ressources provisionnées.

|===
====
. Cliquez sur *Ajouter*.
+
Si vous ajoutez des disques à un pool ou à un groupe de volumes, une boîte de dialogue de confirmation s'affiche si vous avez sélectionné un lecteur qui empêche le pool ou le groupe de volumes d'avoir un ou plusieurs des attributs suivants :

+
** Protection contre les pertes de tiroirs ^*^
** Protection contre la perte de tiroir ^*^
** Fonctionnalité Full Disk Encryption
** Fonctionnalité Data assurance
** Capacité DULBE





NOTE: ^*^ actuellement, la boîte de dialogue de confirmation ne s’affiche pas lors de l’ajout de lecteurs à un pool avec protection contre la perte de tiroirs ou protection contre la perte de tiroirs.

. Pour continuer, cliquez sur *Oui* ; sinon, cliquez sur *Annuler*.


.Résultats
Après avoir ajouté les disques non assignés à un pool ou à un groupe de volumes, les données de chaque volume du pool ou du groupe de volumes sont redistribuées pour inclure les disques supplémentaires.
