---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-consistency-group-member-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, consistency group, member volume 
summary: 'Vous pouvez modifier les paramètres d"un volume membre d"un groupe de cohérence de manière à ajuster le point de pourcentage auquel System Manager envoie une notification d"alerte lorsque la capacité réservée d"un volume membre approche pleine et à modifier la règle à utiliser lorsque la capacité réservée atteint son maximum défini pourcentage.' 
---
= Modifiez les paramètres de capacité réservée pour un volume membre de groupe de cohérence
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres d'un volume de membres d'un groupe de cohérence pour ajuster le point de pourcentage auquel le gestionnaire système SANtricity envoie une notification d'alerte lorsque la capacité réservée d'un volume membre est presque pleine et pour modifier la règle à utiliser lorsque la capacité réservée atteint son pourcentage maximal défini.

.Description de la tâche
La modification des paramètres de capacité réservée pour un volume membre individuel modifie également les paramètres de capacité réservée pour tous les volumes membres associés à un groupe de cohérence.

.Étapes
. Menu Sélectionner:Storage[pools & Volume Groups].
. Cliquez sur l'onglet *capacité réservée*.
. Sélectionnez le volume membre du groupe de cohérence que vous souhaitez modifier, puis cliquez sur *Afficher/Modifier les paramètres*.
+
La boîte de dialogue Paramètres de capacité réservée du volume membre s'affiche.

. Modifiez les paramètres de capacité réservée pour le volume membre selon les besoins.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
M'avertir lorsque...
 a| 
Utilisez la case à cocher pour régler le point de pourcentage auquel System Manager envoie une notification d'alerte lorsque la capacité réservée d'un volume membre est presque pleine.

Lorsque la capacité réservée du volume membre dépasse le seuil spécifié, System Manager envoie une alerte pour augmenter la capacité réservée ou supprimer des objets inutiles.


NOTE: Si vous modifiez le paramètre alerte pour un volume membre, les volumes _All_ member appartenant au même groupe de cohérence seront modifiés.



 a| 
Règle pour la capacité totale réservée
 a| 
Vous pouvez choisir l'une des règles suivantes :

** *Purge de l'image snapshot la plus ancienne* -- System Manager purge automatiquement l'image snapshot la plus ancienne du groupe de cohérence, ce qui libère la capacité réservée du membre pour réutilisation au sein du groupe.
** *Rejeter les écritures dans le volume de base* -- lorsque la capacité réservée atteint son pourcentage maximal défini, System Manager rejette toute demande d'écriture d'E/S au volume de base qui a déclenché l'accès à la capacité réservée.


|===
====
. Cliquez sur *Enregistrer* pour appliquer vos modifications.


.Résultats
System Manager modifie les paramètres de capacité réservée pour le volume membre, ainsi que les paramètres de capacité réservée pour tous les volumes membres du groupe de cohérence.
