---
permalink: sm-storage/change-the-settings-for-a-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, host, cluster 
summary: Vous pouvez modifier le nom du cluster hôte ou ajouter ou supprimer des hôtes dans un cluster hôte. 
---
= Modifier les paramètres d'un cluster hôte dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le nom du cluster hôte ou ajouter ou supprimer des hôtes dans un cluster hôte.

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage[Hosts].
. Sélectionnez le cluster hôte que vous souhaitez modifier, puis cliquez sur l’icône menu:ellipse [Edit Settings].
+
Une fenêtre s'affiche, affichant les paramètres actuels du cluster hôte.

. Modifiez les paramètres du cluster hôte selon les besoins.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
Nom
 a| 
Vous pouvez spécifier le nom fourni par l'utilisateur du cluster hôte. La spécification d'un nom pour un cluster est requise.



 a| 
Hôtes associés
 a| 
Pour ajouter un hôte, cliquez sur la case *Associated Hosts*, puis sélectionnez un nom d'hôte dans la liste déroulante. Vous ne pouvez pas entrer manuellement un nom d'hôte.

Pour supprimer un hôte, cliquez sur *X* en regard du nom d'hôte.

|===
====
. Cliquez sur *Enregistrer*.

