---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, volume 
summary: 'Vous pouvez modifier les paramètres d"un volume d"instantané pour régler le point de pourcentage auquel le système envoie une notification d"alerte lorsque la capacité réservée d"un volume d"instantané est presque pleine.' 
---
= Modifier les paramètres de capacité réservée pour un volume de snapshot dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres d'un volume d'instantané pour régler le point de pourcentage auquel le système envoie une notification d'alerte lorsque la capacité réservée d'un volume d'instantané est presque pleine.

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage [Pools and volume groups].
. Cliquez sur l'onglet *capacité réservée*.
. Sélectionnez le volume d'instantané que vous souhaitez modifier, puis cliquez sur menu : icône de points de suspension [Modifier les paramètres].
+
La fenêtre « Modifier les paramètres de capacité réservée du volume instantané » s’affiche.

. Modifiez les paramètres de capacité réservée pour le volume de snapshot, le cas échéant.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
M'avertir lorsque...
 a| 
Utilisez la boîte à plateau pour régler le point de pourcentage auquel le système envoie une notification d'alerte lorsque la capacité réservée d'un volume membre est presque pleine.

Lorsque la capacité réservée du volume de snapshot dépasse le seuil spécifié, le système envoie une alerte, ce qui vous permet d'augmenter la capacité réservée ou de supprimer des objets inutiles.

|===
====
. Cliquez sur *Enregistrer* pour appliquer vos modifications aux paramètres de capacité réservée du volume de snapshot.

