---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, mirrored pair volume 
summary: 'Vous pouvez modifier les paramètres d"un volume de paire en miroir pour ajuster le point de pourcentage auquel System Manager envoie une notification d"alerte lorsque la capacité réservée d"un volume de paire en miroir est presque pleine.' 
---
= Modifier les paramètres de capacité réservée pour un volume de paire en miroir dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres d'un volume de paire en miroir pour ajuster le point de pourcentage auquel SANtricity System Manager envoie une notification d'alerte lorsque la capacité réservée pour un volume de paire en miroir est presque pleine.

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage [Pools and volume groups].
. Sélectionnez l'onglet *capacité réservée*.
. Sélectionnez le volume de paire en miroir que vous souhaitez modifier, puis cliquez sur le menu : ellipsis icon[Edit Settings].
+
La fenêtre Edit Mirrored Pair Volume Reserved Capacity Settings s’affiche.

. Modifiez les paramètres de capacité réservée pour le volume de paire en miroir selon les besoins.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
Seuil d'alerte de capacité réservée atteinte
 a| 
Utilisez la barre pour ajuster le point de pourcentage auquel System Manager envoie une notification d'alerte lorsque la capacité réservée pour une paire en miroir est presque pleine.

Lorsque la capacité réservée de la paire en miroir dépasse le seuil spécifié, System Manager envoie une alerte et vous permet d'augmenter la capacité réservée.


NOTE: La modification du paramètre alerte pour une paire symétrique modifie le paramètre alerte pour toutes les paires symétriques appartenant au même groupe de cohérence miroir.

|===
====
. Cliquez sur *Enregistrer* pour appliquer vos modifications.

