---
permalink: sm-storage/change-workload-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workload, settings 
summary: 'Vous pouvez modifier le nom d"une charge de travail et afficher son type d"application associé. Modifiez le nom d"une charge de travail lorsque le nom actuel n"a plus de signification ni d"objet.' 
---
= Modifier les paramètres de charge de travail dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le nom d'une charge de travail et afficher son type d'application associé. Modifiez le nom d'une charge de travail lorsque le nom actuel n'a plus de signification ni d'objet.

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage[Volumes].
. Sélectionnez l’onglet *Applications et charges de travail*.
+
La vue Applications et charges de travail s’affiche.

. Sélectionnez la charge de travail que vous souhaitez modifier, puis cliquez sur le menu : icône ellipse [Modifier les paramètres].
+
La boîte de dialogue Paramètres des Applications and workloads s'affiche.

. *Facultatif:* modifiez le nom fourni par l'utilisateur de la charge de travail.
. Cliquez sur *Enregistrer*.

