---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: 'Modifiez les identificateurs de port hôte lorsque vous souhaitez modifier le libellé utilisateur d"un identificateur de port hôte, ajouter un nouvel identificateur de port hôte à l"hôte ou supprimer un identificateur de port hôte de l"hôte.' 
---
= Modifier les identifiants de port d'hôte pour un hôte dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Modifiez les identificateurs de port hôte lorsque vous souhaitez modifier le libellé utilisateur d'un identificateur de port hôte, ajouter un nouvel identificateur de port hôte à l'hôte ou supprimer un identificateur de port hôte de l'hôte.

.Description de la tâche
Lors de la modification des identificateurs de port hôte, gardez les consignes suivantes à l'esprit :

* *Ajouter* -- lorsque vous ajoutez un port hôte, vous associez l'identificateur de port hôte à l'hôte que vous avez créé pour vous connecter à votre matrice de stockage. Vous pouvez saisir manuellement des informations de port à l'aide d'un utilitaire HBA (Host bus adapter).
* *Edit* -- vous pouvez modifier les ports hôte pour déplacer (associer) un port hôte à un autre hôte. Vous avez peut-être déplacé l'adaptateur de bus hôte ou l'initiateur iSCSI vers un autre hôte. Vous devez donc déplacer (associer) le port hôte vers le nouvel hôte.
* *Delete* -- vous pouvez supprimer des ports hôtes pour supprimer (dissocier) des ports hôtes d'un hôte.


.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage[Hosts].
. Sélectionnez l'hôte auquel les ports seront associés, puis cliquez sur l'icône menu:ellipsis icon[Modifier les paramètres].
+
Si vous souhaitez ajouter des ports à un hôte dans un cluster d'hôtes, sélectionnez l'hôte souhaité. Vous ne pouvez pas ajouter de ports au niveau du cluster d'hôtes.

+
Un écran Modifier les paramètres de l'hôte apparaît, affichant les paramètres actuels de l'hôte.

. Modifiez les paramètres de l'identificateur de port hôte selon les besoins.
+
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
Port hôte
 a| 
Vous pouvez choisir l'une des options suivantes :

** *Ajouter un port hôte* -- Cliquez sur *Ajouter un port hôte* pour associer un nouvel identifiant de port hôte à l'hôte. La longueur du nom de l'identifiant de port hôte est déterminée par la technologie de l'interface d'hôte. Les noms d'identifiants de port hôte Fibre Channel et Infiniband doivent comporter 16 caractères. Les noms d'identifiants de port hôte iSCSI ont un maximum de 223 caractères. Le port doit être unique. Un numéro de port déjà configuré n'est pas autorisé.
** *Supprimer (icône X)* -- Cliquez sur l’icône *X* pour supprimer (dissocier) un identifiant de port hôte. L’option de suppression ne supprime pas physiquement le port hôte. Cette option supprime l’association entre le port hôte et l’hôte. À moins que vous ne supprimiez l’adaptateur de bus hôte ou l’initiateur iSCSI, le port hôte est toujours reconnu par le contrôleur.
+
[NOTE]
====
Si vous supprimez un identificateur de port hôte, il n'est plus associé à cet hôte. De même, l'hôte perd l'accès à l'un de ses volumes affectés via cet identifiant de port hôte.

====




 a| 
Nom
 a| 
Si nécessaire, vous pouvez modifier le nom de l'étiquette du port. Le nom de l'étiquette du port doit être unique. Un nom d'étiquette déjà configuré n'est pas autorisé.



 a| 
Secret CHAP
 a| 
Apparaît uniquement pour les hôtes iSCSI. Vous pouvez définir ou modifier le secret CHAP pour les initiateurs (hôtes iSCSI).

System Manager utilise la méthode CHAP (Challenge Handshake Authentication Protocol) qui valide l'identité des cibles et des initiateurs pendant la liaison initiale. L'authentification est basée sur une clé de sécurité partagée appelée secret CHAP.

|===
. Cliquez sur *Enregistrer*.

