---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: 'Vous pouvez modifier les paramètres d"un volume, comme son nom, son affectation hôte, sa taille de segment, sa priorité de modification, sa mise en cache, et ainsi de suite.' 
---
= Modifier les paramètres d'un volume dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres d'un volume : son nom, son affectation hôte, sa taille, sa priorité de modification, sa mise en cache, et ainsi de suite.

.Avant de commencer
Le volume que vous souhaitez modifier est à l'état optimal.


NOTE: Certaines opérations peuvent ne pas être disponibles lorsque des modifications des paramètres de volume sont en cours

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage[Volumes].
. Sélectionnez le volume que vous souhaitez modifier, puis cliquez sur l’icône menu:ellipsis icon[Edit Settings].
+
La fenêtre Edit Volume Settings apparaît, affichant les paramètres de configuration du volume sélectionné.

. Configurez les paramètres de volume selon vos besoins :
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
Nom
 a| 
Affiche le nom du volume. Modifiez le nom d'un volume lorsque le nom actuel n'est plus significatif ou applicable.



 a| 
Hôte
 a| 
Affiche l'affectation du volume. Vous affectez un volume à un hôte ou à un cluster hôte, afin que celui-ci soit accessible aux opérations d'E/S. Cette affectation permet à un hôte ou un cluster hôte d'accéder à un volume particulier ou à un certain nombre de volumes d'une baie de stockage.

** *Affecté à* -- identifie l'hôte ou le cluster hôte qui a accès au volume sélectionné.
** *LUN* -- Un numéro d'unité logique (LUN) est le numéro attribué à l'espace d'adresse qu'un hôte utilise pour accéder à un volume. Le volume est présenté à l'hôte comme capacité sous la forme d'une LUN. Chaque hôte dispose de son propre espace d'adresse de LUN. Par conséquent, la même LUN peut être utilisée par différents hôtes pour accéder à différents volumes.
+

NOTE: Pour les interfaces NVMe, cette colonne affiche l'ID d'espace de noms. Un espace de noms est un stockage NVM formaté pour un accès au bloc. Il est similaire à une unité logique de SCSI, qui se rapporte à un volume de la baie de stockage. L'ID de namespace est l'identifiant unique du contrôleur NVMe pour le namespace et peut être défini sur une valeur comprise entre 1 et 255. Il est similaire à un numéro d'unité logique (LUN) dans SCSI.





 a| 
Dimensionnement des segments
 a| 
Affiche le paramètre de dimensionnement du segment, qui apparaît uniquement pour les volumes d'un groupe de volumes. Vous pouvez modifier la taille du segment pour optimiser les performances.

*Transitions de taille de segment autorisées* -- System Manager détermine les transitions de taille de segment autorisées. Les tailles de segment qui ne sont pas appropriées à partir de la taille de segment actuelle ne sont pas disponibles dans la liste déroulante. Les transitions autorisées sont généralement deux ou la moitié de la taille de segment actuelle. Par exemple, si la taille de segment de volume actuelle est de 32 Kio, une nouvelle taille de segment de volume de 16 Kio ou 64 Kio est autorisée.

*Volumes SSD cache-enabled* -- vous pouvez spécifier une taille de segment de 4 Ko pour les volumes SSD cache-enabled. Veillez à sélectionner la taille de segment 4 Kio uniquement pour les volumes SSD cache prenant en charge les opérations d'E/S de blocs de petite taille (par exemple, 16 tailles de bloc d'E/S Kio ou plus petites). Les performances peuvent être affectées si vous sélectionnez 4 Kio comme taille de segment pour les volumes SSD cache qui gèrent les opérations séquentielles de blocs volumineux.

*Le temps de modification de la taille du segment* -- la durée de modification de la taille du segment d'un volume dépend de ces variables :

** La charge d'E/S de l'hôte
** Priorité de modification du volume
** Nombre de disques dans le groupe de volumes
** Nombre de canaux de transmission
** La puissance de traitement des contrôleurs de la baie de stockage lorsque vous modifiez la taille de segment d'un volume, les performances d'E/S sont affectées, mais vos données restent disponibles.




 a| 
Priorité de modification
 a| 
Affiche le paramètre de priorité de modification, qui apparaît uniquement pour les volumes d'un groupe de volumes.

La priorité de modification définit le temps de traitement alloué aux opérations de modification de volume par rapport aux performances du système. Vous pouvez augmenter la priorité de modification du volume, bien que cela puisse affecter les performances du système.

Déplacez les barres de défilement pour sélectionner un niveau de priorité.

*Taux de priorité de modification* -- le taux de priorité le plus bas bénéficie des performances du système, mais l'opération de modification prend plus de temps. Le taux de priorité le plus élevé bénéficie à l'opération de modification, mais les performances du système peuvent être compromises.

|===
====
. Cliquez sur *Enregistrer*.
+
System Manager modifie les paramètres du volume en fonction de vos sélections.



.Une fois que vous avez terminé
Sélectionnez menu : Storage[Operations in Progress] pour afficher la progression des opérations de modification en cours pour le volume sélectionné.
