---
permalink: sm-storage/change-ssd-cache-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd, cache, settings 
summary: Vous pouvez modifier les paramètres du cache SSD. Les paramètres actuels du cache SSD sont accessibles via l’option Afficher les paramètres. 
---
= Modifier les paramètres du cache SSD dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres du cache SSD. Les paramètres actuels du cache SSD sont accessibles via l’option Afficher les paramètres.

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage [Pools and volume groups].
. Sélectionnez le SSD Cache que vous souhaitez modifier, puis cliquez sur l’icône menu:ellipsis icon[Edit Settings].
+
La fenêtre « Modifier les paramètres du cache SSD » s'affiche.

. Vérifiez ou modifiez les paramètres de cache SSD, le cas échéant.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
Nom
 a| 
Affiche le nom de la mémoire SSD cache que vous pouvez modifier. Vous devez fournir un nom pour le cache SSD.



 a| 
Caractéristiques
 a| 
Indique l'état de la mémoire SSD cache. Les États possibles sont les suivants :

** Optimale
** Inconnu
** Dégradé
** Échec (un état en échec entraîne un événement MEL critique.)
** Suspendu




 a| 
Capacités
 a| 
Affiche la capacité actuelle et la capacité maximale autorisées pour le cache SSD.

La capacité maximale autorisée pour SSD cache dépend de la taille du cache principal du contrôleur :

** Jusqu'à 1 Gio
** 1 Gio vers 2 Gio
** 2 Gio vers 4 Gio
** Plus de 4 Gio




 a| 
Sécurité et DA
 a| 
Affiche l'état sécurité des disques et Data assurance pour le cache SSD.

** *Secure-capable* -- indique si le cache SSD est composé uniquement de disques sécurisés. Un disque sécurisé est un disque à chiffrement automatique qui protège ses données contre tout accès non autorisé.
** *Secure-Enabled* -- indique si la sécurité est activée sur le cache SSD.
** *DA capable* -- indique si le cache SSD est composé uniquement de disques compatibles DA. Un lecteur compatible DA peut rechercher et corriger les erreurs qui peuvent survenir lors de la communication des données entre l'hôte et la matrice de stockage.




 a| 
Objets associés
 a| 
Affiche les volumes et les disques associés à la fonctionnalité SSD cache.

|===
====
. Cliquez sur *Enregistrer*.

