---
permalink: sm-storage/change-cache-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache settings 
summary: 'Modifiez les paramètres du cache de lecture et d"écriture pour affecter les performances d"E/S globales d"un volume.' 
---
= Modifier les paramètres de cache d'un volume
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Modifiez les paramètres du cache de lecture et d'écriture pour affecter les performances d'E/S globales d'un volume.

.Description de la tâche
Gardez ces consignes à l'esprit lorsque vous modifiez les paramètres de cache d'un volume :

* Après avoir ouvert la boîte de dialogue Modifier les paramètres de cache, une icône peut s'afficher en regard des propriétés de cache sélectionnées. Cette icône indique que le contrôleur a temporairement suspendu les opérations de mise en cache.
+
Cette action peut se produire lorsqu'une nouvelle batterie est en cours de chargement, lorsqu'un contrôleur a été retiré ou si le contrôleur a détecté une discordance dans les tailles de cache. Une fois la condition effacée, les propriétés de cache sélectionnées dans la boîte de dialogue deviennent actives. Si les propriétés de cache sélectionnées ne sont pas actives, contactez le support technique.

* Vous pouvez modifier les paramètres du cache pour un seul volume ou pour plusieurs volumes sur une matrice de stockage. Vous pouvez modifier les paramètres de cache de tous les volumes standard ou de tous les volumes fins en même temps.


.Étapes
. Sélectionnez menu:Storage[volumes].
. Sélectionnez un volume, puis sélectionnez menu:autres [Modifier les paramètres du cache].
+
La boîte de dialogue Modifier les paramètres de cache s'affiche. Tous les volumes de la matrice de stockage s'affichent dans cette boîte de dialogue.

. Sélectionnez l'onglet *Basic* pour modifier les paramètres de mise en cache de lecture et d'écriture.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Paramètre de cache | Description 


 a| 
Mise en cache de lecture
 a| 
Le cache de lecture est un tampon qui stocke les données lues à partir des lecteurs. Les données d'une opération de lecture peuvent déjà se trouver dans le cache à partir d'une opération précédente, ce qui évite d'avoir à accéder aux disques. Les données restent dans le cache de lecture jusqu'à ce qu'elles soient supprimées.



 a| 
Mise en cache d'écriture
 a| 
Le cache d'écriture est un tampon qui stocke les données de l'hôte qui n'ont pas encore été écrites sur les lecteurs. Les données restent dans le cache d'écriture jusqu'à ce qu'elles soient écrites sur les disques. La mise en cache d'écriture peut augmenter les performances d'E/S.


NOTE: Le cache est automatiquement vidé après la désactivation de la mise en cache *Write* pour un volume.

|===
====
. Sélectionnez l'onglet *Avancé* pour modifier les paramètres avancés pour les volumes épais. Les paramètres de cache avancés sont disponibles uniquement pour les volumes épais.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Paramètre de cache | Description 


 a| 
Récupération dynamique du cache de lecture
 a| 
La fonctionnalité de lecture préalable en lecture dynamique du cache permet au contrôleur de copier des blocs de données séquentiels supplémentaires dans le cache lors de la lecture des blocs de données d'un disque sur le cache. Cette mise en cache augmente le risque que les futures demandes de données soient traitées à partir du cache. La lecture préalable en cache dynamique est importante pour les applications multimédia qui utilisent des E/S séquentielles Le taux et la quantité de données préextraites dans le cache sont auto-réglables en fonction du débit et de la taille de la demande des lectures de l'hôte. L'accès aléatoire n'entraîne pas la préextraction des données dans le cache. Cette fonction ne s'applique pas lorsque la mise en cache de lecture est désactivée.

Pour un volume fin, la préextraction de lecture dynamique du cache est toujours désactivée et ne peut pas être modifiée.



 a| 
Mise en cache d'écriture sans batterie
 a| 
Le paramètre de mise en cache d'écriture sans batterie permet de poursuivre la mise en cache d'écriture même si les batteries sont manquantes, défectueuses, complètement déchargées ou non complètement chargées. Il n'est généralement pas recommandé de choisir la mise en cache d'écriture sans piles car les données risquent d'être perdues en cas de coupure d'alimentation. En règle générale, la mise en cache des écritures est désactivée temporairement par le contrôleur jusqu'à ce que les batteries soient chargées ou qu'une batterie défectueuse soit remplacée.


CAUTION: *Perte de données possible* -- si vous sélectionnez cette option et que vous ne disposez pas d'une alimentation universelle pour la protection, vous risquez de perdre des données. De plus, vous risquez de perdre des données si vous n'avez pas de batterie de contrôleur et que vous activez l'option *Write cache sans piles*.

Ce paramètre n'est disponible que si vous avez activé la mise en cache des écritures. Ce paramètre n'est pas disponible pour les volumes fins.



 a| 
Mise en cache d'écriture avec mise en miroir
 a| 
La mise en cache d'écriture avec la mise en miroir se produit lorsque les données écrites dans la mémoire cache d'un contrôleur sont également écrites dans la mémoire cache de l'autre contrôleur. Par conséquent, si un contrôleur tombe en panne, l'autre peut mener à bien toutes les opérations d'écriture en attente. La mise en miroir du cache d'écriture n'est disponible que si la mise en cache d'écriture est activée et que deux contrôleurs sont présents. Lors de la création du volume, la mise en cache d'écriture avec mise en miroir est le paramètre par défaut.

Ce paramètre n'est disponible que si vous avez activé la mise en cache des écritures. Ce paramètre n'est pas disponible pour les volumes fins.

|===
====
. Cliquez sur *Enregistrer* pour modifier les paramètres de cache.

