---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group 
summary: 'Vous pouvez modifier les paramètres d"un groupe de snapshots pour modifier son nom, ses paramètres de suppression automatique, le nombre maximal d"images de snapshot autorisées, le point de pourcentage auquel System Manager envoie une notification d"alerte de capacité réservée, ou la règle à utiliser lorsque la capacité réservée atteint son pourcentage maximal défini.' 
---
= Modifier les paramètres de capacité réservée pour un groupe de snapshots dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres d'un groupe de snapshots pour modifier son nom, ses paramètres de suppression automatique, le nombre maximal d'images de snapshot autorisées, le point de pourcentage auquel SANtricity System Manager envoie une notification d'alerte de capacité réservée ou la stratégie à utiliser lorsque la capacité réservée atteint son pourcentage maximal défini.

Lors de la création d'un groupe de snapshots, la capacité réservée est créée pour stocker les données de toutes les images de snapshot contenues dans le groupe.

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage [Pools and volume groups].
. Cliquez sur l'onglet *capacité réservée*.
. Sélectionnez le groupe d'instantanés que vous souhaitez modifier, puis cliquez sur menu : icône de points de suspension [Edit Settings].
+
La fenêtre « Modifier les paramètres du groupe d'instantanés » s'affiche.

. Modifiez les paramètres du groupe de snapshots, le cas échéant.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
*Paramètres de groupe d'instantanés*



 a| 
Nom
 a| 
Nom du groupe de snapshots. La spécification d'un nom pour le groupe de snapshots est requise.



 a| 
Suppression automatique des images Snapshot
 a| 
Paramètre qui maintient le nombre total d'images de snapshot dans le groupe à un maximum défini par l'utilisateur ou en dessous. Lorsque cette option est activée, System Manager supprime automatiquement l'image snapshot la plus ancienne du groupe à chaque création d'un nouvel instantané, afin de respecter le nombre maximal d'images instantanées autorisées pour le groupe.



 a| 
Limite d'image snapshot
 a| 
Valeur configurable qui spécifie le nombre maximal d'images instantanées autorisées pour un groupe de snapshots.



 a| 
*Paramètres de capacité réservés*



 a| 
M'avertir lorsque...
 a| 
Utilisez la case à cocher pour régler le point de pourcentage auquel System Manager envoie une notification d'alerte lorsque la capacité réservée d'un groupe d'instantanés approche pleine.

Lorsque la capacité réservée du groupe de snapshots dépasse le seuil spécifié, System Manager envoie une alerte pour augmenter la capacité réservée ou supprimer des objets inutiles.



 a| 
Règle pour la capacité totale réservée
 a| 
Vous pouvez choisir l'une des règles suivantes :

** *Purge de l'image snapshot la plus ancienne* -- System Manager purge automatiquement l'image snapshot la plus ancienne du groupe de snapshots, ce qui libère la capacité réservée de l'image snapshot pour être réutilisée dans le groupe.
** *Rejeter les écritures dans le volume de base* -- lorsque la capacité réservée atteint son pourcentage maximal défini, System Manager rejette toute demande d'écriture d'E/S au volume de base qui a déclenché l'accès à la capacité réservée.


|===
====
. Cliquez sur *Enregistrer* pour appliquer vos modifications aux paramètres du groupe de snapshots.

