---
permalink: sm-storage/create-pool-automatically.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, automatically 
summary: 'La création du pool est lancée automatiquement lorsque System Manager détecte des disques non assignés dans la baie de stockage. La création automatique de pool vous permet de configurer facilement tous les disques non assignés dans la baie de stockage dans un pool et d"ajouter des disques aux pools existants.' 
---
= Création automatique du pool
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La création de pool est lancée automatiquement lorsque SANtricity System Manager détecte des disques non attribués dans la baie de stockage. La création automatique de pool vous permet de configurer facilement tous les disques non assignés dans la baie de stockage dans un pool et d'ajouter des disques aux pools existants.

.Avant de commencer
Vous pouvez lancer la boîte de dialogue Configuration automatique du pool lorsque l'une des conditions suivantes est vraie :

* Au moins un lecteur non affecté a été détecté qui peut être ajouté à un pool existant avec des types de disques similaires.
* Onze (11) disques non assignés ou plus ont été détectés qui peuvent être utilisés pour créer un nouveau pool (s'ils ne peuvent pas être ajoutés à un pool existant en raison de types de disques différents).


.Description de la tâche
Gardez à l'esprit les éléments suivants :

* Lorsque vous ajoutez des disques à une baie de stockage, System Manager détecte automatiquement les disques et vous invite à créer un ou plusieurs pools en fonction du type de disque et de la configuration actuelle.
* Si des pools ont été définis précédemment, System Manager vous invite automatiquement à ajouter les disques compatibles à un pool existant. Lorsque de nouveaux disques sont ajoutés à un pool existant, System Manager redistribue automatiquement les données en fonction de la nouvelle capacité, notamment les nouveaux lecteurs que vous avez ajoutés.
* Lors de la configuration d'une baie de stockage EF600 ou EF300, assurez-vous que chaque contrôleur a accès à un nombre égal de disques dans les 12 premiers emplacements et à un nombre égal de disques dans les 12 derniers slots. Cette configuration permet aux contrôleurs d'utiliser plus efficacement les deux bus PCIe côté disque.


Vous pouvez lancer la boîte de dialogue Configuration automatique du pool en utilisant l'une des méthodes suivantes :

* Lorsque la capacité non affectée est détectée, la recommandation de configuration automatique du pool s'affiche sur la page d'accueil de la zone notification. Cliquez sur *Afficher la configuration automatique du pool* pour lancer la boîte de dialogue.
* Vous pouvez également lancer la boîte de dialogue Configuration automatique du pool à partir de la page pools et groupes de volumes, comme décrit dans la tâche suivante.


.Étapes
. Menu Sélectionner:Storage[pools & Volume Groups].
. Sélectionnez menu:More [lancer la configuration automatique du pool].
+
Le tableau des résultats répertorie les nouveaux pools, les pools existants avec disques ajoutés, ou les deux. Par défaut, un nouveau pool est nommé avec un numéro séquentiel.

+
System Manager effectue les tâches suivantes :

+
** Crée un pool unique si le nombre de disques dotés du même type de disque (HDD ou SSD) et ayant la même capacité est suffisant.
** Plusieurs pools sont créés si la capacité non affectée se compose de différents types de disques.
** Ajoute les disques à un pool existant si un pool est déjà défini dans la baie de stockage et que vous ajoutez de nouveaux disques du même type de disque au pool.
** Ajoute les disques du même type au pool existant, et utilisez les autres types de disques pour créer différents pools si les nouveaux disques sont de types différents.


. Pour modifier le nom d'un nouveau pool, cliquez sur l'icône *Modifier* (le crayon).
. Pour afficher d'autres caractéristiques du pool, placez le curseur sur ou appuyez sur l'icône *Détails* (la page).
+
Des informations sur le type de disque, la fonctionnalité de sécurité, l'assurance de données (DA), la protection contre la perte de tiroir et la protection contre la perte de tiroir s'affichent.

+
Pour les baies de stockage EF600 et EF300, les paramètres sont également affichés pour le provisionnement des ressources et la taille des blocs de volume.

. Cliquez sur *Accept*.

