---
permalink: sm-storage/create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volumes 
summary: 'Vous créez des volumes pour ajouter de la capacité de stockage à une charge de travail spécifique aux applications et rendre les volumes créés visibles pour un hôte ou un cluster hôte spécifique. En outre, la séquence de création de volumes offre des options permettant d"allouer des quantités spécifiques de capacité à chaque volume que vous souhaitez créer.' 
---
= Créer des volumes
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous créez des volumes pour ajouter de la capacité de stockage à une charge de travail spécifique aux applications et rendre les volumes créés visibles pour un hôte ou un cluster hôte spécifique. En outre, la séquence de création de volumes offre des options permettant d'allouer des quantités spécifiques de capacité à chaque volume que vous souhaitez créer.

.Description de la tâche
La plupart des types d'application par défaut à une configuration de volume définie par l'utilisateur. Une configuration intelligente est appliquée à certains types d'applications lors de la création du volume. Par exemple, si vous créez des volumes pour une application Microsoft Exchange, vous devez connaître le nombre de boîtes aux lettres dont vous avez besoin, les besoins moyens de vos boîtes aux lettres et le nombre de copies de la base de données que vous souhaitez. System Manager utilise ces informations pour créer une configuration de volume optimale, qui peut être modifiée selon vos besoins.

Le processus de création d'un volume est une procédure à plusieurs étapes.



== Étape 1 : sélectionnez l'hôte d'un volume

Vous créez des volumes pour ajouter de la capacité de stockage à une charge de travail spécifique aux applications et rendre les volumes créés visibles pour un hôte ou un cluster hôte spécifique. En outre, la séquence de création de volumes offre des options permettant d'allouer des quantités spécifiques de capacité à chaque volume que vous souhaitez créer.

.Avant de commencer
* Les hôtes ou clusters hôtes valides existent sous la mosaïque hôtes.
* Des identifiants de port hôte ont été définis pour l'hôte.
* Avant de créer un volume DA, la connexion hôte que vous prévoyez d'utiliser doit prendre en charge DA. Si l'une des connexions hôte sur les contrôleurs de votre matrice de stockage ne prend pas en charge DA, les hôtes associés ne peuvent pas accéder aux données sur les volumes DA.


.Description de la tâche
Gardez ces consignes à l'esprit lorsque vous attribuez des volumes :

* Le système d'exploitation d'un hôte peut disposer de limites spécifiques sur le nombre de volumes accessibles par l'hôte. Gardez cette limitation à l'esprit lorsque vous créez des volumes pour une utilisation par un hôte spécifique.
* Vous pouvez définir une affectation pour chaque volume de la matrice de stockage.
* Les volumes affectés sont partagés entre les contrôleurs de la baie de stockage.
* Le même numéro d'unité logique (LUN) ne peut pas être utilisé deux fois par un hôte ou un cluster hôte pour accéder à un volume. Vous devez utiliser une LUN unique.
* Pour accélérer le processus de création de volumes, vous pouvez ignorer l'étape d'affectation des hôtes afin que les nouveaux volumes soient initialisés hors ligne.


[NOTE]
====
L'affectation d'un volume à un hôte échoue si vous tentez d'attribuer un volume à un cluster hôte en conflit avec une affectation établie pour un hôte dans les clusters hôtes.

====
.Étapes
. Sélectionnez menu:Storage[volumes].
. Sélectionnez menu:Créer [Volume].
+
La boîte de dialogue Créer des volumes s'affiche.

. Dans la liste déroulante, sélectionnez un hôte ou un cluster hôte spécifique auquel vous souhaitez attribuer des volumes ou choisissez d'affecter ultérieurement l'hôte ou le cluster hôte.
. Pour continuer la séquence de création du volume pour l'hôte ou le cluster hôte sélectionné, cliquez sur *Suivant* et allez à <<Étape 2 : sélectionnez une charge de travail pour un volume>>.
+
La boîte de dialogue Sélectionner la charge de travail s'affiche.





== Étape 2 : sélectionnez une charge de travail pour un volume

Sélectionnez une charge de travail pour personnaliser la configuration de la baie de stockage pour une application spécifique, telle que Microsoft SQL Server, Microsoft Exchange, les applications de vidéosurveillance ou VMware. Vous pouvez sélectionner « autre application » si l'application que vous souhaitez utiliser sur cette baie de stockage n'est pas répertoriée.

.Description de la tâche
Cette tâche décrit comment créer des volumes pour une charge de travail existante.

* _Lorsque vous créez des volumes à l'aide d'une charge de travail spécifique à l'application_, le système peut recommander une configuration de volume optimisée afin de minimiser les conflits entre les E/S de charge de travail d'application et le trafic provenant de votre instance d'application. Vous pouvez revoir la configuration de volume recommandée et modifier, ajouter ou supprimer les volumes et les caractéristiques recommandés par le système à l'aide de la boîte de dialogue Ajouter/Modifier des volumes.
* _Lorsque vous créez des volumes à l'aide d'autres applications (ou d'applications sans support de création de volume spécifique), vous spécifiez manuellement la configuration du volume à l'aide de la boîte de dialogue Ajouter/Modifier des volumes.


.Étapes
. Effectuez l'une des opérations suivantes :
+
** Sélectionnez l'option *Créer des volumes pour une charge de travail existante* pour créer des volumes pour une charge de travail existante.
** Sélectionnez l'option *Créer une nouvelle charge de travail* pour définir une nouvelle charge de travail pour une application prise en charge ou pour d'autres applications.
+
*** Dans la liste déroulante, sélectionnez le nom de l'application pour laquelle vous souhaitez créer la nouvelle charge de travail.
+
Sélectionnez l'une des « autres » entrées si l'application que vous souhaitez utiliser sur cette matrice de stockage n'est pas répertoriée.

*** Saisissez un nom pour la charge de travail à créer.




. Cliquez sur *Suivant*.
. Si votre charge de travail est associée à un type d'application pris en charge, entrez les informations requises. Sinon, rendez-vous à <<Étape 3 : ajout ou modification de volumes>>.




== Étape 3 : ajout ou modification de volumes

System Manager peut suggérer une configuration de volume en fonction de l'application ou du workload sélectionné. Cette configuration de volume est optimisée en fonction du type d'application pris en charge par la charge de travail. Vous pouvez accepter la configuration de volume recommandée ou la modifier si nécessaire. Si vous avez sélectionné l'une des autres applications, vous devez spécifier manuellement les volumes et les caractéristiques que vous souhaitez créer.

.Avant de commencer
* Les pools ou les groupes de volumes doivent disposer d'une capacité disponible suffisante.
* Le nombre maximal de volumes autorisés dans un groupe de volumes est de 256.
* Le nombre maximum de volumes autorisé dans un pool dépend du modèle du système de stockage :
+
** 2,048 volumes (EF600 et E5700 Series)
** 1,024 volumes (EF300)
** 512 volumes (E2800 Series)


* Pour créer un volume activé pour Data assurance (DA), la connexion hôte que vous prévoyez d'utiliser doit prendre en charge DA.
+
.Sélection d'un pool ou d'un groupe de volumes qui prend en charge la sécurité
[%collapsible]
====
Si vous souhaitez créer un volume DA activé, sélectionnez un pool ou un groupe de volumes qui est compatible DA (recherchez *Oui* en regard de "DA" dans la table des candidats de groupe de volumes et de pools).

Les fonctionnalités DE DA sont présentées au niveau du pool et du groupe de volumes dans System Manager. DA protection vérifie et corrige les erreurs susceptibles de se produire au fur et à mesure du transfert des données entre les contrôleurs et les disques. La sélection d'un pool ou d'un groupe de volumes capable de gérer le nouveau volume garantit la détection et la correction des erreurs éventuelles.

Si l'une des connexions hôte sur les contrôleurs de votre matrice de stockage ne prend pas en charge DA, les hôtes associés ne peuvent pas accéder aux données sur les volumes DA.

====
* Pour créer un volume sécurisé, une clé de sécurité doit être créée pour la matrice de stockage.
+
.Sélection d'un pool ou d'un groupe de volumes qui prend en charge la sécurité
[%collapsible]
====
Si vous souhaitez créer un volume sécurisé, sélectionnez un pool ou un groupe de volumes qui est sécurisé et capable (recherchez *Oui* en regard de « sécurisé » dans la table des candidats de groupe de volumes et de pools).

Les fonctionnalités de sécurité des disques sont présentées au niveau du pool et du groupe de volumes dans System Manager. Les disques sécurisés empêchent tout accès non autorisé aux données d'un disque physiquement retiré de la baie de stockage. Un disque sécurisé crypte les données pendant les écritures et les décrypte pendant les lectures à l'aide d'une clé de cryptage unique_.

Un pool ou un groupe de volumes peut contenir à la fois des disques sécurisés et non sécurisés, mais tous les disques doivent être sécurisés pour utiliser leurs fonctionnalités de chiffrement.

====
* Pour créer un volume provisionné en ressources, tous les disques doivent être des disques NVMe avec l'option DULBE (Logical Block Error) désallocation ou non écrite.


.Description de la tâche
La création de volumes s'effectue à partir de pools ou de groupes de volumes. La boîte de dialogue Ajouter/Modifier des volumes affiche tous les pools et groupes de volumes éligibles de la baie de stockage. Pour chaque pool et groupe de volumes éligibles, le nombre de disques disponibles et la capacité totale disponible s'affichent.

Pour certaines charges de travail spécifiques à une application, chaque pool ou groupe de volumes éligible affiche la capacité proposée en fonction de la configuration de volume suggérée et indique la capacité libre restante en Gio. Pour les autres charges de travail, la capacité proposée s'affiche lors de l'ajout de volumes à un pool ou à un groupe de volumes, puis lorsque vous spécifiez la capacité indiquée.

.Étapes
. Choisissez l'une des actions suivantes selon que vous avez sélectionné une autre charge de travail ou une charge de travail spécifique à une application :
+
** *Autre* -- cliquez sur *Ajouter nouveau volume* dans chaque pool ou groupe de volumes que vous souhaitez utiliser pour créer un ou plusieurs volumes.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Champ | Description 


 a| 
Nom du volume
 a| 
Lors de la séquence de création du volume, System Manager attribue un nom par défaut à un volume. Vous pouvez accepter le nom par défaut ou fournir une description plus détaillée indiquant le type de données stockées dans le volume.



 a| 
Capacité déclarée
 a| 
Définissez la capacité du nouveau volume et les unités de capacité à utiliser (MIB, Gio ou Tio). Pour les volumes épais, la capacité minimale est de 1 Mio, et la capacité maximale est déterminée par le nombre et la capacité des disques du pool ou du groupe de volumes.

N'oubliez pas que la capacité de stockage est également nécessaire pour les services de copie (images Snapshot, volumes Snapshot, copies de volume et miroirs distants) ; par conséquent, n'allouez pas toutes la capacité aux volumes standard.

La capacité d'un pool est allouée par incréments de 4 Gio ou 8 Gio, selon le type de disque. Toute capacité non utilisable n'est pas un multiple de 4 ou 8 Gio est allouée, mais pas utilisable. Pour vérifier la disponibilité de toute la capacité, spécifiez la capacité par incréments de 4 Gio ou 8 Gio. Si une capacité inutilisable, le seul moyen de le récupérer est d'augmenter la capacité du volume.



 a| 
Taille de bloc du volume (EF300 et EF600 uniquement)
 a| 
Affiche les tailles de blocs pouvant être créées pour le volume :

*** 512 -- 512 octets
*** 4 Ko -- 4,096 octets




 a| 
Taille du segment
 a| 
Affiche le paramètre de dimensionnement du segment, qui apparaît uniquement pour les volumes d'un groupe de volumes. Vous pouvez modifier la taille du segment pour optimiser les performances.

*Transitions de taille de segment autorisées* -- System Manager détermine les transitions de taille de segment autorisées. Les tailles de segment qui ne sont pas appropriées à partir de la taille de segment actuelle ne sont pas disponibles dans la liste déroulante. Les transitions autorisées sont généralement deux ou la moitié de la taille de segment actuelle. Par exemple, si la taille de segment de volume actuelle est de 32 Kio, une nouvelle taille de segment de volume de 16 Kio ou 64 Kio est autorisée.

*Volumes SSD cache-enabled* -- vous pouvez spécifier une taille de segment de 4 Ko pour les volumes SSD cache-enabled. Veillez à sélectionner la taille de segment 4 Kio uniquement pour les volumes SSD cache prenant en charge les opérations d'E/S de blocs de petite taille (par exemple, 16 tailles de bloc d'E/S Kio ou plus petites). Les performances peuvent être affectées si vous sélectionnez 4 Kio comme taille de segment pour les volumes SSD cache qui gèrent les opérations séquentielles de blocs volumineux.

*Le temps de modification de la taille du segment* -- la durée de modification de la taille du segment d'un volume dépend de ces variables :

*** La charge d'E/S de l'hôte
*** Priorité de modification du volume
*** Nombre de disques dans le groupe de volumes
*** Nombre de canaux de transmission
*** La puissance de traitement des contrôleurs de la baie de stockage


Lorsque vous modifiez la taille de segment d'un volume, les performances d'E/S sont affectées, mais vos données restent disponibles.



 a| 
Sécurité
 a| 
*Oui* apparaît en regard de « sécurisé » uniquement si les lecteurs du pool ou du groupe de volumes sont sécurisés.

La sécurité du lecteur empêche tout accès non autorisé aux données d'un lecteur qui est physiquement retiré de la matrice de stockage. Cette option n'est disponible que lorsque la fonction sécurité du lecteur a été activée et qu'une clé de sécurité est configurée pour la matrice de stockage.

Un pool ou un groupe de volumes peut contenir à la fois des disques sécurisés et non sécurisés, mais tous les disques doivent être sécurisés pour utiliser leurs fonctionnalités de chiffrement.



 a| 
DA
 a| 
*Oui* apparaît en regard de "DA" uniquement si les lecteurs du pool ou du groupe de volumes prennent en charge Data assurance (DA).

DA augmente l'intégrité des données dans l'ensemble du système de stockage. DA permet à la matrice de stockage de vérifier si des erreurs peuvent se produire lorsque les données sont transférées via les contrôleurs vers les disques. L'utilisation de DA pour le nouveau volume garantit la détection de toute erreur.



 a| 
Ressource provisionnée (EF300 et EF600 uniquement)
 a| 
*Oui* apparaît en regard de "Resource Provisioné" uniquement si les lecteurs prennent en charge cette option. La fonctionnalité de provisionnement des ressources est disponible dans les baies de stockage EF300 et EF600, ce qui permet de mettre immédiatement les volumes en service sans processus d'initialisation en arrière-plan.

|===
====
** *Charge de travail spécifique à une application* -- cliquez sur *Suivant* pour accepter les volumes et les caractéristiques recommandés par le système pour la charge de travail sélectionnée, ou cliquez sur *Modifier les volumes* pour modifier, ajouter ou supprimer les volumes et les caractéristiques recommandés par le système pour la charge de travail sélectionnée.
+
.Détails du champ
[%collapsible]
====
[cols="1a,1a"]
|===
| Champ | Description 


 a| 
Nom du volume
 a| 
Lors de la séquence de création du volume, System Manager attribue un nom par défaut à un volume. Vous pouvez accepter le nom par défaut ou fournir une description plus détaillée indiquant le type de données stockées dans le volume.



 a| 
Capacité déclarée
 a| 
Définissez la capacité du nouveau volume et les unités de capacité à utiliser (MIB, Gio ou Tio). Pour les volumes épais, la capacité minimale est de 1 Mio, et la capacité maximale est déterminée par le nombre et la capacité des disques du pool ou du groupe de volumes.

N'oubliez pas que la capacité de stockage est également nécessaire pour les services de copie (images Snapshot, volumes Snapshot, copies de volume et miroirs distants) ; par conséquent, n'allouez pas toutes la capacité aux volumes standard.

La capacité d'un pool est allouée par incréments de 4 Gio ou 8 Gio, selon le type de disque. Toute capacité non utilisable n'est pas un multiple de 4 ou 8 Gio est allouée, mais pas utilisable. Pour vérifier la disponibilité de toute la capacité, spécifiez la capacité par incréments de 4 Gio ou 8 Gio. Si une capacité inutilisable, le seul moyen de le récupérer est d'augmenter la capacité du volume.



 a| 
Type de Volume
 a| 
Type de volume indique le type de volume créé pour une charge de travail spécifique à l'application.



 a| 
Taille de bloc du volume (EF300 et EF600 uniquement)
 a| 
Affiche les tailles de blocs pouvant être créées pour le volume :

*** 512 -- 512 octets
*** 4 Ko -- 4,096 octets




 a| 
Taille du segment
 a| 
Affiche le paramètre de dimensionnement du segment, qui apparaît uniquement pour les volumes d'un groupe de volumes. Vous pouvez modifier la taille du segment pour optimiser les performances.

*Transitions de taille de segment autorisées* -- System Manager détermine les transitions de taille de segment autorisées. Les tailles de segment qui ne sont pas appropriées à partir de la taille de segment actuelle ne sont pas disponibles dans la liste déroulante. Les transitions autorisées sont généralement deux ou la moitié de la taille de segment actuelle. Par exemple, si la taille de segment de volume actuelle est de 32 Kio, une nouvelle taille de segment de volume de 16 Kio ou 64 Kio est autorisée.

*Volumes SSD cache-enabled* -- vous pouvez spécifier une taille de segment de 4 Ko pour les volumes SSD cache-enabled. Veillez à sélectionner la taille de segment 4 Kio uniquement pour les volumes SSD cache prenant en charge les opérations d'E/S de blocs de petite taille (par exemple, 16 tailles de bloc d'E/S Kio ou plus petites). Les performances peuvent être affectées si vous sélectionnez 4 Kio comme taille de segment pour les volumes SSD cache qui gèrent les opérations séquentielles de blocs volumineux.

*Le temps de modification de la taille du segment* -- la durée de modification de la taille du segment d'un volume dépend de ces variables :

*** La charge d'E/S de l'hôte
*** Priorité de modification du volume
*** Nombre de disques dans le groupe de volumes
*** Nombre de canaux de transmission
*** La puissance de traitement des contrôleurs de la baie de stockage lorsque vous modifiez la taille de segment d'un volume, les performances d'E/S sont affectées, mais vos données restent disponibles.




 a| 
Sécurité
 a| 
*Oui* apparaît en regard de « sécurisé » uniquement si les lecteurs du pool ou du groupe de volumes sont sécurisés.

La sécurité du disque empêche les accès non autorisés aux données d'un disque qui est physiquement retiré de la matrice de stockage. Cette option n'est disponible que lorsque la fonction de sécurité du lecteur a été activée et qu'une clé de sécurité est configurée pour la matrice de stockage.

Un pool ou un groupe de volumes peut contenir à la fois des disques sécurisés et non sécurisés, mais tous les disques doivent être sécurisés pour utiliser leurs fonctionnalités de chiffrement.



 a| 
DA
 a| 
*Oui* apparaît en regard de "DA" uniquement si les lecteurs du pool ou du groupe de volumes prennent en charge Data assurance (DA).

DA augmente l'intégrité des données dans l'ensemble du système de stockage. DA permet à la matrice de stockage de vérifier si des erreurs peuvent se produire lorsque les données sont transférées via les contrôleurs vers les disques. L'utilisation de DA pour le nouveau volume garantit la détection de toute erreur.



 a| 
Ressource provisionnée (EF300 et EF600 uniquement)
 a| 
*Oui* apparaît en regard de "Resource Provisioné" uniquement si les lecteurs prennent en charge cette option. La fonctionnalité de provisionnement des ressources est disponible dans les baies de stockage EF300 et EF600, ce qui permet de mettre immédiatement les volumes en service sans processus d'initialisation en arrière-plan.

|===
====


. Pour continuer la séquence de création du volume pour l'application sélectionnée, cliquez sur *Suivant* et allez à <<Étape 4 : consultez la configuration du volume>>.




== Étape 4 : consultez la configuration du volume

Examinez un récapitulatif des volumes que vous envisagez de créer et apportez les modifications nécessaires.

.Étapes
. Vérifiez les volumes que vous souhaitez créer. Cliquez sur *Retour* pour apporter des modifications.
. Lorsque vous êtes satisfait de la configuration de votre volume, cliquez sur *Finish*.


.Résultats
System Manager crée les nouveaux volumes dans les pools et groupes de volumes sélectionnés, puis affiche les nouveaux volumes dans la table tous les volumes.

.Une fois que vous avez terminé
* Apportez les modifications nécessaires au système d'exploitation sur l'hôte de l'application afin que les applications puissent utiliser le volume.
* Exécutez l'utilitaire spécifique au système d'exploitation (disponible auprès d'un fournisseur tiers), puis exécutez la commande SMcli `-identifyDevices` pour mettre en corrélation les noms de volumes avec les noms de matrices de stockage hôte.
+
Le SMcli est disponible directement via le Gestionnaire système SANtricity. Cette version téléchargeable du SMcli est disponible sur les systèmes EF600, EF300, E5700, EF570, E2800, Et des contrôleurs EF280. Pour télécharger le SMcli dans le Gestionnaire système SANtricity, sélectionnez *Paramètres* > *système* et *Add-ons* > *interface de ligne de commande* .


