---
permalink: sm-storage/delete-host-or-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, host, host cluster 
summary: Vous pouvez supprimer un hôte ou un cluster hôte. 
---
= Supprime l'hôte ou le cluster hôte
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un hôte ou un cluster hôte.

.Description de la tâche
Suivez les consignes ci-dessous lorsque vous supprimez un hôte ou un cluster hôte :

* Toute affectation de volumes spécifique est supprimée et les volumes associés sont disponibles dans le cadre d'une nouvelle affectation.
* Si l'hôte fait partie d'un cluster hôte ayant ses propres affectations spécifiques, le cluster hôte n'est pas affecté. Cependant, si l'hôte fait partie d'un cluster hôte sans autres affectations, le cluster hôte et tout autre hôte ou identifiant de port hôte associés héritent de toute affectation par défaut.
* Tous les identificateurs de port hôte associés à l'hôte deviennent non définis.


.Étapes
. Sélectionnez menu:Storage[hosts].
. Sélectionnez l'hôte ou le cluster hôte que vous souhaitez supprimer, puis cliquez sur *Supprimer*.
+
La boîte de dialogue de confirmation s'affiche.

. Confirmez que vous souhaitez effectuer l'opération, puis cliquez sur *Supprimer*.


.Résultats
Si vous avez supprimé un hôte, le système effectue les opérations suivantes :

* Supprime l'hôte et, le cas échéant, le supprime du cluster hôte.
* Supprime l'accès aux volumes affectés.
* Renvoie les volumes associés à un état non affecté.
* Renvoie les identificateurs de port hôte associés à l'hôte à un état non associé.


Si vous avez supprimé un cluster hôte, le système effectue les opérations suivantes :

* Supprime le cluster hôte et ses hôtes associés (le cas échéant).
* Supprime l'accès aux volumes affectés.
* Renvoie les volumes associés à un état non affecté.
* Renvoie les identificateurs de port hôte associés aux hôtes à un état non associé.

