---
permalink: sm-storage/delete-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, volume 
summary: 'Vous pouvez supprimer un volume Snapshot ou un volume Snapshot de groupe de cohérence Snapshot qui n"est plus nécessaire à des fins de sauvegarde ou de test d"applications logicielles.' 
---
= Supprimez le volume snapshot
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un volume Snapshot ou un volume Snapshot de groupe de cohérence Snapshot qui n'est plus nécessaire à des fins de sauvegarde ou de test d'applications logicielles.

Vous pouvez également indiquer si vous souhaitez supprimer le volume de capacité réservé de snapshot associé à un `read-write` volume de snapshot ou conservez le volume de capacité réservé de l'instantané comme volume non attribué.

.Description de la tâche
La suppression d'un volume de base supprime automatiquement tout volume snapshot associé ou tout volume snapshot de groupe de cohérence. Vous ne pouvez pas supprimer un volume de snapshot qui se trouve dans une copie de volume avec l'état *en cours*.

.Étapes
. Sélectionnez menu:stockage[snapshots].
. Sélectionnez l'onglet *Snapshot volumes*.
+
System Manager affiche tous les volumes de snapshot associés à la matrice de stockage.

. Sélectionnez le volume de snapshot que vous souhaitez supprimer, puis sélectionnez menu:tâches rares[Supprimer].
. Confirmez que vous souhaitez effectuer l'opération, puis cliquez sur *Supprimer*.


.Résultats
System Manager effectue les actions suivantes :

* Supprime tous les volumes snapshot membres (pour un volume snapshot de groupe de cohérence Snapshot).
* Supprime toutes les affectations d'hôtes associées.

