---
permalink: sm-storage/delete-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, schedule 
summary: 'Si vous ne souhaitez plus collecter d"images de snapshot, vous pouvez supprimer un planning de snapshots existant.' 
---
= Supprimer une planification d'instantanés dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous ne souhaitez plus collecter d'images de snapshot, vous pouvez supprimer un planning de snapshots existant.

.Description de la tâche
Lorsque vous supprimez un planning de snapshots, les images de snapshot associées ne sont pas supprimées avec lui. Si vous pensez que la collection d'images d'instantanés peut être reprise à un moment donné, vous devez interrompre la planification d'instantanés au lieu de la supprimer.

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage[Snapshots].
. Cliquez sur l'onglet *Snapshots Schedules*.
. Sélectionnez la planification d'instantané que vous souhaitez supprimer, cliquez sur *Delete*, et confirmez l'opération.


.Résultats
Le système supprime tous les attributs de planification du volume de base ou du groupe de cohérence snapshot.
