---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: Vous pouvez activer ou désactiver le provisionnement de ressources sur un pool ou un groupe de volumes existant. 
---
= Activer ou désactiver le provisionnement des ressources sur les groupes de volumes et les pools existants dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour tous les disques compatibles DULBE, vous pouvez activer ou désactiver le provisionnement de ressources sur les volumes existants d'un pool ou d'un groupe de volumes.

L'allocation de ressources est une fonctionnalité disponible sur les baies de stockage EF80, EF50, EF300/EF300C et EF600/EF600C, qui permet aux volumes d'être mis en service immédiatement sans processus d'initialisation en arrière-plan. Tous les blocs de disque affectés au volume sont désalloués (non mappés), ce qui peut améliorer la durée de vie des SSD et augmenter les performances d'écriture maximales.

Par défaut, le provisionnement de ressources est activé sur les systèmes sur lesquels les disques prennent en charge DULBE. Il n'est pas nécessaire d'activer le provisionnement des ressources à moins que vous ne l'ayez précédemment désactivé.

.Avant de commencer
* Vous devez disposer d'une baie de stockage EF80, EF50, EF300 ou EF600.
* Vous devez disposer de groupes ou de pools de volume SSD, où tous les disques prennent en charge la fonctionnalité de restauration d'erreur DULBE (Logical Block Error Enable) de NVMe avec une gestion simplifiée ou non écrite. Sinon, l'option de provisionnement de ressources n'est pas disponible.


.Description de la tâche
Lorsque vous activez le provisionnement des ressources pour les groupes de volumes et les pools existants, tous les volumes du groupe ou pool de volumes sélectionné sont modifiés afin de permettre la désallocation des blocs. Ce processus peut impliquer une opération en arrière-plan pour assurer une allocation cohérente à la granularité du mappage. Cette opération ne permet pas d'annuler le mappage sur un espace. Une fois l'opération en arrière-plan terminée, le système d'exploitation doit annuler le mappage sur les blocs inutilisés afin de créer de l'espace libre.

Lorsque vous désactivez le provisionnement des ressources pour les groupes de volumes ou les pools existants, une opération en arrière-plan réécrit tous les blocs logiques de chaque volume. Les données existantes restent intactes. Les écritures regroupent ou provisionne les blocs sur les disques associés au groupe ou au pool de volumes.


NOTE: Pour les nouveaux groupes et pools de volumes, vous pouvez activer ou désactiver le provisionnement de ressources à partir du menu:Paramètres[système > Paramètres supplémentaires > Activer/Désactiver les volumes provisionnés par ressource].

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage [Pools and volume groups].
. Cliquez sur l'icône *points de suspension* et sélectionnez soit *Activer l'approvisionnement en ressources* soit *Désactiver l'approvisionnement en ressources* pour le pool ou le groupe de volumes sélectionné.
. Dans la boîte de dialogue, confirmer l'opération.



NOTE: *Si vous avez réactivé DULBE* -- une fois l'opération d'arrière-plan terminée, vous devrez peut-être redémarrer l'hôte pour détecter les modifications de configuration DULBE, puis remonter tous les systèmes de fichiers.
