---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: Vous pouvez activer ou désactiver le provisionnement de ressources sur un pool ou un groupe de volumes existant. 
---
= Activez ou désactivez le provisionnement de ressources sur les groupes de volumes et les pools existants
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour tous les disques compatibles DULBE, vous pouvez activer ou désactiver le provisionnement de ressources sur les volumes existants d'un pool ou d'un groupe de volumes.

Le provisionnement des ressources est une fonctionnalité disponible dans les baies de stockage EF300 et EF600, qui permet de mettre les volumes en service immédiatement sans processus d'initialisation en arrière-plan. La libération de tous les blocs de disque attribués au volume est effectuée (non mappés), ce qui permet d'améliorer la durée de vie du disque SSD et d'augmenter les performances d'écriture maximales.

Par défaut, le provisionnement de ressources est activé sur les systèmes sur lesquels les disques prennent en charge DULBE. Il n'est pas nécessaire d'activer le provisionnement des ressources à moins que vous ne l'ayez précédemment désactivé.

.Avant de commencer
* Vous devez disposer d'une baie de stockage EF300 ou EF600.
* Vous devez disposer de groupes ou de pools de volume SSD, où tous les disques prennent en charge la fonctionnalité de restauration d'erreur DULBE (Logical Block Error Enable) de NVMe avec une gestion simplifiée ou non écrite. Sinon, l'option de provisionnement de ressources n'est pas disponible.


.Description de la tâche
Lorsque vous activez le provisionnement des ressources pour les groupes de volumes et les pools existants, tous les volumes du groupe ou pool de volumes sélectionné sont modifiés afin de permettre la désallocation des blocs. Ce processus peut impliquer une opération en arrière-plan pour assurer une allocation cohérente à la granularité du mappage. Cette opération ne permet pas d'annuler le mappage sur un espace. Une fois l'opération en arrière-plan terminée, le système d'exploitation doit annuler le mappage sur les blocs inutilisés afin de créer de l'espace libre.

Lorsque vous désactivez le provisionnement des ressources pour les groupes de volumes ou les pools existants, une opération en arrière-plan réécrit tous les blocs logiques de chaque volume. Les données existantes restent intactes. Les écritures regroupent ou provisionne les blocs sur les disques associés au groupe ou au pool de volumes.


NOTE: Pour les nouveaux groupes et pools de volumes, vous pouvez activer ou désactiver le provisionnement de ressources à partir du menu:Paramètres[système > Paramètres supplémentaires > Activer/Désactiver les volumes provisionnés par ressource].

.Étapes
. Menu Sélectionner:Storage[pools & Volume Groups].
. Sélectionnez un pool ou un groupe de volumes dans la liste.
+
Vous ne pouvez sélectionner qu'un seul pool ou groupe de volumes à la fois. Faites défiler la liste pour afficher d'autres pools ou groupes de volumes.

. Sélectionnez *tâches rares*, puis *Activer le provisioning de ressources* ou *Désactiver le provisioning de ressources*.
. Dans la boîte de dialogue, confirmer l'opération.



NOTE: *Si vous avez réactivé DULBE* -- une fois l'opération d'arrière-plan terminée, vous devrez peut-être redémarrer l'hôte pour détecter les modifications de configuration DULBE, puis remonter tous les systèmes de fichiers.
