---
permalink: sm-storage/how-do-i-know-which-host-operating-system-type-is-correct.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host operating system, type, 
summary: 'Le champ Type de système d"exploitation hôte contient le système d"exploitation de l"hôte. Vous pouvez sélectionner le type d"hôte recommandé dans la liste déroulante ou autoriser l"agent de contexte hôte (HCA) à configurer l"hôte et le type de système d"exploitation hôte approprié.' 
---
= Comment savoir quel type de système d'exploitation hôte est correct ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le champ Type de système d'exploitation hôte contient le système d'exploitation de l'hôte. Vous pouvez sélectionner le type d'hôte recommandé dans la liste déroulante ou autoriser l'agent de contexte hôte (HCA) à configurer l'hôte et le type de système d'exploitation hôte approprié.

Les types d'hôte qui apparaissent dans la liste déroulante dépendent du modèle de la matrice de stockage et de la version du micrologiciel. Les versions les plus récentes affichent d'abord les options les plus courantes, qui sont les plus susceptibles d'être appropriées. L'apparence sur cette liste n'implique pas que l'option est entièrement prise en charge.

[NOTE]
====
Pour plus d'informations sur la prise en charge des hôtes, reportez-vous au https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp"^].

====
Certains des types d'hôtes suivants peuvent apparaître dans la liste :

[cols="35h,~"]
|===
| Type de système d'exploitation hôte | Système d'exploitation et pilote multivoie 


 a| 
Linux DM-MP (Kernel 3.10 ou version ultérieure)
 a| 
Prend en charge les systèmes d'exploitation Linux à l'aide d'une solution de basculement multivoie Device Mapper avec un noyau 3.10 ou ultérieur.



 a| 
VMware ESXi
 a| 
Prend en charge les systèmes d'exploitation VMware ESXi exécutant l'architecture NMP (Native Multipathing Plug-in) en utilisant le module SATP_ALUA (Storage Array Policy module) intégré à VMware.



 a| 
Windows (en cluster ou non mis en cluster)
 a| 
Prend en charge les configurations Windows en cluster ou non en cluster qui n'exécutent pas le pilote de chemins d'accès multiples ATTO.



 a| 
Cluster ATTO (tous les systèmes d'exploitation)
 a| 
Prise en charge de toutes les configurations de cluster via le pilote ATTO Technology, Inc., multivoie.



 a| 
Linux (Veritas DMP)
 a| 
Prend en charge les systèmes d'exploitation Linux à l'aide d'une solution de chemins d'accès multiples DMP Veritas.



 a| 
Linux (ATTO)
 a| 
Prend en charge les systèmes d'exploitation Linux via un pilote ATTO Technology, Inc., des chemins d'accès multiples.



 a| 
Mac OS (ATTO)
 a| 
Prend en charge les versions Mac OS via un pilote ATTO Technology, Inc., des chemins d'accès multiples.



 a| 
Windows (ATTO)
 a| 
Prend en charge les systèmes d'exploitation Windows via un pilote ATTO Technology, Inc., des chemins d'accès multiples.



 a| 
FlexArray (ALUA)
 a| 
Prend en charge un système NetApp FlexArray via ALUA pour les chemins d'accès multiples.



 a| 
SERVICE IBM
 a| 
Prend en charge une configuration contrôleur de volume SAN IBM.



 a| 
Valeur par défaut
 a| 
Réservé au démarrage initial de la matrice de stockage. Si le type de système d'exploitation hôte est défini sur usine par défaut, modifiez-le pour qu'il corresponde au système d'exploitation hôte et au pilote multichemin exécuté sur l'hôte connecté.



 a| 
Linux DM-MP (Kernel 3.9 ou version antérieure)
 a| 
Prend en charge les systèmes d'exploitation Linux à l'aide d'une solution de basculement multivoie Device Mapper avec un noyau 3.9 ou antérieur.



 a| 
Fenêtre clustered (obsolète)
 a| 
Si votre type de système d'exploitation hôte est défini sur cette valeur, utilisez à la place le paramètre Windows (cluster ou non-cluster).

|===
Une fois l'HCA installé et le stockage connecté à l'hôte, l'HCA envoie la topologie hôte aux contrôleurs de stockage via le chemin d'E/S. En fonction de la topologie hôte, les contrôleurs de stockage définissent automatiquement l'hôte et les ports hôtes associés, puis définissent le type d'hôte.

[NOTE]
====
Si le HCA ne sélectionne pas le type d'hôte recommandé, vous devez définir manuellement le type d'hôte.

====