---
permalink: sm-storage/how-do-i-match-the-host-ports-to-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, match, host, ports, 
summary: 'Si vous créez manuellement un hôte, vous devez d"abord utiliser l"utilitaire HBA (Host bus adapter) approprié disponible sur l"hôte pour déterminer les identificateurs de port hôte associés à chaque HBA installé dans l"hôte.' 
---
= Comment faire correspondre les ports hôte à un hôte ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous créez manuellement un hôte, vous devez d'abord utiliser l'utilitaire HBA (Host bus adapter) approprié disponible sur l'hôte pour déterminer les identificateurs de port hôte associés à chaque HBA installé dans l'hôte.

Lorsque vous disposez de ces informations, sélectionnez les identificateurs de port hôte qui se sont connectés à la matrice de stockage dans la liste fournie dans la boîte de dialogue Créer un hôte.

[NOTE]
====
Assurez-vous de sélectionner les identificateurs de port hôte appropriés pour l'hôte que vous créez. Si vous associez des identificateurs de port hôte incorrects, vous risquez de provoquer un accès involontaire d'un autre hôte à ces données.

====
Si vous créez automatiquement des hôtes à l'aide de l'agent HCA (Host Context Agent) installé sur chaque hôte, l'HCA doit automatiquement associer les identificateurs de port hôte à chaque hôte et les configurer de manière appropriée.
