---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: 'Lors de la création d"un volume, vous sélectionnez une charge de travail pour personnaliser la configuration de la matrice de stockage d"une application spécifique.' 
---
= Comment fonctionnent les charges de travail dans le logiciel SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la création d'un volume, vous sélectionnez une charge de travail pour personnaliser la configuration de la matrice de stockage d'une application spécifique.

Un workload est un objet de stockage qui prend en charge une application. Vous pouvez définir une ou plusieurs charges de travail ou instances par application.



== Création d'une charge de travail

Vous devez spécifier manuellement quand vous souhaitez créer une charge de travail qui n'est pas associée à une application spécifique. Vous devez également spécifier manuellement la configuration du volume à l'aide de la page Ajouter des volumes.



== Vues d'applications et de workloads

Pour afficher les applications et les charges de travail, lancez SANtricity System Manager. Dans cette interface, vous pouvez afficher les informations associées à une charge de travail spécifique aux applications de deux manières différentes :

* Vous pouvez sélectionner l'onglet *Applications and workloads* dans la page Volumes pour afficher les volumes de la baie de stockage regroupés par charge de travail et par type d'application à laquelle la charge de travail est associée.
* Vous pouvez sélectionner l’onglet *Applications et charges de travail* dans la page Performances pour afficher les indicateurs de performance (latence, IOPS et Mo/s) des objets logiques. Les objets sont regroupés par application et charge de travail associée. En collectant ces données de performance à intervalles réguliers, vous pouvez établir des mesures de référence et analyser les tendances, ce qui peut vous aider lors de l’investigation des problèmes liés aux performances d’E/S.

