---
permalink: sm-storage/manual-host-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, manual, host, 
summary: 'La création d"un hôte est l"une des étapes requises pour permettre à la baie de stockage de savoir quels hôtes lui sont connectés et d"autoriser l"accès E/S aux volumes. Vous ne pouvez créer un hôte que manuellement.' 
---
= Création manuelle d'hôtes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La création d'un hôte est l'une des étapes requises pour permettre à la baie de stockage de savoir quels hôtes lui sont connectés et d'autoriser l'accès E/S aux volumes. Vous ne pouvez créer un hôte que manuellement.



== Création manuelle

La création manuelle d'hôte vous permet de vous assurer que les identificateurs de port d'hôte détectés par les contrôleurs de matrice de stockage sont correctement associés aux hôtes.

Lors de la création manuelle d'un hôte, vous associez des identificateurs de port hôte en les sélectionnant dans une liste ou en les saisissant manuellement. Une fois que vous avez créé un hôte, vous pouvez lui attribuer des volumes ou l'ajouter à un cluster hôte si vous prévoyez de partager l'accès aux volumes.
