---
permalink: sm-storage/remove-capacity-from-a-pool-or-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, capacity, pool, ssd cache 
summary: 'Vous pouvez supprimer des disques pour réduire la capacité d"un pool existant ou d"un cache SSD.' 
---
= Suppression de la capacité d'un pool ou SSD cache
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer des disques pour réduire la capacité d'un pool existant ou d'un cache SSD.

Après avoir supprimé des disques, les données de chaque volume du pool ou SSD cache sont redistribuées aux disques restants. Les disques retirés sont devenus non assignés et leur capacité devient un élément de la capacité totale disponible de la baie de stockage.

.Description de la tâche
Suivez les consignes suivantes lorsque vous retirez de la capacité :

* Vous ne pouvez pas supprimer le dernier disque d'un cache SSD sans supprimer au préalable le cache SSD.
* Vous ne pouvez pas réduire le nombre de disques dans un pool à moins de 11 disques.
* Vous pouvez supprimer un maximum de 12 lecteurs à la fois. Si vous devez retirer plus de 12 lecteurs, répétez la procédure.
* Vous ne pouvez pas supprimer les disques s'il n'y a pas suffisamment de capacité libre dans le pool ou dans SSD cache pour contenir les données, lorsque ces données sont redistribuées vers les disques restants du pool ou SSD cache.


.En savoir plus sur les impacts potentiels sur les performances
[%collapsible]
====
* La suppression des disques d'un pool ou d'un SSD cache peut entraîner une réduction des performances du volume.
* La capacité de conservation n'est pas utilisée lorsque vous supprimez la capacité d'un pool ou d'un SSD cache. Toutefois, la capacité de conservation peut diminuer en fonction du nombre de disques restants dans le pool ou dans SSD cache.


====
.En savoir plus sur les impacts sur les lecteurs sécurisés
[%collapsible]
====
* Si vous retirez le dernier lecteur qui n'est pas sécurisé, le pool est laissé avec tous les lecteurs compatibles. Dans ce cas, vous avez la possibilité d'activer la sécurité du pool.
* Si vous supprimez le dernier disque qui ne prend pas en charge Data assurance (DA), le pool est laissé avec tous les disques compatibles DA.



NOTE: Tous les nouveaux volumes que vous créez sur le pool seront compatibles DA. Si vous souhaitez que les volumes existants soient compatibles DA, vous devez les supprimer, puis recréer le volume.

====
.Étapes
. Menu Sélectionner:Storage[pools & Volume Groups].
. Sélectionnez le pool ou SSD cache, puis cliquez sur menu:More[Remove Capacity].
+
La boîte de dialogue Supprimer la capacité s'affiche.

. Sélectionnez un ou plusieurs lecteurs dans la liste.
+
Lorsque vous sélectionnez ou désélectionnez des lecteurs dans la liste, le champ capacité totale sélectionnée* est mis à jour. Ce champ indique la capacité totale du pool ou de SSD cache résultant de la suppression des disques sélectionnés.

. Cliquez sur *Supprimer*, puis confirmez que vous souhaitez supprimer les lecteurs.
+
La capacité réduite récemment du pool ou de SSD cache est reflétée dans la vue pools et groupes de volumes.


