---
permalink: sm-storage/remove-member-volumes-from-a-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, member volume, snapshot, consistency group 
summary: 'Vous pouvez supprimer un volume membre d"un groupe de cohérence Snapshot existant.' 
---
= Supprimez un volume membre d'un groupe de cohérence snapshot
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un volume membre d'un groupe de cohérence Snapshot existant.

.Description de la tâche
Lorsque vous supprimez un volume membre d'un groupe de cohérence de snapshot, System Manager supprime automatiquement les objets de snapshot associés à ce volume membre.

.Étapes
. Sélectionnez menu:stockage[snapshots].
. Cliquez sur l'onglet *groupes de cohérence Snapshot*.
. Développez le groupe de cohérence de snapshot à modifier en sélectionnant le signe plus (+) en regard de celui-ci.
. Sélectionnez le volume membre que vous souhaitez supprimer, puis cliquez sur *Supprimer*.
. Confirmez que vous souhaitez effectuer l'opération, puis cliquez sur *Supprimer*.


.Résultats
System Manager effectue les actions suivantes :

* Supprime toutes les images de snapshot et tous les volumes de snapshot associés au volume membre.
* Supprime le groupe d'instantanés associé au volume membre.
* Le volume membre n'est pas modifié ou supprimé.

