---
permalink: sm-storage/rtv-remote-storage-requirements.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, requirements 
summary: 'Avant d"utiliser la fonction de stockage à distance, consultez les exigences et restrictions suivantes.' 
---
= Configuration requise pour la fonction de stockage à distance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser la fonction de stockage à distance, consultez les exigences et restrictions suivantes.



== Protocoles pris en charge

Les protocoles suivants sont pris en charge :

* ISCSI
* IPv4


Pour obtenir des informations à jour sur la prise en charge et la configuration des systèmes E-Series, consultez le https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp"^].



== Configuration matérielle requise

La baie de stockage E-Series doit inclure les éléments suivants :

* Deux contrôleurs (mode duplex)
* Connexions iSCSI pour les deux contrôleurs E-Series afin de communiquer avec le système de stockage distant via une ou plusieurs connexions iSCSI
* SANtricity OS 11.71 ou version ultérieure
* Fonction de stockage à distance activée dans l'ID du sous-modèle (SMID)


Le système distant peut être un système de stockage E-Series ou un système d'un autre fournisseur. Il doit inclure :

* Interfaces compatibles iSCSI




== Restrictions

La fonction de stockage à distance comporte les restrictions suivantes :

* La mise en miroir doit être désactivée.
* Le volume de destination du système E-Series ne doit pas contenir de snapshots.
* Le volume de destination du système E-Series ne doit pas être mappé à un hôte avant le démarrage de l'importation.
* Le provisionnement des ressources doit être désactivé sur le volume de destination du système E-Series.
* Les mappages directs du volume de stockage distant vers un ou plusieurs hôtes ne sont pas pris en charge.
* Web Services Proxy n'est pas pris en charge.
* Les secrets CHAP iSCSI ne sont pas pris en charge.
* SMcli n'est pas pris en charge.
* Le datastore VMware n'est pas pris en charge.
* Un seul système de stockage de la paire relation/importation peut être mis à niveau à la fois lorsqu'une paire d'importation est présente.

