---
permalink: sm-storage/start-snapshot-image-rollback-for-consistency-group-member-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, snapshot, consistency, group, member, volumes 
summary: 'Vous pouvez effectuer une restauration pour modifier le contenu des volumes membres d"un groupe de cohérence de snapshot afin qu"il corresponde au contenu enregistré dans une image snapshot.' 
---
= Démarrez la restauration d'image snapshot pour les volumes membres de groupe de cohérence de snapshot
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une restauration pour modifier le contenu des volumes membres d'un groupe de cohérence de snapshot afin qu'il corresponde au contenu enregistré dans une image snapshot.

L'opération de restauration ne modifie pas le contenu des images de snapshot associées au groupe de cohérence de snapshot.

.Avant de commencer
* Une capacité réservée suffisante est disponible pour démarrer une opération de restauration.
* L'image d'instantané sélectionnée est optimale et le volume sélectionné est optimal.
* Le volume sélectionné n'a pas encore d'opération de retour arrière en cours.


.Description de la tâche
La séquence de démarrage de restauration permet de lancer la restauration sur une image instantanée d'un groupe de cohérence de snapshot tout en offrant des options permettant d'ajouter de la capacité de stockage. Vous ne pouvez pas démarrer plusieurs opérations de restauration simultanément pour un groupe de cohérence Snapshot.

[NOTE]
====
L'hôte a un accès immédiat aux nouveaux volumes transférés, mais les volumes membres existants n'autorisent plus l'accès en lecture/écriture de l'hôte après le démarrage de la restauration. Vous pouvez créer une image instantanée des volumes membres juste avant de démarrer la restauration afin de conserver les volumes de base de pré-restauration à des fins de restauration.

====
Le processus permettant de démarrer la restauration d'une image snapshot d'un groupe de cohérence de snapshot est une procédure en plusieurs étapes.



== Étape 1 : sélectionnez les membres

Vous devez sélectionner les volumes membres à retourner.

.Étapes
. Sélectionnez menu:stockage[snapshots].
. Sélectionnez l'onglet *Images snapshot*.
. Sélectionnez l'image snapshot du groupe de cohérence de snapshot, puis sélectionnez menu:Restauration[Démarrer].
+
La boîte de dialogue Démarrer la restauration s'affiche.

. Sélectionnez le ou les volumes membres.
. Cliquez sur *Suivant* et effectuez l'une des opérations suivantes :
+
** Si l'un des volumes membres sélectionnés est associé à plusieurs objets de capacité réservée qui stockent des images instantanées, la boîte de dialogue capacité de révision s'affiche. Accédez à <<Étape 2 : examiner la capacité>>.
** Si aucun des volumes membres sélectionnés n'est associé à plusieurs objets de capacité réservée qui stockent des images instantanées, la boîte de dialogue Modifier la priorité s'affiche. Accédez à <<Étape 3 : modifier la priorité>>.






== Étape 2 : examiner la capacité

Si vous avez sélectionné des volumes membres associés à plusieurs objets de capacité réservée, tels qu'un groupe de snapshots et un volume de capacité réservée, vous pouvez revoir et augmenter la capacité réservée pour le ou les volumes de retour arrière.

.Étapes
. À côté de tout volume membre ayant une capacité réservée très faible (ou zéro), cliquez sur le lien *augmenter la capacité* dans la colonne *Modifier*.
+
La boîte de dialogue augmenter la capacité réservée s'affiche.

. Utilisez la case à cocher pour régler le pourcentage de capacité, puis cliquez sur *augmenter*.
+
Si la capacité disponible n'existe pas dans le pool ou le groupe de volumes qui contient l'objet de stockage sélectionné et que la baie de stockage dispose de la capacité non affectée, vous pouvez ajouter de la capacité. Vous pouvez créer un nouveau pool ou groupe de volumes et réessayer cette opération en utilisant la nouvelle capacité disponible sur ce pool ou ce groupe de volumes.

. Cliquez sur *Suivant* et allez à <<Étape 3 : modifier la priorité>>.
+
La boîte de dialogue Modifier la priorité s'affiche.





== Étape 3 : modifier la priorité

Vous pouvez modifier la priorité de l'opération de restauration si nécessaire.

.Description de la tâche
La priorité de restauration détermine le nombre de ressources système dédiées à l'opération de restauration, aux dépens des performances du système.

.Étapes
. Utilisez le curseur pour régler la priorité de retour arrière selon les besoins.
. Confirmez que vous souhaitez effectuer cette opération, puis cliquez sur *Terminer*.


.Résultats
System Manager effectue les actions suivantes :

* Restaure les volumes membres du groupe de cohérence de snapshot avec le contenu enregistré sur l'image snapshot sélectionnée.
* Rend les volumes rédéployés immédiatement disponibles pour l'accès à l'hôte. Il n'est pas nécessaire d'attendre la fin de l'opération de restauration.


.Une fois que vous avez terminé
Sélectionnez menu:Accueil[opérations de visualisation en cours] pour afficher la progression de l'opération de retour arrière.

Si l'opération de restauration n'a pas réussi, l'opération s'interrompt. Vous pouvez reprendre l'opération interrompue et, si l'opération n'a toujours pas abouti, suivre la procédure Recovery Guru pour corriger le problème ou contacter le support technique.
