---
permalink: sm-storage/turn-on-locator-lights-in-a-pool-volume-group-or-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, lights, LEDs 
summary: 'Vous pouvez localiser les disques afin d"identifier physiquement tous les disques qui comprennent un pool, un groupe de volumes ou SSD cache sélectionné. Un voyant s"allume sur chaque lecteur du pool, du groupe de volumes ou du cache SSD sélectionné.' 
---
= Activer les voyants de localisation dans un pool, un groupe de volumes ou un cache SSD dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez localiser les disques afin d'identifier physiquement tous les disques qui comprennent un pool, un groupe de volumes ou SSD cache sélectionné. Un voyant s'allume sur chaque lecteur du pool, du groupe de volumes ou du cache SSD sélectionné.

.Étapes
. Dans le panneau de gauche, sélectionnez menu : Storage [Pools and volume groups].
. Sélectionnez le pool, le groupe de volumes ou le cache SSD que vous souhaitez localiser, puis cliquez sur le menu:ellipsis icon[Activer les voyants du localisateur].
+
Une boîte de dialogue s'affiche pour indiquer que les voyants des disques comprenant le pool sélectionné, le groupe de volumes ou le cache SSD sont activés.

. Après avoir trouvé les lecteurs, cliquez sur *Désactiver*.

