---
permalink: sm-storage/view-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, ssd cache, statistics 
summary: 'Vous pouvez afficher les statistiques du module SSD cache, telles que les lectures, les écritures, les accès au cache, le pourcentage d"allocation du cache, et le pourcentage d"utilisation du cache.' 
---
= Afficher les statistiques du cache SSD dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les statistiques du module SSD cache, telles que les lectures, les écritures, les accès au cache, le pourcentage d'allocation du cache, et le pourcentage d'utilisation du cache.

Les statistiques nominales, qui constituent un sous-ensemble des statistiques détaillées, sont affichées dans la boîte de dialogue Afficher les statistiques du cache du disque SSD. Vous ne pouvez afficher les statistiques détaillées du module SSD cache que lorsque vous exportez toutes les statistiques SSD vers un `.csv` fichier.

Pendant que vous examinez et interprétez les statistiques, gardez à l'esprit que certaines interprétations sont dérivées en examinant une combinaison de statistiques.

.Étapes
. Menu Sélectionner:Storage[pools & Volume Groups].
. Sélectionnez le cache SSD pour lequel vous souhaitez afficher les statistiques, puis cliquez sur menu:More[Afficher les statistiques du cache SSD].
+
La boîte de dialogue Afficher les statistiques de cache SSD s'affiche et affiche les statistiques nominales du cache SSD sélectionné.

+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Paramètres | Description 


 a| 
En lecture
 a| 
Affiche le nombre total de lectures d'hôte à partir des volumes SSD cache activés. Plus le rapport entre les lectures et les écritures est élevé, meilleur est le fonctionnement du cache.



 a| 
Écritures
 a| 
Nombre total d'écritures sur l'hôte pour les volumes SSD cache. Plus le rapport entre les lectures et les écritures est élevé, meilleur est le fonctionnement du cache.



 a| 
Accès au cache
 a| 
Affiche le nombre d'accès au cache.



 a| 
Taux d'accès au cache %
 a| 
Affiche le pourcentage d'accès au cache. Ce nombre est dérivé de cache Hits/(lectures + écritures). Le pourcentage de réussite dans le cache doit être supérieur à 50 % pour une opération SSD cache efficace.



 a| 
% D'allocation du cache
 a| 
Affiche le pourcentage de stockage SSD cache alloué, exprimé en pourcentage du stockage SSD cache disponible pour ce contrôleur et dérivé des octets alloués/octets disponibles.



 a| 
Taux d'utilisation du cache
 a| 
Affiche le pourcentage de stockage SSD cache contenant les données des volumes activés, exprimé en pourcentage de stockage SSD cache alloué. Ce montant représente l'utilisation ou la densité de la mémoire SSD cache. Dérivé des octets alloués/octets disponibles.



 a| 
Tout exporter
 a| 
Exporte toutes les statistiques de cache SSD vers un format CSV. Le fichier exporté contient toutes les statistiques disponibles pour la mémoire SSD cache (nominale et détaillée).

|===
====
. Cliquez sur *Annuler* pour fermer la boîte de dialogue.

