---
permalink: sm-storage/volume-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, terms 
summary: 'Découvrez comment les conditions générales de volume s"appliquent à votre baie de stockage.' 
---
= Terminologie des volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment les conditions générales de volume s'appliquent à votre baie de stockage.



== Tous types de volume

[cols="25h,~"]
|===
| Durée | Description 


 a| 
Capacité allouée
 a| 
Vous utilisez la capacité allouée pour créer des volumes et des opérations de copie de services.

La capacité allouée et les capacités indiquées sont identiques pour les volumes non fin, mais elles sont différentes pour les volumes fins. Pour un thick volume, l'espace physiquement alloué est égal à l'espace signalé à l'hôte. Pour un volume fin, la capacité indiquée correspond à la capacité signalée aux hôtes, tandis que la capacité allouée correspond à la quantité d'espace disque actuellement allouée pour l'écriture des données.



 a| 
Client supplémentaire
 a| 
Une application peut être utilisée comme un logiciel tel que SQL Server ou Exchange. Vous définissez une ou plusieurs charges de travail pour prendre en charge chaque application. Pour certaines applications, le système recommande automatiquement une configuration de volume qui optimise le stockage. Des caractéristiques telles que le type d'E/S, la taille du segment, la propriété du contrôleur et le cache de lecture et d'écriture sont incluses dans la configuration du volume.



 a| 
Puissance
 a| 
La capacité correspond à la quantité de données que vous pouvez stocker dans un volume.



 a| 
Propriété du contrôleur
 a| 
La propriété du contrôleur définit le contrôleur désigné comme étant le contrôleur propriétaire ou principal du volume. Un volume peut disposer d'un contrôleur préféré (A ou B) qui « détient » le volume. La propriété des volumes est automatiquement ajustée à l'aide de la fonction d'équilibrage automatique de la charge pour corriger tout problème d'équilibrage de la charge lors du transfert des charges de travail entre les contrôleurs. L'équilibrage de charge automatique assure un équilibrage automatique de la charge d'E/S et garantit que le trafic d'E/S entrantes depuis les hôtes est géré et équilibré de manière dynamique entre les deux contrôleurs.



 a| 
Préextraction de lecture dynamique du cache
 a| 
La fonctionnalité de lecture préalable en lecture dynamique du cache permet au contrôleur de copier des blocs de données séquentiels supplémentaires dans le cache lors de la lecture des blocs de données d'un disque sur le cache. Cette mise en cache augmente le risque que les futures demandes de données soient traitées à partir du cache. La lecture préalable en cache dynamique est importante pour les applications multimédia qui utilisent des E/S séquentielles Le taux et la quantité de données préextraites dans le cache sont auto-réglables en fonction du débit et de la taille de la demande des lectures de l'hôte. L'accès aléatoire n'entraîne pas la préextraction des données dans le cache. Cette fonction ne s'applique pas lorsque la mise en cache de lecture est désactivée.

Pour un volume fin, la préextraction de lecture dynamique du cache est toujours désactivée et ne peut pas être modifiée.



 a| 
Zone de capacité libre
 a| 
Une zone de capacité libre est la capacité disponible pouvant résulter de la suppression d'un volume ou de l'absence de toute capacité disponible lors de la création du volume. Lorsque vous créez un volume dans un groupe de volumes disposant d'une ou plusieurs zones de capacité libre, la capacité du volume est limitée à la plus grande zone de capacité libre de ce groupe de volumes. Par exemple, si un groupe de volumes dispose d'une capacité libre totale de 15 Gio et si la zone la plus large de capacité libre est de 10 Gio, le plus grand volume possible est de 10 Gio.

En consolidant la capacité disponible, vous pouvez créer des volumes supplémentaires à partir de la capacité maximale disponible dans un groupe de volumes.



 a| 
Hôte
 a| 
Un hôte est un serveur qui envoie des E/S à un volume d'une baie de stockage.



 a| 
Cluster d'hôtes
 a| 
Un cluster hôte est un groupe d'hôtes. Vous créez un cluster hôte pour vous permettre d'attribuer facilement les mêmes volumes à plusieurs hôtes.



 a| 
Disque de secours
 a| 
Les disques de secours ne sont pris en charge qu'avec des groupes de volumes. Un disque de secours ne contient aucune donnée et agit comme un disque de secours en cas de panne dans des volumes RAID 1, RAID 3, RAID 5 ou RAID 6 contenus dans un groupe de volumes. Le disque de secours ajoute un niveau supplémentaire de redondance à votre matrice de stockage.



 a| 
LUN
 a| 
Un numéro d'unité logique (LUN) est le numéro attribué à l'espace d'adresse qu'un hôte utilise pour accéder à un volume. Le volume est présenté à l'hôte comme capacité sous la forme d'une LUN.

Chaque hôte dispose de son propre espace d'adresse de LUN. Par conséquent, la même LUN peut être utilisée par différents hôtes pour accéder à différents volumes.



 a| 
Analyse des supports
 a| 
Une analyse de support permet de détecter les erreurs de support de lecteur avant qu'elles ne soient détectées lors d'une lecture normale ou d'une écriture sur les lecteurs. Une analyse des supports est effectuée en arrière-plan et analyse toutes les données et informations de redondance des volumes utilisateur définis.



 a| 
Espace de noms
 a| 
Un espace de noms est un stockage NVM formaté pour un accès au bloc. Il est similaire à une unité logique de SCSI, qui se rapporte à un volume de la baie de stockage.



 a| 
Piscine
 a| 
Un pool est un ensemble de disques regroupés de manière logique. Vous pouvez utiliser un pool pour créer un ou plusieurs volumes accessibles à un hôte. (Vous créez des volumes depuis un pool ou un groupe de volumes.)



 a| 
Capacité du pool ou du groupe de volumes
 a| 
La capacité du pool, du volume ou du groupe de volumes correspond à la capacité d'une matrice de stockage affectée à un pool ou à un groupe de volumes. Cette capacité permet de créer des volumes et de répondre aux différentes exigences de capacité des opérations de services de copie et des objets de stockage.



 a| 
Cache en lecture
 a| 
Le cache de lecture est un tampon qui stocke les données lues à partir des lecteurs. Les données d'une opération de lecture peuvent déjà se trouver dans le cache à partir d'une opération précédente, ce qui évite d'avoir à accéder aux disques. Les données restent dans le cache de lecture jusqu'à ce qu'elles soient supprimées.



 a| 
Capacité indiquée
 a| 
La capacité signalée est la capacité signalée à l'hôte et accessible par l'hôte.

Les capacités signalées et les capacités allouées sont identiques pour les volumes non volumineux, mais sont différentes pour les volumes fins. Pour un thick volume, l'espace physiquement alloué est égal à l'espace signalé à l'hôte. Pour un volume fin, la capacité indiquée correspond à la capacité signalée aux hôtes, tandis que la capacité allouée correspond à la quantité d'espace disque actuellement allouée pour l'écriture des données.



 a| 
Taille du segment
 a| 
Un segment correspond à la quantité de données en kilo-octets (Kio) stockée sur un lecteur avant que la matrice de stockage ne passe au lecteur suivant de la bande (groupe RAID). La taille du segment est égale ou inférieure à la capacité du groupe de volumes. La taille du segment est fixe et ne peut pas être modifiée pour les pools.



 a| 
Répartition
 a| 
La répartition est une méthode de stockage des données sur la baie de stockage. Les segmentations fractionne le flux de données en blocs d'une certaine taille (appelé « taille de bloc »), puis écrit ces blocs sur les disques un par un. Le stockage de données est utilisé de cette façon pour distribuer et stocker les données sur plusieurs disques physiques. La répartition est synonyme de RAID 0 et répartit les données sur tous les disques du groupe RAID sans parité.



 a| 
Volumétrie
 a| 
Un volume est un conteneur dans lequel les applications, les bases de données et les systèmes de fichiers stockent les données. Il s'agit du composant logique créé pour que l'hôte puisse accéder au stockage de la matrice de stockage.



 a| 
Affectation des volumes
 a| 
L'assignation de volumes désigne la façon dont les LUN hôtes sont attribuées à un volume.



 a| 
Nom du volume
 a| 
Un nom de volume est une chaîne de caractères affectée au volume lors de sa création. Vous pouvez accepter le nom par défaut ou fournir un nom plus descriptif indiquant le type de données stockées dans le volume.



 a| 
Groupe de volumes
 a| 
Un groupe de volumes est un conteneur pour les volumes aux caractéristiques partagées. Un groupe de volumes a une capacité et un niveau RAID définis. Vous pouvez utiliser un groupe de volumes pour créer un ou plusieurs volumes accessibles à un hôte. (Vous créez des volumes à partir d'un groupe de volumes ou d'un pool.)



 a| 
Charge de travail
 a| 
Un workload est un objet de stockage qui prend en charge une application. Vous pouvez définir une ou plusieurs charges de travail ou instances par application. Pour certaines applications, le système configure la charge de travail de manière à contenir des volumes dont les caractéristiques de volume sous-jacent sont similaires. Ces caractéristiques de volume sont optimisées en fonction du type d'application pris en charge par les workloads. Par exemple, si vous créez une charge de travail prenant en charge une application Microsoft SQL Server, puis que vous créez des volumes pour cette charge de travail, les caractéristiques du volume sous-jacent sont optimisées pour prendre en charge Microsoft SQL Server.



 a| 
Cache d'écriture
 a| 
Le cache d'écriture est un tampon qui stocke les données de l'hôte qui n'ont pas encore été écrites sur les lecteurs. Les données restent dans le cache d'écriture jusqu'à ce qu'elles soient écrites sur les disques. La mise en cache d'écriture peut augmenter les performances d'E/S.



 a| 
Mise en cache d'écriture avec mise en miroir
 a| 
La mise en cache d'écriture avec la mise en miroir se produit lorsque les données écrites dans la mémoire cache d'un contrôleur sont également écrites dans la mémoire cache de l'autre contrôleur. Par conséquent, si un contrôleur tombe en panne, l'autre peut mener à bien toutes les opérations d'écriture en attente. La mise en miroir du cache d'écriture n'est disponible que si la mise en cache d'écriture est activée et que deux contrôleurs sont présents. Lors de la création du volume, la mise en cache d'écriture avec mise en miroir est le paramètre par défaut.



 a| 
Mise en cache d'écriture sans piles
 a| 
Le paramètre de mise en cache d'écriture sans batterie permet de poursuivre la mise en cache d'écriture même si les batteries sont manquantes, défectueuses, complètement déchargées ou non complètement chargées. Il n'est généralement pas recommandé de choisir la mise en cache d'écriture sans piles car les données risquent d'être perdues en cas de coupure d'alimentation. En règle générale, la mise en cache des écritures est désactivée temporairement par le contrôleur jusqu'à ce que les batteries soient chargées ou qu'une batterie défectueuse soit remplacée.

|===


== Propre aux fins volumes

[NOTE]
====
System Manager ne propose pas d'option pour la création des volumes fins. Pour créer des volumes fins, utilisez l'interface de ligne de commande.

====
[NOTE]
====
Les volumes fins ne sont pas disponibles sur les systèmes de stockage EF600 ou EF300.

====
[cols="25h,~"]
|===
| Durée | Description 


 a| 
Limite de capacité allouée
 a| 
La limite de capacité allouée correspond au plafond de la capacité physique allouée d'un volume fin pouvant évoluer.



 a| 
Capacité écrite
 a| 
La capacité écrite correspond à la quantité de capacité écrite à partir de la capacité réservée allouée aux volumes fins.



 a| 
Seuil d'avertissement
 a| 
Vous pouvez définir une alerte de seuil d'avertissement à émettre lorsque la capacité allouée pour un volume fin atteint le pourcentage plein (seuil d'avertissement).

|===