---
permalink: sm-storage/what-is-redundancy-check.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, redundancy, check 
summary: 'Une vérification de redondance détermine si les données d"un volume d"un pool ou d"un groupe de volumes sont cohérentes. Les données redondantes sont utilisées pour reconstruire rapidement les informations sur un disque de remplacement en cas de panne de l"un des disques du pool ou du groupe de volumes.' 
---
= Qu'est-ce que le contrôle de redondance ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une vérification de redondance détermine si les données d'un volume d'un pool ou d'un groupe de volumes sont cohérentes. Les données redondantes sont utilisées pour reconstruire rapidement les informations sur un disque de remplacement en cas de panne de l'un des disques du pool ou du groupe de volumes.

Cette vérification n'est possible que sur un pool ou un groupe de volumes à la fois. Un contrôle de redondance des volumes effectue les actions suivantes :

* Analyse les blocs de données d'un volume RAID 3, d'un volume RAID 5 ou d'un volume RAID 6, puis vérifie les informations de redondance de chaque bloc. (RAID 3 ne peut être affecté qu'à des groupes de volumes à l'aide de l'interface de ligne de commande.)
* Compare les blocs de données des lecteurs RAID 1 en miroir.
* Renvoie les erreurs de redondance si les données sont jugées incohérentes par le micrologiciel du contrôleur.


[NOTE]
====
L'exécution immédiate d'une vérification de redondance sur le même pool ou groupe de volumes peut entraîner une erreur. Pour éviter ce problème, attendez une à deux minutes avant d'exécuter une autre vérification de redondance sur le même pool ou groupe de volumes.

====