---
permalink: sm-storage/what-is-the-default-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, default, cluster, 
summary: 'Le cluster par défaut est une entité définie par le système qui permet à tout identificateur de port hôte non associé connecté à la matrice de stockage d"accéder aux volumes affectés au cluster par défaut. Un identificateur de port hôte non associé est un port hôte qui n"est pas logiquement associé à un hôte donné, mais qui est physiquement installé dans un hôte et connecté à la matrice de stockage.' 
---
= À quoi correspond le cluster par défaut ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le cluster par défaut est une entité définie par le système qui permet à tout identificateur de port hôte non associé connecté à la matrice de stockage d'accéder aux volumes affectés au cluster par défaut. Un identificateur de port hôte non associé est un port hôte qui n'est pas logiquement associé à un hôte donné, mais qui est physiquement installé dans un hôte et connecté à la matrice de stockage.

[NOTE]
====
Si vous souhaitez que les hôtes disposent d'un accès spécifique à certains volumes de la baie de stockage, vous devez _pas_ utiliser le cluster par défaut. À la place, vous devez associer les identificateurs de port hôte à leurs hôtes correspondants. Cette tâche peut être effectuée manuellement pendant l'opération Créer un hôte ou automatiquement à l'aide de l'agent de contexte hôte (HCA) installé sur chaque hôte. Ensuite, vous affectez des volumes à un hôte individuel ou à un cluster hôte.

====
Vous devez _uniquement_ utiliser le cluster par défaut dans des situations spéciales où votre environnement de stockage externe est recommandé pour permettre à tous les hôtes et tous les identificateurs de port hôte connectés à la matrice de stockage ont accès à tous les volumes (mode accès total) sans spécifiquement faire connaître les hôtes à la matrice de stockage ou à l'interface utilisateur.

Initialement, vous pouvez affecter des volumes uniquement au cluster par défaut via l'interface de ligne de commande. Cependant, après avoir affecté au moins un volume au cluster par défaut, cette entité (appelée cluster par défaut) s'affiche dans l'interface utilisateur dans laquelle vous pouvez alors gérer cette entité.
