---
permalink: sm-storage/when-would-i-want-to-use-the-assign-host-later-selection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, offline, volumes, use, assign, host, 
summary: 'Pour accélérer le processus de création de volumes, vous pouvez ignorer l"étape d"affectation des hôtes afin que les nouveaux volumes soient initialisés hors ligne.' 
---
= Quand dois-je utiliser la sélection attribuer l'hôte ultérieurement ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour accélérer le processus de création de volumes, vous pouvez ignorer l'étape d'affectation des hôtes afin que les nouveaux volumes soient initialisés hors ligne.

Les volumes qui viennent d'être créés doivent être initialisés. Le système peut les initialiser en utilisant l'un des deux modes -- soit un processus d'initialisation en arrière-plan IAF (format disponible immédiat), soit un processus hors ligne.

Lorsque vous mappez un volume à un hôte, tous les volumes en cours d'initialisation de ce groupe passent à l'initialisation en arrière-plan. Ce processus d'initialisation en arrière-plan permet d'effectuer des E/S simultanées des hôtes, ce qui peut parfois prendre du temps.

Lorsqu'aucun volume d'un groupe de volumes n'est mappé, l'initialisation hors ligne est effectuée. Le processus hors ligne est bien plus rapide qu'en arrière-plan.
