---
permalink: sm-storage/why-cant-i-increase-my-preservation-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, preservation, capacity 
summary: Si vous avez créé des volumes sur toute la capacité utilisable disponible, il se peut que vous ne puissiez pas augmenter la capacité de préservation. 
---
= Pourquoi ne puis-je pas augmenter ma capacité de préservation ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez créé des volumes sur toute la capacité utilisable disponible, il se peut que vous ne puissiez pas augmenter la capacité de préservation.

La capacité de conservation correspond à la capacité (nombre de disques) réservée dans un pool afin de prendre en charge les défaillances potentielles de disque. Lorsqu'un pool est créé, le système réserve automatiquement une quantité par défaut de capacité de conservation en fonction du nombre de disques du pool. Si vous avez créé des volumes sur toute la capacité utilisable disponible, vous ne pouvez pas augmenter la capacité de préservation sans ajouter de la capacité au pool en ajoutant des disques ou en supprimant des volumes.

Vous pouvez modifier la capacité de conservation de *pools et groupes de volumes*. Sélectionnez le pool que vous souhaitez modifier. Cliquez sur *Afficher/Modifier les paramètres*, puis sélectionnez l'onglet *Paramètres*.

[NOTE]
====
La capacité de conservation est spécifiée comme un nombre de disques, même si la capacité de conservation réelle est répartie sur tous les disques du pool.

====