---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.0 
summary: Nouvelles fonctionnalités de SANtricity OS. 
---
= Nouveautés de SANtricity OS 12.0
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le tableau suivant décrit les nouvelles fonctionnalités de SANtricity System Manager 12.0.



== Nouvelles fonctionnalités dans la version 12.0


NOTE: La version 12.0 de SANtricity OS est uniquement compatible avec les nouveaux systèmes de stockage 100 % Flash EF80 et EF50. Si vous utilisez SANtricity OS 11.9 ou une version antérieure, veuillez consulter link:known-issues.html["Problèmes connus"] pour obtenir la liste des nouvelles fonctionnalités des versions précédentes.

[cols="35h,~"]
|===
| Nouvelle fonction | Description 


 a| 
Nouveaux modèles de systèmes de stockage – systèmes de stockage 100 % Flash EF80 et EF50
 a| 
Cette version introduit les systèmes de stockage EF80 et EF50 entièrement flash NVMe. Les EF80 et EF50 prennent en charge 24 disques SSD NVMe et une carte de duplication inter-contrôleur par contrôleur. Les interfaces d'hôte NVMe over Fabrics prises en charge incluent NVMe over RoCE, NVMe over IB, NVMe over FC pour EF80, et NVMe over FC pour EF50. L'interface SCSI prise en charge est Fibre Channel pour les deux systèmes. L'EF50 prend en charge jusqu'à deux cartes d'interface d'hôte par contrôleur, tandis que l'EF80 prend en charge jusqu'à trois cartes d'interface d'hôte par contrôleur.

Les disques SSD NVMe haute capacité de 30 To ou 60 To sont également pris en charge avec les EF80 et EF50. Les EF80 et EF50 ne peuvent utiliser le pool de disques dynamique que lorsque la baie est équipée de disques de 30 To ou 60 To.



 a| 
Nouvelle interface utilisateur pour SANtricity System Manager
 a| 
Pour les nouveaux contrôleurs EF80 et EF50, l'interface utilisateur de SANtricity System Manager a été repensée pour offrir une apparence et une expérience plus modernes. La nouvelle interface comprend une navigation par panneau latéral et une ergonomie améliorée pour simplifier les tâches de gestion.


NOTE: La nouvelle interface utilisateur est actuellement disponible uniquement pour les systèmes de stockage EF80 et EF50 avec la version SANtricity 12.0. Si vous utilisez SANtricity 11.9 ou une version antérieure, veuillez consulter link:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["Gestionnaire système SANtricity 11.9"] pour obtenir des instructions sur l'utilisation de l'ancienne interface utilisateur.



 a| 
Les noms alternatifs de sujet (SAN) pour le certificat de serveur n'autorisent désormais que les lettres, les chiffres et les tirets
 a| 
Lors de la création ou de la modification d'un certificat serveur dans SANtricity System Manager ou Unified Manager, le champ Subject Alternative Names (SANs) n'accepte désormais que les lettres, les chiffres et les tirets. Cette modification renforce la sécurité et garantit la compatibilité avec les normes du secteur pour les certificats SSL/TLS.



 a| 
La taille des segments des Dynamic Disk Pools est désormais fixée par défaut à 32K pour les systèmes SSD et NVMe-based.
 a| 
Pour les Dynamic Disk Pools sur les systèmes SSD et NVMe, la taille de segment par défaut a été modifiée à 32K. Auparavant, la taille de segment par défaut des Dynamic Disk Pools était fixée à 128K pour ces systèmes. Ce changement optimise les performances pour les charges de travail impliquant un mélange d'opérations d'E/S petites et grandes.



 a| 
L'éditeur de scripts est désormais disponible dans SANtricity System Manager
 a| 
Un nouvel éditeur de scripts est désormais disponible dans SANtricity System Manager. L'éditeur de scripts vous permet de créer ou de modifier un fichier de script, d'enregistrer un fichier de script sur le disque local de la station de gestion du stockage ou de charger un fichier de script depuis le disque. L'éditeur de scripts offre des fonctionnalités de vérification de la syntaxe et d'exécution de commandes pour la gestion de votre système de stockage. Pour plus d'informations, voir link:sm-support/use-script-editor.html["Utilisation de l'éditeur de script"^].

|===