---
permalink: sm-mirroring/complete-mirrored-pair-for-primary-volumes-created-on-legacy-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, complete, mirrored, pair, volumes, created, legacy, 
summary: 'Si vous avez créé un volume primaire sur une baie de stockage existante qui ne peut pas être gérée par SANtricity System Manager, vous pouvez créer le volume secondaire sur cette baie à l"aide de System Manager.' 
---
= Paire mise en miroir complète pour les volumes primaires créés sur le système existant
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez créé un volume primaire sur une baie de stockage existante qui ne peut pas être gérée par SANtricity System Manager, vous pouvez créer le volume secondaire sur cette baie avec SANtricity System Manager.

.Description de la tâche
Vous pouvez réaliser une mise en miroir asynchrone entre les baies existantes qui utilisent une interface différente et les baies plus récentes pouvant être gérées par System Manager.

* Si vous effectuez une mise en miroir entre deux matrices de stockage qui utilisent System Manager, vous pouvez ignorer cette tâche car vous avez déjà terminé la paire en miroir dans la séquence de création de paires en miroir.
* Effectuez cette tâche sur la matrice de stockage distante.


.Étapes
. Sélectionnez menu:stockage[mise en miroir asynchrone].
. Sélectionnez l'onglet *paire symétrique*.
+
Le tableau paires mises en miroir apparaît et affiche toutes les paires mises en miroir associées à la matrice de stockage.

. Recherchez le volume de paires en miroir dont l'état est incomplet, puis cliquez sur le lien *paire en miroir complète* affiché dans la colonne paire en miroir.
. Choisissez si vous souhaitez terminer la séquence de création de paires symétriques automatiquement ou manuellement en sélectionnant l'un des boutons radio suivants :
+
** *Automatique* -- Créer un nouveau volume secondaire.
+
Acceptez les paramètres par défaut du côté distant de la paire en miroir en sélectionnant un pool ou un groupe de volumes existant dans lequel vous souhaitez créer le volume secondaire. Utilisez cette option recommandée pour allouer la capacité réservée au volume secondaire avec les paramètres par défaut.

** *Manuel* -- sélectionnez un volume existant.
+
Définissez vos propres paramètres pour le volume secondaire.

+
... Cliquez sur *Suivant* pour sélectionner le volume secondaire.
... Sélectionnez un volume existant que vous souhaitez utiliser comme volume secondaire, puis cliquez sur *Suivant* pour allouer la capacité réservée.
... Allouez la capacité réservée. Effectuez l'une des opérations suivantes :
+
**** Acceptez les paramètres par défaut.
+
Le paramètre par défaut pour la capacité réservée correspond à 20 % de la capacité du volume de base et cette capacité est généralement suffisante.

**** Allouez vos propres paramètres de capacité réservés pour répondre à vos besoins en stockage de données liés à la mise en miroir asynchrone.
+
La capacité nécessaire varie, selon la fréquence et la taille des E/S écrites sur le volume primaire et le temps nécessaire pour conserver la capacité. En général, choisissez une capacité supérieure pour la capacité réservée si l'une ou les deux conditions suivantes existent :

+
***** Vous avez l'intention de conserver la paire en miroir pendant une longue période.
***** Un pourcentage élevé de blocs de données change sur le volume primaire en raison d'une forte activité d'E/S. Utilisez des données de performances historiques ou d'autres utilitaires du système d'exploitation pour déterminer les activités d'E/S types sur le volume primaire.








. Sélectionnez *Complete*.


.Résultats
System Manager effectue les actions suivantes :

* Crée le volume secondaire sur la matrice de stockage distante et alloue la capacité réservée pour le côté distant de la paire en miroir.
* Commence la synchronisation initiale entre la matrice de stockage locale et la matrice de stockage distante.
* Si le volume mis en miroir est un volume fin, seuls les blocs alloués sont transférés vers le volume secondaire au cours de la synchronisation initiale. Ce transfert réduit la quantité de données à transférer pour terminer la synchronisation initiale.
* Crée la capacité réservée pour la paire en miroir sur la matrice de stockage locale et sur la matrice de stockage distante.

