---
permalink: sm-mirroring/faq-async-mirroring.html 
sidebar: sidebar 
keywords:  
summary: Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question. 
---
= FAQ sur la mise en miroir asynchrone pour SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question.



== En quoi la mise en miroir asynchrone est-elle différente de la mise en miroir synchrone ?

La fonction de mise en miroir asynchrone diffère de la fonction de mise en miroir synchrone de façon essentielle : elle capture l'état du volume source à un moment donné et copie uniquement les données qui ont changé depuis la dernière capture d'image.

Avec la mise en miroir synchrone, l'état du volume primaire n'est pas capturé à un certain moment, mais reflète plutôt toutes les modifications apportées au volume primaire au volume secondaire. Le volume secondaire est identique au volume primaire à chaque instant car, avec ce type de miroir, chaque écriture est effectuée sur le volume primaire, une écriture est effectuée sur le volume secondaire. L'hôte ne reçoit pas de confirmation de la réussite de l'écriture tant que le volume secondaire n'a pas été mis à jour avec les modifications apportées au volume principal.

Avec la mise en miroir asynchrone, la baie de stockage distante n'est pas entièrement synchronisée avec la baie de stockage locale. Par conséquent, si l'application doit passer à la baie de stockage distante en raison d'une perte de la baie de stockage locale, certaines transactions peuvent être perdues.

Comparaison entre les fonctions de mise en miroir :

[cols="1a,1a"]
|===
| La mise en miroir asynchrone | La mise en miroir synchrone 


 a| 
*Méthode de réplication*



 a| 
* *Point dans le temps*
+
La mise en miroir s'effectue à la demande ou automatiquement selon un planning défini par l'utilisateur. Les planifications peuvent être définies au niveau de la granularité de quelques minutes. La durée minimale entre les synchronisations est de 10 minutes.


 a| 
* *Continu*
+
La mise en miroir s'exécute automatiquement en continu et copie les données à partir de chaque écriture hôte.





 a| 
*Capacité réservée*



 a| 
* *Multiple*
+
Un volume de capacité réservée est requis pour chaque paire en miroir.


 a| 
* *Unique*
+
Un seul volume de capacité réservée est requis pour tous les volumes en miroir.





 a| 
* Communication*



 a| 
* *ISCSI et Fibre Channel*
+
Prend en charge les interfaces iSCSI et Fibre Channel entre différentes baies de stockage.


 a| 
* *Fibre Channel*
+
Prend uniquement en charge les interfaces Fibre Channel entre différentes baies de stockage.





 a| 
*Distance*



 a| 
* *Illimité*
+
Prise en charge de distances pratiquement illimitées entre la matrice de stockage locale et la matrice de stockage distante, avec une distance généralement limitée uniquement par les capacités du réseau et la technologie d'extension de canal.


 a| 
* *Restreint*
+
La baie de stockage locale doit généralement se situer à environ 10 km (6.2 miles), afin de répondre aux exigences de latence et de performances applicatives.



|===


== Pourquoi ne puis-je pas accéder à la fonctionnalité de mise en miroir que j'ai choisie ?

La mise en miroir est configurée dans l'interface SANtricity Unified Manager.

[NOTE]
====
La mise en miroir synchrone n'est pas disponible sur les baies de stockage EF600/EF600C ou EF300/EF300C.

====
Pour activer et configurer la mise en miroir entre deux baies, vérifiez les points suivants :

* Le service Web Services Proxy doit être en cours d'exécution. (Unified Manager est installé sur un système hôte avec le proxy de services Web.)
* Unified Manager doit s'exécuter sur votre hôte local via une connexion HTTPS.
* Les deux baies de stockage que vous souhaitez utiliser pour la mise en miroir doivent être découvertes dans Unified Manager.
* Unified Manager doit disposer de certificats SSL valides pour les matrices de stockage. Vous pouvez accepter un certificat auto-signé ou installer des certificats avec une autorité de certification depuis Unified Manager.


Pour obtenir des instructions de configuration, reportez-vous aux sections suivantes :

* link:../um-manage/create-asynchronous-mirrored-pair-um.html["Création d'une paire asynchrone en miroir (dans Unified Manager)"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["Création d'une paire mise en miroir synchrone (dans Unified Manager)"]




== Que dois-je savoir avant de créer un groupe de cohérence miroir ?

Suivez les consignes suivantes avant de créer un groupe de cohérence en miroir.

[NOTE]
====
La mise en miroir synchrone n'est pas disponible sur les systèmes de stockage EF600/EF600C ou EF300/EF300C.

====
Vous créez un groupe de cohérence dans Unified Manager dans l'assistant de création de paires en miroir.

Voici les conditions requises pour Unified Manager :

* Le service Web Services Proxy doit être en cours d'exécution.
* Unified Manager doit s'exécuter sur votre hôte local via une connexion HTTPS.
* Unified Manager doit afficher des certificats SSL valides pour la matrice de stockage. Vous pouvez accepter un certificat auto-signé ou installer votre propre certificat de sécurité à l'aide d'Unified Manager et accéder au menu :Certificate[Certificate Management].


Assurez-vous également de répondre aux exigences suivantes pour les baies de stockage :

* Les deux baies de stockage doivent être découvertes dans Unified Manager.
* Chaque baie de stockage doit disposer de deux contrôleurs.
* Chaque contrôleur de la baie primaire et de la baie secondaire doit disposer d'un port de gestion Ethernet configuré et être connecté à votre réseau.
* Les matrices de stockage ont une version minimale du micrologiciel de 7.84. (Chacun peut exécuter différentes versions d'OS.)
* Vous devez connaître le mot de passe des matrices de stockage locales et distantes.
* Vos baies de stockage locales et distantes sont connectées via une structure Fibre Channel ou une interface iSCSI.




== Mise en miroir asynchrone : que faut-il savoir avant de créer une paire en miroir ?

Vous configurez les paires en miroir dans l'interface SANtricity Unified Manager, puis vous gérez les paires dans SANtricity System Manager.

Avant de créer une paire symétrique, suivez ces instructions.

* Vous devez disposer de deux baies de stockage.
* Chaque baie de stockage doit disposer de deux contrôleurs.
* Chaque contrôleur de la baie primaire et de la baie secondaire doit disposer d'un port de gestion Ethernet configuré et être connecté à votre réseau.
* Vos baies de stockage locales et distantes sont connectées via une structure Fibre Channel ou une interface iSCSI.
* Les matrices de stockage ont une version minimale du micrologiciel de 7.84. (Chacun peut exécuter différentes versions d'OS.)
* Vous devez connaître le mot de passe des matrices de stockage locales et distantes.
* Vous devez disposer d'une capacité disponible suffisante sur la matrice de stockage distante pour créer un volume secondaire égal ou supérieur au volume principal que vous souhaitez mettre en miroir.
* Vous avez installé Web Services Proxy et Unified Manager. Les paires en miroir sont configurées dans l'interface Unified Manager.
* Les deux baies de stockage sont découvertes dans Unified Manager.
* Votre matrice de stockage doit contenir au moins un groupe de cohérence miroir. Vous créez un groupe de cohérence dans Unified Manager dans l'assistant de création de paires en miroir.




== Que dois-je savoir avant d'augmenter la capacité réservée sur un volume en miroir ?

En règle générale, vous devez augmenter la capacité réservée lorsque vous recevez un avertissement indiquant que la capacité réservée d'une paire en miroir est saturée. Vous pouvez augmenter la capacité réservée par incréments de 8 Gio.

Pour les opérations de mise en miroir asynchrone, la capacité réservée est généralement de 20 % du volume de base. Choisissez une capacité supérieure pour la capacité réservée si l'une ou les deux conditions suivantes existent :

* Vous avez l'intention de conserver la paire en miroir pendant une longue période.
* Un pourcentage élevé de blocs de données change sur le volume primaire en raison d'une forte activité d'E/S. Utilisez des données de performances historiques ou d'autres utilitaires du système d'exploitation pour déterminer les activités d'E/S types sur le volume primaire.


Vous pouvez augmenter la capacité réservée pour une paire en miroir en effectuant l'une des actions suivantes :

* Réglez le pourcentage de capacité d'un volume de paire en miroir en sélectionnant menu:Storage[pools and volumes Groups], puis en cliquant sur l'onglet *Reserved Capacity*.
* Créez un nouveau volume en utilisant la capacité disponible dans un pool ou un groupe de volumes.
+
Si aucune capacité disponible n'existe sur un pool ou un groupe de volumes, vous pouvez ajouter de la capacité non configurée sous la forme de disques inutilisés à un pool ou à un groupe de volumes.





== Pourquoi ne puis-je pas augmenter la capacité réservée avec le montant demandé ?

Vous pouvez augmenter la capacité réservée par incréments de 4 Gio.

Consultez les directives suivantes :

* Vous devez disposer d'une capacité disponible suffisante dans le pool ou le groupe de volumes pour pouvoir l'étendre si nécessaire.
+
Si aucune capacité disponible n'est disponible dans un pool ou un groupe de volumes, vous pouvez ajouter de la capacité non affectée sous la forme de disques inutilisés dans un pool ou un groupe de volumes.

* Le volume du pool ou du groupe de volumes doit avoir un état optimal et ne doit pas être dans un état de modification.
* La capacité disponible doit exister dans le pool ou le groupe de volumes que vous souhaitez utiliser pour augmenter la capacité.


Pour les opérations de mise en miroir asynchrone, la capacité réservée est généralement de 20 % du volume de base. Utilisez un pourcentage plus élevé si vous pensez que le volume de base sera soumis à de nombreuses modifications ou si l'espérance de vie estimée du service de copie d'un objet de stockage sera très longue.



== Pourquoi changer ce pourcentage ?

La capacité réservée est généralement de 40 % du volume de base pour les opérations Snapshot et de 20 % du volume de base pour les opérations de mise en miroir asynchrone.

En général, cette capacité est suffisante. La capacité nécessaire varie, selon la fréquence et la taille des écritures d'E/S sur le volume de base et le temps d'utilisation du service de copie de l'objet de stockage.

En général, choisissez un pourcentage plus élevé pour la capacité réservée si l'une ou les deux conditions suivantes existent :

* Si la durée de vie d'une opération de service de copie d'un objet de stockage spécifique sera très longue.
* Si un pourcentage élevé de blocs de données change sur le volume de base en raison d'une forte activité d'E/S. Utilisez l'historique des performances ou d'autres utilitaires du système d'exploitation pour déterminer les activités d'E/S types sur le volume de base.




== Pourquoi vois-je plusieurs candidats à la capacité réservée ?

Si plusieurs volumes sont présents dans un pool ou un groupe de volumes qui correspond au pourcentage de capacité sélectionné pour l'objet de stockage, plusieurs candidats s'affichent.

Vous pouvez actualiser la liste des candidats recommandés en modifiant le pourcentage d'espace disque physique que vous souhaitez réserver sur le volume de base pour les opérations de service de copie. Les meilleurs candidats s'affichent en fonction de votre sélection.



== Pourquoi les valeurs non disponibles sont-elles affichées dans le tableau ?

Le tableau répertorie les valeurs non disponibles lorsque les données situées sur la matrice de stockage distante ne sont pas disponibles pour être affichées.

Pour afficher les données de la baie de stockage distante, lancez System Manager depuis Unified Manager.



== Pourquoi ne vois-je pas tous mes pools et groupes de volumes ?

Lorsque vous créez un volume secondaire pour la paire asynchrone en miroir, le système affiche la liste de tous les pools et groupes de volumes éligibles pour cette paire asynchrone en miroir. Tout pool ou groupe de volumes non éligible à l'utilisation ne s'affiche pas dans cette liste.

Les pools ou groupes de volumes ne peuvent être admissibles pour aucune des raisons suivantes.

* Les capacités de sécurité d'un pool ou d'un groupe de volumes ne correspondent pas.
* Un pool ou un groupe de volumes est dans un état non optimal.
* La capacité d'un pool ou d'un groupe de volumes est trop faible.




== Mise en miroir asynchrone - Pourquoi ne vois-je pas tous mes volumes ?

Lorsque vous sélectionnez un volume primaire pour une paire en miroir, une liste affiche tous les volumes éligibles.

Les volumes qui ne peuvent pas être utilisés ne s'affichent pas dans cette liste. Les volumes ne peuvent être admissibles pour aucune des raisons suivantes :

* Le volume n'est pas optimal.
* Le volume participe déjà à une relation de mise en miroir.
* Pour les volumes fins, l'extension automatique doit être activée.



NOTE: Pour les contrôleurs EF600 et EF300, les volumes principal et secondaire d'une paire en miroir asynchrone doivent correspondre au même protocole, au même niveau de tiroir, à la même taille de segment, au même type de sécurité et au même niveau RAID. Les paires en miroir asynchrones non éligibles n'apparaîtront pas dans la liste des volumes disponibles.



== Mise en miroir asynchrone - Pourquoi ne vois-je pas tous les volumes sur la baie de stockage distante ?

Lorsque vous sélectionnez un volume secondaire sur la matrice de stockage distante, une liste affiche tous les volumes éligibles pour cette paire en miroir.

Les volumes qui ne peuvent pas être utilisés ne s'affichent pas dans cette liste. Les volumes peuvent ne pas être éligibles pour les raisons suivantes :

* Le volume n'est pas optimal.
* Le volume participe déjà à une relation de mise en miroir.
* Les attributs du volume fin entre le volume primaire et le volume secondaire ne correspondent pas.
* Si vous utilisez Data assurance (DA), le volume primaire et le volume secondaire doivent avoir les mêmes paramètres DA.
+
** Si le volume principal est DA activé, le volume secondaire doit être DA activé.
** Si le volume principal n'est pas activé par DA, le volume secondaire ne doit pas être activé par DA.






== Pourquoi devrais-je mettre à jour l’adresse IP de ma baie de stockage distante ?

Vous mettez à jour l'adresse IP de votre matrice de stockage distante lorsque l'adresse IP d'un port iSCSI change et que la matrice de stockage locale ne parvient pas à communiquer avec la matrice de stockage distante.

Lors de l'établissement d'une relation de mise en miroir asynchrone avec une connexion iSCSI, les matrices de stockage locales et distantes stockent un enregistrement de l'adresse IP de la matrice de stockage distante dans la configuration de mise en miroir asynchrone. Si l'adresse IP d'un port iSCSI change, la matrice de stockage distante qui tente d'utiliser ce port rencontre une erreur de communication.

La matrice de stockage avec l'adresse IP modifiée envoie un message à chaque matrice de stockage distante associée aux groupes de cohérence miroir configurés pour effectuer une mise en miroir sur une connexion iSCSI. Les matrices de stockage qui reçoivent ce message mettent automatiquement à jour leur adresse IP cible distante.

Si la matrice de stockage avec l'adresse IP modifiée ne parvient pas à envoyer son message inter-matrice à une matrice de stockage distante, le système vous envoie une alerte du problème de connectivité. Utilisez l'option mettre à jour l'adresse IP distante pour rétablir la connexion avec la matrice de stockage locale.
