---
permalink: sm-mirroring/overview-mirroring-async.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ARVM, asynchronous, mirroring, firmware, 
summary: La fonction de mise en miroir asynchrone fournit un mécanisme basé sur le firmware au niveau du contrôleur pour la réplication des données entre une baie de stockage locale et une baie de stockage distante. 
---
= Présentation de la mise en miroir asynchrone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La fonction de mise en miroir asynchrone fournit un mécanisme basé sur le firmware au niveau du contrôleur pour la réplication des données entre une baie de stockage locale et une baie de stockage distante.

[NOTE]
====
Cette fonctionnalité n'est pas disponible sur les systèmes de stockage EF600 ou EF300.

====


== Qu'est-ce que la mise en miroir asynchrone ?

_Asynchronous Mirroring_ capture l'état du volume primaire à un moment donné et copie uniquement les données qui ont changé depuis la dernière capture d'image. Le site primaire peut être mis à jour immédiatement et le site secondaire peut être mis à jour à mesure que la bande passante le permet. Les informations sont mises en cache et envoyées ultérieurement, au fur et à mesure que les ressources réseau deviennent disponibles.

La mise en miroir asynchrone est créée par volume, mais gérée au niveau d'un groupe. Vous pouvez ainsi associer un volume mis en miroir distant distinct à n'importe quel volume primaire sur une baie de stockage donnée. Ce type de mise en miroir est idéal pour répondre à la demande d'opérations continues et, en général, est beaucoup plus efficace sur le réseau pour les processus périodiques.

En savoir plus :

* link:how-asynchronous-mirroring-works.html["Fonctionnement de la mise en miroir asynchrone"]
* link:asynchronous-terminology.html["Terminologie de la mise en miroir asynchrone"]
* link:asynchronous-mirror-status.html["État de la mise en miroir asynchrone"]
* link:volume-ownership-sync.html["Propriété de volume"]
* link:role-change-of-a-mirror-consistency-group.html["Changement de rôle d'un groupe de cohérence miroir"]




== Comment configurer la mise en miroir asynchrone ?

Vous devez utiliser l'interface Unified Manager pour effectuer la configuration initiale de mise en miroir entre les baies. Une fois configuré, vous pouvez gérer les paires et les groupes de cohérence en miroir dans System Manager.

En savoir plus :

* link:requirements-for-using-asynchronous-mirroring.html["Requise pour l'utilisation de la mise en miroir asynchrone"]
* link:workflow-for-mirroring-a-volume-asynchronously.html["Workflow de mise en miroir asynchrone d'un volume"]
* link:../um-manage/create-asynchronous-mirrored-pair-um.html["Création d'une paire asynchrone en miroir (dans Unified Manager)"]




== Informations associées

En savoir plus sur les concepts liés à la mise en miroir asynchrone :

* link:what-do-i-need-to-know-before-creating-a-mirror-consistency-group.html["Ce que vous devez savoir avant de créer un groupe de cohérence en miroir"]
* link:asynchronous-mirroring-what-do-i-need-to-know-before-creating-a-mirrored-pair.html["Ce que vous devez savoir avant de créer une paire en miroir"]
* link:how-does-asynchronous-mirroring-differ-from-synchronous-mirroring-async.html["La différence entre la mise en miroir asynchrone et la mise en miroir synchrone"]

