---
permalink: sm-mirroring/re-synchronize-mirror-consistency-group-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, re-synchronize, mirror, consistency, group, manually, 
summary: Vous pouvez démarrer manuellement la resynchronisation pour toutes les paires mises en miroir dans un groupe de cohérence miroir. 
---
= Synchronisez à nouveau le groupe de cohérence miroir manuellement
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez démarrer manuellement la resynchronisation pour toutes les paires mises en miroir dans un groupe de cohérence miroir.

.Étapes
. Sélectionnez menu:stockage[mise en miroir asynchrone].
. Sélectionnez l'onglet *groupes de cohérence miroir*.
+
Le tableau Groupe de cohérence miroir s'affiche et affiche tous les groupes de cohérence miroir associés à la matrice de stockage.

. Sélectionnez le groupe de cohérence miroir que vous souhaitez resynchroniser, puis sélectionnez menu:plus[resynchroniser manuellement].
+
Le système affiche une confirmation.

. Sélectionnez *Oui* pour confirmer.


.Résultats
Le système effectue les opérations suivantes :

* Lance la resynchronisation des données sur toutes les paires symétriques au sein du groupe de cohérence miroir sélectionné.
* Met à jour les données modifiées de la matrice de stockage locale vers la matrice de stockage distante.

