---
permalink: sm-mirroring/remove-synchronous-mirror-relationship.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, synchronous, mirror, relationship, 
summary: Vous supprimez une paire en miroir pour supprimer la relation de miroir du volume primaire sur la matrice de stockage locale et du volume secondaire sur la matrice de stockage distante. 
---
= Supprimer la relation de miroir synchrone
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous supprimez une paire en miroir pour supprimer la relation de miroir du volume primaire sur la matrice de stockage locale et du volume secondaire sur la matrice de stockage distante.

.Description de la tâche
Vous pouvez également supprimer une paire en miroir pour corriger un état de paire en miroir orphelin. Consultez les informations suivantes sur les paires en miroir orphelines :

* Une paire mise en miroir orpheline existe lorsqu'un volume membre a été supprimé d'un côté (local/distant) mais pas de l'autre.
* Des paires mises en miroir orphelines sont détectées lors de la restauration de la communication inter-baies.


.Étapes
. Menu sélection:stockage[mise en miroir synchrone].
. Sélectionnez la paire symétrique que vous souhaitez supprimer, puis sélectionnez le menu:tâches rares[Supprimer].
+
La boîte de dialogue Supprimer la relation de symétrie s'affiche.

. Confirmez que vous souhaitez supprimer la paire symétrique, puis cliquez sur *Supprimer*.


.Résultats
System Manager effectue les actions suivantes :

* Supprime la relation de miroir de la paire en miroir sur la matrice de stockage locale et sur la matrice de stockage distante.
* Renvoie le volume primaire et le volume secondaire aux volumes non mis en miroir accessibles par l'hôte.
* Met à jour la mosaïque mise en miroir synchrone avec la suppression de la paire mise en miroir synchrone.

