---
permalink: sm-mirroring/remove-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, asynchronous, mirror, relationship, 
summary: Vous supprimez une paire en miroir pour supprimer la relation de miroir du volume primaire sur la matrice de stockage locale et du volume secondaire sur la matrice de stockage distante. 
---
= Supprimer la relation de miroir asynchrone
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous supprimez une paire en miroir pour supprimer la relation de miroir du volume primaire sur la matrice de stockage locale et du volume secondaire sur la matrice de stockage distante.

.Description de la tâche
Consultez les informations suivantes sur les paires en miroir orphelines :

* Une paire mise en miroir orpheline existe lorsqu'un volume membre d'un groupe de miroirs de cohérence a été supprimé d'un côté (côté de la baie de stockage locale ou côté de la baie de stockage distante), mais pas de l'autre.
* Des paires mises en miroir orphelines sont détectées lorsque la communication inter-array est restaurée et que les deux côtés de la configuration miroir concilient les paramètres de miroir.
* Vous pouvez supprimer une paire en miroir pour corriger un état de paire en miroir orphelin.


.Étapes
. Sélectionnez menu:stockage[mise en miroir asynchrone].
. Sélectionnez l'onglet *paire symétrique*.
+
Le tableau paires mises en miroir apparaît et affiche toutes les paires mises en miroir associées à la matrice de stockage.

. Sélectionnez la paire symétrique que vous souhaitez supprimer, puis cliquez sur *Supprimer*.
. Confirmez que vous souhaitez supprimer la paire symétrique, puis cliquez sur *Supprimer*.


.Résultats
System Manager effectue les actions suivantes :

* Supprime la relation miroir du groupe de cohérence miroir sur la matrice de stockage locale et sur la matrice de stockage distante, et supprime la capacité réservée.
* Renvoie le volume primaire et le volume secondaire aux volumes non mis en miroir accessibles par l'hôte.
* Met à jour la mosaïque mise en miroir asynchrone avec la suppression de la paire mise en miroir asynchrone.

