---
permalink: sm-mirroring/suspend-or-resume-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, suspend, resume, synchronization, mirror, consistency, group, 
summary: 'Vous pouvez interrompre ou reprendre la synchronisation des données sur toutes les paires mises en miroir d"un groupe de cohérence miroir, ce qui est plus efficace que la suspension ou la reprise de la synchronisation sur des paires mises en miroir individuelles.' 
---
= Suspendre ou reprendre la synchronisation pour le groupe de cohérence miroir
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez interrompre ou reprendre la synchronisation des données sur toutes les paires mises en miroir d'un groupe de cohérence miroir, ce qui est plus efficace que la suspension ou la reprise de la synchronisation sur des paires mises en miroir individuelles.

.Description de la tâche
La suspension et la reprise de la synchronisation sur les groupes permettent de réduire tout impact sur les performances de l'application hôte, ce qui peut se produire lorsque toutes les données modifiées de la baie de stockage locale sont copiées sur la baie de stockage distante.

L'état du groupe de cohérence miroir et de ses paires symétriques restent suspendus jusqu'à ce que vous utilisiez l'option reprendre pour reprendre l'activité de synchronisation.

.Étapes
. Sélectionnez menu:stockage[mise en miroir asynchrone].
. Sélectionnez l'onglet *groupes de cohérence miroir*.
+
Le tableau Groupe de cohérence en miroir s'affiche et affiche tous les groupes de cohérence en miroir associés à la matrice de stockage.

. Sélectionnez le groupe de cohérence miroir que vous souhaitez suspendre ou reprendre, puis sélectionnez menu :plus[Suspend] ou menu:plus[reprendre].
+
Le système affiche une confirmation.

. Sélectionnez *Oui* pour confirmer.


.Résultats
System Manager effectue les actions suivantes :

* Suspend ou reprend le transfert de données entre toutes les paires symétriques d'un groupe de cohérence miroir sans supprimer la relation miroir.
* Consigne toutes les données écrites sur le côté primaire du groupe de cohérence miroir alors que le groupe miroir est suspendu et écrit automatiquement les données sur le côté secondaire du groupe de cohérence miroir lorsque le groupe miroir reprend. Aucune synchronisation complète n'est requise.
* Pour un groupe de cohérence _suspendu_ miroir, affiche *utilisateur-suspendu* dans le tableau groupes de cohérence miroir.
* Pour un groupe de cohérence _repris_ miroir, les données écrites sur les volumes primaires pendant que le groupe de cohérence miroir a été suspendu sont immédiatement écrites sur les volumes secondaires. La synchronisation périodique reprend si un intervalle de synchronisation automatique a été défini.

