---
permalink: sm-mirroring/why-cant-i-increase-reserved-capacity-with-my-requested-amount.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, reserved, capacity, 
summary: Vous pouvez augmenter la capacité réservée par incréments de 4 Gio. 
---
= Pourquoi ne puis-je pas augmenter la capacité réservée avec le montant demandé ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez augmenter la capacité réservée par incréments de 4 Gio.

Consultez les directives suivantes :

* Vous devez disposer d'une capacité disponible suffisante dans le pool ou le groupe de volumes pour pouvoir l'étendre si nécessaire.
+
Si aucune capacité disponible n'est disponible dans un pool ou un groupe de volumes, vous pouvez ajouter de la capacité non affectée sous la forme de disques inutilisés dans un pool ou un groupe de volumes.

* Le volume du pool ou du groupe de volumes doit avoir un état optimal et ne doit pas être dans un état de modification.
* La capacité disponible doit exister dans le pool ou le groupe de volumes que vous souhaitez utiliser pour augmenter la capacité.


Pour les opérations de mise en miroir asynchrone, la capacité réservée est généralement de 20 % du volume de base. Utilisez un pourcentage plus élevé si vous pensez que le volume de base sera soumis à de nombreuses modifications ou si l'espérance de vie estimée du service de copie d'un objet de stockage sera très longue.
