---
permalink: sm-mirroring/workflow-for-mirroring-a-volume-synchronously.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workflow, mirroring, synchronously, 
summary: 'Vous configurez la mise en miroir synchrone à l"aide du workflow suivant.' 
---
= Workflow de mise en miroir d'un volume de manière synchrone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous configurez la mise en miroir synchrone à l'aide du workflow suivant.

[NOTE]
====
Cette fonctionnalité n'est pas disponible sur les systèmes de stockage EF600 ou EF300.

====
. Effectuer la configuration initiale dans Unified Manager :
+
.. Sélectionnez une matrice de stockage locale comme source pour le transfert de données.
.. Sélectionnez un volume primaire dans la matrice de stockage locale.
.. Sélectionnez une matrice de stockage distante comme destination pour le transfert de données, puis sélectionnez un volume secondaire.
.. Sélectionnez les priorités de synchronisation et de resynchronisation.
.. Démarrer le transfert de données initial du volume primaire vers le volume secondaire. Selon la taille du volume, ce transfert initial peut prendre plusieurs heures.


. Vérifier la progression de la synchronisation initiale :
+
.. Dans Unified Manager, lancez System Manager pour la baie locale.
.. Dans System Manager, afficher l'état de l'opération de mise en miroir. Une fois la mise en miroir terminée, l'état de la paire en miroir est « optimal ». Les deux matrices tentent de rester synchronisées pendant les opérations normales. Seuls les nouveaux blocs et les blocs modifiés sont transférés du volume primaire vers le volume secondaire.


. *Facultatif:* vous pouvez modifier les paramètres de synchronisation dans System Manager.
+
[NOTE]
====
Étant donné que la réplication synchrone est continue, la liaison de réplication entre les deux sites doit fournir suffisamment de capacités de bande passante.

====

