---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: Vous devez configurer la matrice de stockage avec un mot de passe administrateur pour la protéger contre les accès non autorisés. 
---
= Gérer la protection par mot de passe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer la matrice de stockage avec des mots de passe pour la protéger contre les accès non autorisés.



== Définir et modifier les mots de passe

Lorsque vous démarrez System Manager pour la première fois, vous êtes invité à définir un mot de passe administrateur. Tout utilisateur disposant du mot de passe administrateur peut modifier la configuration de la matrice de stockage, par exemple ajouter, modifier ou supprimer des objets ou des paramètres. Pour définir le mot de passe administrateur au démarrage initial, reportez-vous à la section link:../san-getstarted/access-sam.html["Accédez à System Manager"].

Pour des raisons de sécurité, vous ne pouvez tenter de saisir un mot de passe que cinq fois avant que la matrice de stockage ne passe à l'état « verrouillage ». Dans cet état, la matrice de stockage rejette les tentatives de mot de passe suivantes. Vous devez attendre 10 minutes que la matrice de stockage se réinitialise à l'état « normal » avant d'essayer à nouveau d'entrer un mot de passe.

Outre le mot de passe administrateur, la matrice de stockage inclut des profils utilisateur prédéfinis avec un ou plusieurs rôles qui leur sont associés. Pour plus d'informations, voir link:../sm-settings/permissions-for-mapped-roles.html["Autorisations pour les rôles mappés"]. Les profils utilisateur et les mappages ne peuvent pas être modifiés. Seuls les mots de passe peuvent être modifiés. Si vous souhaitez modifier le mot de passe administrateur ou d'autres mots de passe utilisateur, reportez-vous à la section link:../sm-settings/change-passwords.html["Modifier les mots de passe"].



== Saisissez à nouveau les mots de passe après l'expiration de la session

Le système vous demande le mot de passe une seule fois lors d'une seule session de gestion. Toutefois, une session s'est terminée au bout de 30 minutes d'inactivité. Vous devez alors saisir à nouveau le mot de passe. Si un autre utilisateur gérant la même matrice de stockage à partir d'un autre client de gestion modifie le mot de passe pendant que votre session est en cours, vous êtes invité à saisir un mot de passe lors de la prochaine tentative d'opération de configuration ou d'affichage.

Vous pouvez régler le délai de session ou désactiver complètement les délais de session. Voir link:../sm-settings/manage-session-timeouts-sam.html["Gérer les délais d'expiration des sessions"].



== Suppression des disques ou protection par mot de passe

Si vous supprimez des lecteurs protégés par mot de passe ou si vous souhaitez désactiver la protection par mot de passe, sachez que :

* *Si vous supprimez des lecteurs avec protection par mot de passe* -- le mot de passe est stocké dans une zone réservée de chaque lecteur de la matrice de stockage. Si vous supprimez tous les disques d'une matrice de stockage, son mot de passe ne fonctionnera plus. Pour corriger ce problème, réinstallez l'un des disques d'origine sur la matrice de stockage.
* *Si vous souhaitez supprimer la protection par mot de passe* -- si vous ne souhaitez plus que les commandes soient protégées par mot de passe, entrez le mot de passe administrateur actuel et laissez les zones de texte du nouveau mot de passe vides.


[CAUTION]
====
L'exécution de commandes de configuration sur une matrice de stockage peut causer des dommages graves, y compris la perte de données. C'est pourquoi vous devez toujours définir un mot de passe administrateur pour votre matrice de stockage. Pour renforcer la sécurité, utilisez un mot de passe administrateur long comportant au moins 15 caractères alphanumériques.

====