---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: 'Vous naviguez dans l"interface principale pour accéder aux fonctionnalités et aux tâches de System Manager.' 
---
= En savoir plus sur l'interface SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager est une interface web qui vous permet de gérer une baie de stockage dans une vue unique.



== Page d'accueil

La page d'accueil offre un tableau de bord pour la gestion quotidienne de votre matrice de stockage. Lorsque vous vous connectez à System Manager, la page d'accueil est le premier écran affiché.

La vue du tableau de bord comprend trois zones récapitulatives qui contiennent des informations clés sur l'état et la santé de votre baie de stockage. Vous pouvez trouver plus d'informations dans la zone récapitulative.

[cols="25h,~"]
|===
| De service | Description 


 a| 
Performance
 a| 
La zone Performance vous permet de comparer et de comparer l'utilisation des ressources au fil du temps. Vous pouvez afficher les metrics de performances d'une baie de stockage pour le temps de réponse (IOPS), les taux de transfert (MIB/s) et la capacité de traitement utilisée (CPU).



 a| 
Puissance
 a| 
La zone capacité affiche un graphique indiquant la capacité allouée, la capacité de stockage disponible et la capacité de stockage non affectée dans votre baie de stockage.



 a| 
Hiérarchie du stockage
 a| 
La zone hiérarchie de stockage fournit une vue organisée des divers composants matériels et objets de stockage gérés par votre matrice de stockage. Cliquez sur la flèche de la liste déroulante pour effectuer une certaine action sur ce composant matériel ou objet de stockage.

|===


== Zone de notifications

La zone de notifications est accessible via l'icône de cloche située dans le coin supérieur de la fenêtre. La zone de notifications affiche les notifications de problème indiquant l'état de la baie de stockage et de ses composants. De plus, cette section affiche des alertes automatiques pouvant vous aider à résoudre les problèmes avant qu'ils n'affectent d'autres zones de votre environnement de stockage.



== Paramètres d'interface

Vous pouvez modifier les préférences d'affichage et d'autres paramètres à partir de l'interface principale.



== Identifiants de connexion et mots de passe des utilisateurs

L'utilisateur actuellement connecté au système est affiché dans les paramètres utilisateur.

Pour plus d'informations sur les utilisateurs et les mots de passe, voir :

* link:administrator-password-protection.html["Définissez la protection par mot de passe de l'administrateur"]
* link:../sm-settings/change-passwords.html["Modifier les mots de passe"]

