---
permalink: sm-hardware/initialize-format-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, initialize, format, drive, 
summary: 'Si vous déplacez les lecteurs affectés d"une matrice de stockage à une autre, vous devez initialiser (formater) les lecteurs avant de pouvoir les utiliser dans la nouvelle matrice de stockage.' 
---
= Initialiser (formater) le lecteur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous déplacez les lecteurs affectés d'une matrice de stockage à une autre, vous devez initialiser (formater) les lecteurs avant de pouvoir les utiliser dans la nouvelle matrice de stockage.

.Description de la tâche
L'initialisation supprime les informations de configuration précédentes d'un lecteur et les renvoie à l'état non affecté. Le lecteur peut alors être ajouté à un nouveau pool ou groupe de volumes dans la nouvelle matrice de stockage.

Utilisez l'opération d'initialisation de l'entraînement lorsque vous déplacez un seul lecteur. Il n'est pas nécessaire d'initialiser les lecteurs si vous déplacez un groupe de volumes entier d'une matrice de stockage à une autre.

[CAUTION]
====
*Perte possible de données* -- lorsque vous initialisez un lecteur, toutes les données du lecteur sont perdues. Effectuez cette opération uniquement lorsque le support technique vous y invite.

====
.Étapes
. Sélectionnez *matériel*.
. Si le graphique montre les contrôleurs, cliquez sur *Afficher le recto du tiroir*.
+
Le graphique change pour afficher les disques au lieu des contrôleurs.

. Cliquez sur le lecteur à initialiser.
+
Le menu contextuel du lecteur s'affiche.

. Sélectionnez *Initialize* et confirmez que vous souhaitez effectuer l'opération.

