---
permalink: sm-hardware/place-controller-online.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, place, controller, online 
summary: Si un contrôleur est en mode hors ligne ou de service, vous pouvez le remettre en ligne. 
---
= Mettez le contrôleur en ligne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si un contrôleur est en mode hors ligne ou de service, vous pouvez le remettre en ligne.

.Étapes
. Sélectionnez *matériel*.
. Si le graphique montre les lecteurs, cliquez sur *Afficher le verso du tiroir*.
+
Le graphique change pour afficher les contrôleurs au lieu des disques.

. Cliquez sur un contrôleur en mode hors ligne ou de service.
+
Le menu contextuel du contrôleur s'affiche.

. Sélectionnez *placer en ligne* et confirmez que vous souhaitez effectuer l'opération.


.Résultats
La détection d'un chemin préféré restauré par le pilote multivoie peut prendre jusqu'à 10 minutes.

Tous les volumes possédés à l'origine par ce contrôleur sont automatiquement redéplacés vers le contrôleur au fur et à mesure que des demandes d'E/S sont reçues pour chaque volume. Dans certains cas, vous devrez peut-être redistribuer manuellement les volumes à l'aide de la commande *rerépartir les volumes*.
