---
permalink: sm-hardware/place-controller-offline.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, place, controller, offline, 
summary: Si vous y êtes invité, vous pouvez mettre un contrôleur hors ligne. 
---
= Mettez le contrôleur hors ligne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous y êtes invité, vous pouvez mettre un contrôleur hors ligne.

.Avant de commencer
* Votre baie de stockage doit disposer de deux contrôleurs. Le contrôleur que vous ne mettez pas hors ligne doit être en ligne (dans l'état optimal).
* Assurez-vous qu'aucun volume n'est en cours d'utilisation ou que vous avez installé un pilote multivoie sur tous les hôtes qui utilisent ces volumes.


.Description de la tâche
++ ++

[CAUTION]
====
Ne mettez pas un contrôleur hors ligne à moins d'en recevoir l'instruction du gourou de la restauration ou du support technique.

====
.Étapes
. Sélectionnez *matériel*.
. Si le graphique montre les lecteurs, cliquez sur *Afficher le verso du tiroir*.
+
Le graphique change pour afficher les contrôleurs au lieu des disques.

. Cliquez sur le contrôleur que vous souhaitez placer hors ligne.
+
Le menu contextuel du contrôleur s'affiche.

. Sélectionnez *mettre hors ligne* et confirmez que vous souhaitez effectuer l'opération.


.Résultats
System Manager peut prendre plusieurs minutes pour mettre à jour l'état du contrôleur hors ligne. Ne pas commencer d'autres opérations tant que le statut n'a pas été mis à jour.
