---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, reset, locked, fips, nvme, drives, 
summary: 'Si vous insérez un ou plusieurs disques NVMe ou FIPS verrouillés dans une matrice de stockage, vous pouvez déverrouiller les données du disque en ajoutant le fichier de clé de sécurité associé aux disques. Si vous n"avez pas de clé de sécurité, vous pouvez réinitialiser chaque disque verrouillé en saisissant son ID de sécurité physique (PSID) pour réinitialiser ses attributs de sécurité et effacer les données du lecteur.' 
---
= Déverrouillez ou réinitialisez les disques NVMe ou FIPS verrouillés
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous insérez un ou plusieurs disques NVMe ou FIPS verrouillés dans une matrice de stockage, vous pouvez déverrouiller les données du disque en ajoutant le fichier de clé de sécurité associé aux disques. Si vous n'avez pas de clé de sécurité, vous pouvez réinitialiser chaque disque verrouillé en saisissant son ID de sécurité physique (PSID) pour réinitialiser ses attributs de sécurité et effacer les données du lecteur.

.Avant de commencer
* Pour l'option déverrouiller, assurez-vous que le fichier de clé de sécurité (avec une extension de `.slk`) Est disponible sur le client de gestion (le système avec un navigateur utilisé pour accéder à System Manager). Vous devez également connaître la phrase de passe associée à la clé.
* Pour l'option Réinitialiser, vous devez trouver le PSID sur chaque lecteur que vous souhaitez réinitialiser. Pour localiser le PSID, retirez physiquement le lecteur et localisez la chaîne PSID (32 caractères maximum) sur l'étiquette du lecteur, puis réinstallez le lecteur.


.Description de la tâche
Cette tâche explique comment déverrouiller les données des disques NVMe ou FIPS en important un fichier de clé de sécurité dans la baie de stockage. Dans les cas où la clé de sécurité n'est pas disponible, cette tâche explique également comment effectuer une réinitialisation sur un lecteur verrouillé.

[NOTE]
====
Si le lecteur a été verrouillé à l'aide d'un serveur de gestion externe des clés, sélectionnez menu:Paramètres[système > gestion des clés de sécurité] dans System Manager pour configurer la gestion externe des clés et déverrouiller le lecteur.

====
Vous pouvez accéder à la fonction déverrouiller à partir de la page matériel ou du menu:Paramètres[système > gestion des clés de sécurité]. La tâche ci-dessous fournit des instructions à partir de la page matériel.

.Étapes
. Sélectionnez *matériel*.
. Si le graphique montre les contrôleurs, cliquez sur *Afficher le recto du tiroir*.
+
Le graphique change pour afficher les disques au lieu des contrôleurs.

. Sélectionnez le lecteur NVMe ou FIPS que vous souhaitez déverrouiller ou réinitialiser.
+
Le menu contextuel du lecteur s'ouvre.

. Sélectionnez *Unlock* pour appliquer le fichier de clé de sécurité ou *Reset* si vous ne disposez pas d'un fichier de clé de sécurité.
+
Ces options s'affichent uniquement si vous sélectionnez un lecteur NVMe ou FIPS verrouillé.

+
[CAUTION]
====
Pendant une opération de réinitialisation, toutes les données sont effacées. Effectuez une réinitialisation uniquement si vous ne possédez pas de clé de sécurité. La réinitialisation d'un lecteur verrouillé supprime définitivement toutes les données du lecteur et réinitialise ses attributs de sécurité sur « sécurisé », mais pas activé. *Cette opération n'est pas réversible.*

====
. Effectuez l'une des opérations suivantes :
+
.. *Unlock* : dans la boîte de dialogue *Unlock Secure Drive*, cliquez sur *Browse*, puis sélectionnez le fichier de clé de sécurité correspondant au lecteur que vous souhaitez déverrouiller. Ensuite, entrez la phrase de passe, puis cliquez sur *déverrouiller*.
.. *Réinitialiser* : dans la boîte de dialogue *Réinitialiser le lecteur verrouillé*, entrez la chaîne PSID dans le champ, puis tapez `RESET` pour confirmer. Cliquez sur *Réinitialiser*.
+
Pour déverrouiller toutes les unités NVMe ou FIPS, il vous suffit d'effectuer cette opération une seule fois. Pour une opération de réinitialisation, vous devez sélectionner individuellement chaque lecteur que vous souhaitez réinitialiser.





.Résultats
Le lecteur peut désormais être utilisé dans un autre groupe de volumes ou un autre pool de disques, ou dans une autre matrice de stockage.
