---
permalink: um-manage/discover-multiple-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, multiple, storage, arrays 
summary: Vous découvrez plusieurs baies pour détecter toutes les baies de stockage dans le sous-réseau où réside le serveur de gestion et ajouter automatiquement les baies découvertes à votre domaine de gestion. 
---
= Découvrir plusieurs baies de stockage
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous découvrez plusieurs baies pour détecter toutes les baies de stockage dans le sous-réseau où réside le serveur de gestion et ajouter automatiquement les baies découvertes à votre domaine de gestion.

.Avant de commencer
* Vous devez être connecté avec un profil utilisateur qui inclut les autorisations d'administrateur de sécurité.
* La matrice de stockage doit être correctement installée et configurée.
* Les mots de passe de la baie de stockage doivent être configurés à l'aide de la mosaïque Access Management de System Manager.
* Pour résoudre les certificats non approuvés, vous devez disposer de fichiers de certificats approuvés d'une autorité de certification (CA), et les fichiers de certificats sont disponibles sur votre système local.


La détection des matrices est une procédure à plusieurs étapes.



== Étape 1 : saisissez l'adresse réseau

Vous entrez une plage d'adresses réseau pour effectuer une recherche sur le sous-réseau local. Toute matrice de stockage atteinte s'affiche sur la page Discover et peut-être ajoutée à votre domaine de gestion.

Si vous devez arrêter l'opération de détection pour une raison quelconque, cliquez sur *Arrêter la détection*.

.Étapes
. Dans la page gérer, sélectionnez *Ajouter/découvrir*.
+
La boîte de dialogue Ajouter/découvrir s'affiche.

. Sélectionnez le bouton radio *découvrir toutes les matrices de stockage dans une plage de réseau*.
. Entrez l'adresse réseau de départ et l'adresse réseau de fin pour effectuer une recherche sur votre sous-réseau local, puis cliquez sur *Démarrer la découverte*.
+
Le processus de détection démarre. Ce processus de détection peut prendre plusieurs minutes. Le tableau de la page découverte est rempli au fur et à mesure que les matrices de stockage sont découvertes.

+
[NOTE]
====
Si aucune baie gérable n'est détectée, vérifiez que les matrices de stockage sont correctement connectées à votre réseau et que leurs adresses attribuées sont à portée. Cliquez sur *nouveaux paramètres de découverte* pour revenir à la page Ajouter/découvrir.

====
. Consultez la liste des baies de stockage découvertes.
. Cochez la case en regard de toute matrice de stockage que vous souhaitez ajouter à votre domaine de gestion, puis cliquez sur *Suivant*.
+
Unified Manager effectue une vérification des informations d'identification sur chaque baie que vous ajoutez au domaine de gestion. Vous devrez peut-être résoudre tous les certificats auto-signés et non approuvés associés à cette baie.

. Cliquez sur *Suivant* pour passer à l'étape suivante de l'assistant.




== Étape 2 : résolution des certificats auto-signés pendant la découverte

Dans le cadre du processus de détection, le système vérifie que les matrices de stockage utilisent des certificats par une source de confiance.

.Étapes
. Effectuez l'une des opérations suivantes :
+
** Si vous faites confiance aux connexions aux matrices de stockage découvertes, passez à la carte suivante de l'assistant. Les certificats auto-signés seront marqués comme fiables et les baies de stockage seront ajoutées à Unified Manager.
** Si vous ne faites pas confiance aux connexions aux matrices de stockage, sélectionnez *Annuler* et validez la stratégie de certificat de sécurité de chaque matrice de stockage avant d'ajouter une de ces connexions à Unified Manager.


. Cliquez sur *Suivant* pour passer à l'étape suivante de l'assistant.




== Étape 3 : résolution de certificats non approuvés lors de la découverte

Des certificats non fiables se produisent lorsqu'une baie de stockage tente d'établir une connexion sécurisée à Unified Manager, mais que la connexion ne parvient pas à confirmer la sécurité. Au cours du processus de détection de la baie, vous pouvez résoudre les certificats non approuvés en important un certificat (ou certificat signé par l'autorité de certification) émis par un tiers de confiance.

Vous devrez peut-être installer d'autres certificats d'autorité de certification de confiance si l'un des éléments suivants est vrai :

* Vous avez ajouté récemment une baie de stockage.
* Un ou les deux certificats ont expiré.
* Un ou les deux certificats sont révoqués.
* Un ou les deux certificats ne sont pas titulaires d'un certificat racine ou intermédiaire.


.Étapes
. Cochez la case en regard de toute matrice de stockage pour laquelle vous souhaitez résoudre les certificats non approuvés, puis sélectionnez le bouton **Importer**.
+
Une boîte de dialogue s'ouvre pour importer les fichiers de certificats approuvés.

. Cliquez sur *Parcourir* pour sélectionner les fichiers de certificat des matrices de stockage.
+
Les noms de fichiers s'affichent dans la boîte de dialogue.

. Cliquez sur *Importer*.
+
Les fichiers sont chargés et validés.

+
[NOTE]
====
Toute matrice de stockage présentant des problèmes de certificat non approuvés non résolus n'est pas ajoutée à Unified Manager.

====
. Cliquez sur *Suivant* pour passer à l'étape suivante de l'assistant.




== Étape 4 : fournir des mots de passe

Vous devez entrer les mots de passe des matrices de stockage que vous souhaitez ajouter à votre domaine de gestion.

.Étapes
. Entrez le mot de passe de chaque matrice de stockage à ajouter à Unified Manager.
. *Facultatif :* associer des matrices de stockage à un groupe : dans la liste déroulante, sélectionnez le groupe souhaité à associer aux matrices de stockage sélectionnées.
. Cliquez sur *Terminer*.


.Une fois que vous avez terminé
Les matrices de stockage sont ajoutées à votre domaine de gestion et associées au groupe sélectionné (si spécifié).

[NOTE]
====
La connexion de Unified Manager aux baies de stockage spécifiées peut prendre plusieurs minutes.

====