---
permalink: um-manage/import-autosupport-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, autosupport, settings 
summary: 'Vous pouvez importer une configuration AutoSupport d"une baie de stockage vers d"autres baies de stockage. Cette opération de traitement par lot permet de gagner du temps lorsque vous devez configurer plusieurs baies sur le réseau.' 
---
= Importer les paramètres AutoSupport
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez importer une configuration AutoSupport d'une baie de stockage vers d'autres baies de stockage. Cette opération de traitement par lot permet de gagner du temps lorsque vous devez configurer plusieurs baies sur le réseau.

.Avant de commencer
* AutoSupport est configuré dans System Manager pour la baie de stockage que vous souhaitez utiliser comme source (menu : support[Centre de support]).
* La configuration existante des baies de stockage cibles est sauvegardée dans System Manager (menu:Paramètres[système > Enregistrer la configuration de la matrice de stockage]).


.Description de la tâche
Les paramètres importés comprennent les fonctionnalités séparées (AutoSupport de base, AutoSupport OnDemand et diagnostic à distance), la fenêtre de maintenance, la méthode de livraison, et les plannings d'intervention.

.Étapes
. Dans la page gérer, cliquez sur *Importer les paramètres*.
+
L'assistant Importer les paramètres s'ouvre.

. Dans la boîte de dialogue Sélectionner les paramètres, sélectionnez *AutoSupport*, puis cliquez sur *Suivant*.
+
Une boîte de dialogue s'ouvre pour sélectionner le tableau source.

. Dans la boîte de dialogue Sélectionner la source, sélectionnez la matrice avec les paramètres à importer, puis cliquez sur *Suivant*.
. Dans la boîte de dialogue Sélectionner des cibles, sélectionnez une ou plusieurs matrices pour recevoir les nouveaux paramètres.
+
[NOTE]
====
Les matrices de stockage avec un micrologiciel inférieur à 8.50 ne sont pas disponibles pour la sélection. En outre, une baie n'apparaît pas dans cette boîte de dialogue si Unified Manager ne peut pas communiquer avec cette baie (par exemple, s'il est hors ligne ou s'il présente des problèmes de certificat, de mot de passe ou de mise en réseau).

====
. Cliquez sur *Terminer*.
+
La page opérations affiche les résultats de l'opération d'importation. Si l'opération échoue, vous pouvez cliquer sur sa ligne pour afficher plus d'informations.



.Résultats
Les baies de stockage cibles sont désormais configurées avec les mêmes paramètres AutoSupport que la baie source.
