---
permalink: um-manage/import-storage-configuration-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, storage, configuration, settings 
summary: 'Vous pouvez importer la configuration de stockage d"une matrice de stockage vers d"autres matrices de stockage. Cette opération de traitement par lot permet de gagner du temps lorsque vous devez configurer plusieurs baies sur le réseau.' 
---
= Importer les paramètres de configuration du stockage
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez importer la configuration de stockage d'une matrice de stockage vers d'autres matrices de stockage. Cette opération de traitement par lot permet de gagner du temps lorsque vous devez configurer plusieurs baies sur le réseau.

.Avant de commencer
* Le stockage est configuré dans SANtricity System Manager pour la baie de stockage que vous souhaitez utiliser comme source.
* La configuration existante des baies de stockage cibles est sauvegardée dans System Manager (menu:Paramètres[système > Enregistrer la configuration de la matrice de stockage]).
* Les baies source et cible doivent répondre à ces exigences :
+
** Les tiroirs où les contrôleurs résident doivent être identiques.
** Les ID de tiroir doivent être identiques.
** Les tiroirs d'extension doivent être installés dans les mêmes emplacements avec les mêmes types de disques.
** Le type de boîtier RBOD doit être identique.
** Les HIC, y compris les fonctionnalités Data assurance de l'hôte, doivent être identiques.
** Les baies cibles doivent être en état optimal.
** La capacité de volume de la baie cible est supérieure à la capacité de la baie source.


* Vous comprenez les restrictions suivantes :
+
** L'importation d'une configuration recto-verso vers une configuration recto-verso n'est pas prise en charge. Cependant, l'importation d'une configuration recto-verso est autorisée.
** Les volumes de pool de disques de 64 To ou plus sur la baie source empêchent le processus d'importation sur les cibles.
** Les volumes fins ne sont pas inclus dans le processus d'importation.




.Description de la tâche
Les paramètres importés comprennent les volumes configurés (volumes épais et non référentiels uniquement), les groupes de volumes, les pools et les affectations de disques de secours.

.Étapes
. Dans la page gérer, cliquez sur *Importer les paramètres*.
+
L'assistant Importer les paramètres s'ouvre.

. Dans la boîte de dialogue Sélectionner les paramètres, sélectionnez *Configuration de stockage*, puis cliquez sur *Suivant*.
+
Une boîte de dialogue s'ouvre pour sélectionner le tableau source.

. Dans la boîte de dialogue Sélectionner la source, sélectionnez la matrice avec les paramètres à importer, puis cliquez sur *Suivant*.
. Dans la boîte de dialogue Sélectionner des cibles, sélectionnez une ou plusieurs matrices pour recevoir les nouveaux paramètres.
+
[NOTE]
====
Les matrices de stockage avec un micrologiciel inférieur à 8.50 ne sont pas disponibles pour la sélection. En outre, une baie n'apparaît pas dans cette boîte de dialogue si Unified Manager ne peut pas communiquer avec cette baie (par exemple, s'il est hors ligne ou s'il présente des problèmes de certificat, de mot de passe ou de mise en réseau).

====
. Cliquez sur *Terminer*.
+
La page opérations affiche les résultats de l'opération d'importation. Si l'opération échoue, vous pouvez cliquer sur sa ligne pour afficher plus d'informations.



.Résultats
Les baies de stockage cibles sont désormais configurées avec la même configuration de stockage que la baie source.
