---
permalink: um-manage/import-directory-services-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, directory, services, settings 
summary: 'Vous pouvez importer une configuration de services d"annuaire d"une matrice de stockage vers d"autres matrices de stockage. Cette opération de traitement par lot permet de gagner du temps lorsque vous devez configurer plusieurs baies sur le réseau.' 
---
= Importer les paramètres des services d'annuaire
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez importer une configuration de services d'annuaire d'une matrice de stockage vers d'autres matrices de stockage. Cette opération de traitement par lot permet de gagner du temps lorsque vous devez configurer plusieurs baies sur le réseau.

.Avant de commencer
* Les services d'annuaire sont configurés dans System Manager pour la matrice de stockage que vous souhaitez utiliser comme source (menu:Paramètres[Access Management]).
* La configuration existante des baies de stockage cibles est sauvegardée dans System Manager (menu:Paramètres[système > Enregistrer la configuration de la matrice de stockage]).


.Description de la tâche
Les paramètres importés comprennent le nom de domaine et l'URL d'un serveur LDAP (Lightweight Directory Access Protocol), ainsi que les mappages entre les groupes d'utilisateurs du serveur LDAP et les rôles prédéfinis de la baie de stockage.

.Étapes
. Dans la page gérer, cliquez sur *Importer les paramètres*.
+
L'assistant Importer les paramètres s'ouvre.

. Dans la boîte de dialogue Sélectionner les paramètres, sélectionnez *Services Annuaire*, puis cliquez sur *Suivant*.
+
Une boîte de dialogue s'ouvre pour sélectionner le tableau source.

. Dans la boîte de dialogue Sélectionner la source, sélectionnez la matrice avec les paramètres à importer, puis cliquez sur *Suivant*.
. Dans la boîte de dialogue Sélectionner des cibles, sélectionnez une ou plusieurs matrices pour recevoir les nouveaux paramètres.
+
[NOTE]
====
Les matrices de stockage avec un micrologiciel inférieur à 8.50 ne sont pas disponibles pour la sélection. En outre, une baie n'apparaît pas dans cette boîte de dialogue si Unified Manager ne peut pas communiquer avec cette baie (par exemple, s'il est hors ligne ou s'il présente des problèmes de certificat, de mot de passe ou de mise en réseau).

====
. Cliquez sur *Terminer*.
+
La page opérations affiche les résultats de l'opération d'importation. Si l'opération échoue, vous pouvez cliquer sur sa ligne pour afficher plus d'informations.





== Résultats

Les matrices de stockage cibles sont maintenant configurées avec les mêmes services de répertoire que la matrice source.
