---
permalink: um-manage/mirroring-terminology.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, terminology 
summary: 'Découvrez comment les conditions de mise en miroir s"appliquent à votre baie de stockage.' 
---
= Terminologie de la mise en miroir
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment les conditions de mise en miroir s'appliquent à votre baie de stockage.

[cols="25h,~"]
|===
| Durée | Description 


 a| 
Baie de stockage locale
 a| 
La baie de stockage locale est la baie de stockage sur laquelle vous agissez.



 a| 
Groupe de cohérence en miroir
 a| 
Un groupe de cohérence en miroir est un conteneur pour une ou plusieurs paires en miroir. Pour les opérations de mise en miroir asynchrone, vous devez créer un groupe de cohérence miroir. Toutes les paires mises en miroir d'un groupe sont synchronisées simultanément, ce qui préserve un point de restauration cohérent.

La mise en miroir synchrone n'utilise pas les groupes de cohérence du miroir.



 a| 
Paire en miroir
 a| 
Une paire en miroir comprend deux volumes, un volume primaire et un volume secondaire.

Dans le cas de la mise en miroir asynchrone, une paire en miroir appartient toujours à un groupe de cohérence en miroir. Les opérations d'écriture s'effectuent d'abord sur le volume primaire, puis sont répliquées vers le volume secondaire. Chaque paire en miroir d'un groupe de cohérence miroir partage les mêmes paramètres de synchronisation.



 a| 
Volume primaire
 a| 
Le volume principal d'une paire en miroir est le volume source à mettre en miroir.



 a| 
Baie de stockage distante
 a| 
La matrice de stockage distante est généralement désignée comme site secondaire, qui contient généralement une réplique des données dans une configuration de mise en miroir.



 a| 
Capacité réservée
 a| 
La capacité réservée est la capacité physique allouée utilisée pour toute opération de service de copie et tout objet de stockage. Il n'est pas directement lisible par l'hôte.

Ces volumes sont requis pour que le contrôleur puisse enregistrer de manière persistante les informations requises pour maintenir la mise en miroir à l'état opérationnel. Elles contiennent des informations telles que les journaux delta et les données de copie sur écriture.



 a| 
Volume secondaire
 a| 
Le volume secondaire d'une paire en miroir se trouve généralement sur un site secondaire et contient une réplique des données.



 a| 
Synchronisation
 a| 
La synchronisation a lieu lors de la synchronisation initiale entre la matrice de stockage locale et la matrice de stockage distante. La synchronisation se produit également lorsque les volumes primaire et secondaire ne sont plus synchronisés après une interruption de communication. Lorsque la liaison de communication fonctionne de nouveau, toutes les données non répliquées sont synchronisées avec la matrice de stockage du volume secondaire.

|===