---
permalink: um-manage/upgrade-considerations.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, considerations 
summary: 'Avant d"utiliser Unified Manager pour mettre à niveau plusieurs baies de stockage, prenez en compte les considérations clés dans le cadre de votre planification.' 
---
= Mise à niveau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser Unified Manager pour mettre à niveau plusieurs baies de stockage, prenez en compte les considérations clés dans le cadre de votre planification.



== Versions actuelles

Vous pouvez consulter les versions actuelles du logiciel SANtricity OS à partir de la page Manage of Unified Manager (gérer les versions de chaque baie de stockage détectée). La version est indiquée dans la colonne logiciel SANtricity OS. Les informations relatives au micrologiciel du contrôleur et à la NVSRAM sont disponibles dans une boîte de dialogue contextuelle lorsque vous cliquez sur la version du système d'exploitation SANtricity dans chaque ligne.



== Les autres composants doivent être mis à niveau

Dans le cadre du processus de mise à niveau, vous devrez peut-être également mettre à niveau le pilote multivoie/basculement de l'hôte ou le pilote HBA afin que l'hôte puisse interagir correctement avec les contrôleurs.

Pour plus d'informations sur la compatibilité, reportez-vous à la section https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp"^]. Consultez également les procédures des Guides Express pour votre système d'exploitation. Des guides Express sont disponibles sur le https://docs.netapp.com/us-en/e-series/index.html["Documentation sur les systèmes E-Series et SANtricity"^].



== Doubles contrôleurs

Si une baie de stockage contient deux contrôleurs et qu'un pilote multivoie est installé, la baie de stockage peut continuer à traiter les E/S pendant la mise à niveau. Pendant la mise à niveau, la procédure suivante se produit :

. Le contrôleur A bascule de toutes ses LUN vers le contrôleur B.
. La mise à niveau se produit sur le contrôleur A.
. Le contrôleur A revient ses LUN et toutes les LUN du contrôleur B.
. La mise à niveau se produit sur le contrôleur B.


Une fois la mise à niveau terminée, vous devrez peut-être redistribuer manuellement les volumes entre les contrôleurs afin de garantir que les volumes reviennent au contrôleur propriétaire approprié.
