---
permalink: sm-settings/add-syslog-servers-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, syslog, servers, alerts, 
summary: Vous pouvez ajouter au maximum cinq serveurs pour les alertes syslog. 
---
= Ajouter des serveurs syslog pour les alertes
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter au maximum cinq serveurs pour les alertes syslog.

.Avant de commencer
* L'adresse du serveur syslog doit être disponible. Cette adresse peut être un nom de domaine complet, une adresse IPv4 ou une adresse IPv6.
* Le numéro de port UDP du serveur syslog doit être disponible. Ce port est généralement 514.


.Étapes
. Sélectionnez menu:Paramètres[alertes].
. Sélectionnez l'onglet *Syslog*.
. Sélectionnez *Ajouter des serveurs Syslog*.
+
La boîte de dialogue Ajouter un serveur Syslog s'ouvre.

. Sélectionnez *Ajouter un autre serveur syslog*.
. Entrez les informations relatives au serveur syslog, puis cliquez sur *Ajouter*.
+
** *Adresse du serveur Syslog* -- Entrez un nom de domaine complet, une adresse IPv4 ou une adresse IPv6.
** *Port UDP* -- généralement, le port UDP pour syslog est 514.


+

NOTE: Vous pouvez configurer jusqu'à cinq serveurs syslog.



.Résultats
Les adresses des serveurs syslog apparaissent dans le tableau.
