---
permalink: sm-settings/change-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, security, key, 
summary: Vous pouvez à tout moment remplacer une clé de sécurité par une nouvelle clé. Vous devrez peut-être modifier une clé de sécurité dans les cas où vous pourriez avoir une violation de sécurité potentielle au sein de votre entreprise et vous assurer que le personnel non autorisé ne peut pas accéder aux données des lecteurs. 
---
= Modifier la clé de sécurité
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez à tout moment remplacer une clé de sécurité par une nouvelle clé. Vous devrez peut-être modifier une clé de sécurité dans les cas où une faille de sécurité est potentielle au sein de votre entreprise et si vous souhaitez que du personnel non autorisé ne puisse pas accéder aux données des disques.

.Étapes
. Sélectionnez menu:Paramètres[système].
. Sous *gestion des clés de sécurité*, sélectionnez *changer la clé*.
+
La boîte de dialogue Modifier la clé de sécurité s'ouvre.

. Entrez les informations dans les champs suivants.
+
** *Définir un identificateur de clé de sécurité* -- (pour les clés de sécurité internes uniquement). Acceptez la valeur par défaut (nom de la matrice de stockage et horodatage générés par le micrologiciel du contrôleur) ou entrez votre propre valeur. Vous pouvez entrer jusqu'à 189 caractères alphanumériques sans espaces, signes de ponctuation ni symboles.
+
[NOTE]
====
Des caractères supplémentaires sont générés automatiquement et ajoutés aux deux extrémités de la chaîne que vous entrez. Les caractères générés permettent de s'assurer que l'identificateur est unique.

====
** *Définir une phrase de passe/saisir à nouveau une phrase de passe* -- dans chacun de ces champs, entrez votre phrase de passe. La valeur peut comporter entre 8 et 32 caractères et doit comprendre chacun des éléments suivants :
+
*** Une lettre majuscule (une ou plusieurs). Gardez à l'esprit que la phrase de passe est sensible à la casse.
*** Un nombre (un ou plusieurs).
*** Caractère non alphanumérique, tel que !, *, @ (un ou plusieurs).




. Pour les clés de sécurité externes, si vous souhaitez supprimer l'ancienne clé de sécurité lorsque la nouvelle clé est créée, cochez la case « Supprimer la clé de sécurité actuelle... » en bas de la boîte de dialogue.
+
[CAUTION]
====
*Assurez-vous d'enregistrer vos entrées pour une utilisation ultérieure* -- si vous devez déplacer un lecteur sécurisé de la matrice de stockage, vous devez connaître l'identifiant et passer la phrase pour déverrouiller les données du lecteur.

====
. Cliquez sur *Modifier*.
+
La nouvelle clé de sécurité remplace la clé précédente, qui n'est plus valide.

+
[NOTE]
====
Le chemin du fichier téléchargé peut dépendre de l'emplacement de téléchargement par défaut de votre navigateur.

====
. Enregistrez votre identifiant de clé, votre phrase de passe et l'emplacement du fichier de clé téléchargé, puis cliquez sur *Fermer*.


.Une fois que vous avez terminé
Vous devez valider la clé de sécurité pour vous assurer que le fichier clé n'est pas corrompu.
