---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: Vous pouvez définir la longueur minimale requise pour tous les mots de passe utilisateur locaux nouveaux ou mis à jour sur la matrice de stockage. Vous pouvez également autoriser les utilisateurs locaux à accéder à la matrice de stockage sans saisir de mot de passe. 
---
= Modifier les paramètres de mot de passe de l'utilisateur local
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez définir la longueur minimale requise pour tous les mots de passe utilisateur locaux nouveaux ou mis à jour sur la matrice de stockage. Vous pouvez également autoriser les utilisateurs locaux à accéder à la matrice de stockage sans saisir de mot de passe.

.Avant de commencer
Vous devez être connecté en tant qu'administrateur local, qui inclut les autorisations d'administrateur racine.

.Description de la tâche
Tenez compte des consignes suivantes lorsque vous définissez la longueur minimale des mots de passe utilisateur locaux :

* Les modifications apportées aux paramètres n'affectent pas les mots de passe des utilisateurs locaux existants.
* Le paramètre de longueur minimum requis pour les mots de passe utilisateur local doit comporter entre 0 et 30 caractères.
* Tout nouveau mot de passe utilisateur local doit respecter ou dépasser le paramètre de longueur minimale actuel.
* Ne définissez pas de longueur minimale pour le mot de passe si vous souhaitez que les utilisateurs locaux accèdent à la matrice de stockage sans saisir de mot de passe.


.Étapes
. Sélectionnez menu:Paramètres[gestion des accès].
. Sélectionnez l'onglet *rôles d'utilisateur local*.
. Sélectionnez le bouton *Afficher/Modifier les paramètres*.
+
La boîte de dialogue Paramètres du mot de passe de l'utilisateur local s'ouvre.

. Effectuez l'une des opérations suivantes :
+
** Pour permettre aux utilisateurs locaux d'accéder à la matrice de stockage _sans_ saisir un mot de passe, décochez la case « exiger au moins tous les mots de passe des utilisateurs locaux ».
** Pour définir une longueur minimale de mot de passe pour tous les mots de passe d'utilisateur local, cochez la case « exiger au moins tous les mots de passe d'utilisateur local », puis utilisez la case à cocher pour définir la longueur minimale requise pour tous les mots de passe d'utilisateur local.
+
Tout nouveau mot de passe utilisateur local doit respecter ou dépasser le paramètre actuel.



. Cliquez sur *Enregistrer*.

