---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: Vous pouvez modifier les mots de passe utilisateur de chaque profil utilisateur dans Access Management. 
---
= Modifier les mots de passe
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les mots de passe utilisateur de chaque profil utilisateur dans Access Management.

.Avant de commencer
* Vous devez être connecté en tant qu'administrateur local, qui inclut les autorisations d'administrateur racine.
* Vous devez connaître le mot de passe administrateur local.


.Description de la tâche
Suivez les consignes suivantes lorsque vous choisissez un mot de passe :

* Tout nouveau mot de passe utilisateur local doit respecter ou dépasser le paramètre actuel pour un mot de passe minimum (dans Afficher/Modifier les paramètres).
* Les mots de passe sont sensibles à la casse.
* Les espaces de fin ne sont pas dépouillés des mots de passe lorsqu'ils sont définis. Veillez à inclure des espaces s'ils étaient inclus dans le mot de passe.
* Pour renforcer la sécurité, utilisez au moins 15 caractères alphanumériques et modifiez fréquemment le mot de passe.


[NOTE]
====
La modification du mot de passe dans System Manager modifie également celui-ci dans l'interface de ligne de commande. En outre, les modifications de mot de passe entraînent la fin de la session active de l'utilisateur.

====
.Étapes
. Sélectionnez menu:Paramètres[gestion des accès].
. Sélectionnez l'onglet *rôles d'utilisateur local*.
. Sélectionnez un utilisateur dans le tableau.
+
Le bouton Modifier le mot de passe devient disponible.

. Sélectionnez *Modifier le mot de passe*.
+
La boîte de dialogue modification du mot de passe s'ouvre.

. Si aucun mot de passe minimum n'est défini pour les mots de passe d'utilisateur local, vous pouvez cocher la case pour demander à l'utilisateur sélectionné d'entrer un mot de passe pour accéder à la matrice de stockage, puis vous pouvez saisir le nouveau mot de passe pour l'utilisateur sélectionné.
. Entrez votre mot de passe administrateur local, puis cliquez sur *Modifier*.


.Résultats
Si l'utilisateur est actuellement connecté, le changement de mot de passe entraîne la fin de la session active de l'utilisateur.
