---
permalink: sm-settings/configure-iser-over-infiniband-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iser, over, infiniband, ports, 
summary: 'Si votre contrôleur inclut un port iser sur InfiniBand, vous pouvez configurer la connexion réseau à l"hôte.' 
---
= Configurez iser sur les ports InfiniBand
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si votre contrôleur inclut un port iser sur InfiniBand, vous pouvez configurer la connexion réseau à l'hôte.

.Avant de commencer
* Votre contrôleur doit inclure un iser sur le port InfiniBand ; sinon, les paramètres iser over InfiniBand ne sont pas disponibles dans System Manager.
* Vous devez connaître l'adresse IP de la connexion hôte.


.Étapes
. Sélectionnez menu:Paramètres[système].
. Sous *iser sur les paramètres InfiniBand*, sélectionnez *configurer iser sur les ports InfiniBand*.
. Cliquez sur le contrôleur avec le port iser sur InfiniBand que vous souhaitez configurer. Cliquez sur *Suivant*.
. Dans la liste déroulante, sélectionnez le port HIC que vous souhaitez configurer, puis entrez l'adresse IP de l'hôte.
. Cliquez sur *Terminer*.
. Réinitialisez l'iser sur le port InfiniBand en cliquant sur *Oui*.

