---
permalink: sm-settings/configure-iscsi-authentication.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, authentication, 
summary: 'Pour plus de sécurité sur un réseau iSCSI, vous pouvez définir l"authentification entre les contrôleurs (cibles) et les hôtes (initiateurs).' 
---
= Configurez l'authentification iSCSI
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour plus de sécurité sur un réseau iSCSI, vous pouvez définir l'authentification entre les contrôleurs (cibles) et les hôtes (initiateurs).

System Manager utilise la méthode CHAP (Challenge Handshake Authentication Protocol) qui valide l'identité des cibles et des initiateurs pendant la liaison initiale. L'authentification est basée sur une clé de sécurité partagée appelée secret_CHAP_.

.Avant de commencer
Vous pouvez définir le secret CHAP pour les initiateurs (hôtes iSCSI) avant ou après avoir défini le secret CHAP pour les cibles (contrôleurs). Avant de suivre les instructions de cette tâche, vous devez attendre que les hôtes aient d'abord établi une connexion iSCSI, puis définir le secret CHAP sur les hôtes individuels. Une fois les connexions effectuées, les noms IQN des hôtes et leurs secrets CHAP sont répertoriés dans la boîte de dialogue pour l'authentification iSCSI (décrite dans cette tâche) et vous n'avez pas besoin de les saisir manuellement.

.Description de la tâche
Vous pouvez sélectionner l'une des méthodes d'authentification suivantes :

* *Authentification unidirectionnelle* -- utilisez ce paramètre pour permettre au contrôleur d'authentifier l'identité des hôtes iSCSI (authentification unidirectionnelle).
* *Authentification bidirectionnelle* -- utilisez ce paramètre pour permettre au contrôleur et aux hôtes iSCSI d'effectuer l'authentification (authentification bidirectionnelle). Ce paramètre fournit un second niveau de sécurité en permettant au contrôleur d'authentifier l'identité des hôtes iSCSI et, à son tour, les hôtes iSCSI d'authentifier l'identité du contrôleur.


[NOTE]
====
Les paramètres et fonctions iSCSI s'affichent uniquement sur la page Paramètres si votre matrice de stockage prend en charge iSCSI.

====
.Étapes
. Sélectionnez menu:Paramètres[système].
. Sous Paramètres iSCSI, cliquez sur *configurer l'authentification*.
+
La boîte de dialogue configurer l'authentification s'affiche, indiquant la méthode actuellement définie. Elle indique également si des secrets CHAP sont configurés pour tous les hôtes.

. Sélectionnez l'une des options suivantes :
+
** *Pas d'authentification* -- si vous ne souhaitez pas que le contrôleur authentifie l'identité des hôtes iSCSI, sélectionnez cette option et cliquez sur *Terminer*. La boîte de dialogue se ferme et vous avez terminé avec la configuration.
** *Authentification unidirectionnelle* -- pour permettre au contrôleur d'authentifier l'identité des hôtes iSCSI, sélectionnez cette option et cliquez sur *Suivant* pour afficher la boîte de dialogue configurer CHAP cible.
** *Authentification bidirectionnelle* -- pour permettre à la fois au contrôleur et aux hôtes iSCSI d'effectuer l'authentification, sélectionnez cette option et cliquez sur *Suivant* pour afficher la boîte de dialogue configurer CHAP cible.


. Pour l'authentification unidirectionnelle ou bidirectionnelle, entrez ou confirmez le secret CHAP du contrôleur (la cible). Le secret CHAP doit comporter entre 12 et 57 caractères ASCII imprimables.
+
[NOTE]
====
Si le secret CHAP du contrôleur a été configuré précédemment, les caractères du champ sont masqués. Si nécessaire, vous pouvez remplacer les caractères existants (les nouveaux caractères ne sont pas masqués).

====
. Effectuez l'une des opérations suivantes :
+
** Si vous configurez l'authentification _unidirectionnel_, cliquez sur *Finish*. La boîte de dialogue se ferme et vous avez terminé avec la configuration.
** Si vous configurez _Two-Way_ Authentication, cliquez sur *Next* pour afficher la boîte de dialogue Configure Initiator CHAP.


. Pour l'authentification bidirectionnelle, entrez ou confirmez un secret CHAP pour l'un des hôtes iSCSI (les initiateurs), qui peut comporter entre 12 et 57 caractères ASCII imprimables. Si vous ne souhaitez pas configurer l'authentification bidirectionnelle pour un hôte particulier, laissez le champ secret CHAP de l'initiateur vide.
+
[NOTE]
====
Si le secret CHAP d'un hôte a été configuré précédemment, les caractères du champ sont masqués. Si nécessaire, vous pouvez remplacer les caractères existants (les nouveaux caractères ne sont pas masqués).

====
. Cliquez sur *Terminer*.


.Résultats
L'authentification se produit pendant la séquence de connexion iSCSI entre les contrôleurs et les hôtes iSCSI, à moins que vous n'ayez spécifié aucune authentification.
