---
permalink: sm-settings/configure-nvme-over-infiniband-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, nvme, over, InfiniBand, ports, 
summary: Si votre contrôleur inclut une connexion NVMe over InfiniBand, vous pouvez configurer les paramètres du port NVMe à partir de la page système. 
---
= Configurer les ports NVMe over InfiniBand
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si votre contrôleur inclut une connexion NVMe over InfiniBand, vous pouvez configurer les paramètres du port NVMe à partir de la page système.

.Avant de commencer
* Votre contrôleur doit inclure un port hôte NVMe over InfiniBand. Sinon, les paramètres NVMe over InfiniBand ne sont pas disponibles dans System Manager.
* Vous devez connaître l'adresse IP de la connexion hôte.


[NOTE]
====
Les paramètres et les fonctions de NVMe over InfiniBand n'apparaissent que si le contrôleur de votre baie de stockage est équipé d'un port NVMe over InfiniBand.

====
.Étapes
. Sélectionnez menu:Paramètres[système].
. Sous *NVMe over InfiniBand settings*, sélectionnez *Configure NVMe over InfiniBand ports*.
. Sélectionnez le contrôleur doté du port NVMe over InfiniBand que vous souhaitez configurer. Cliquez sur *Suivant*.
. Sélectionnez le port HIC que vous souhaitez configurer dans la liste déroulante, puis saisissez l'adresse IP.
+
Si vous configurez une baie de stockage EF600 avec une HIC compatible 200 Go, cette boîte de dialogue affiche deux champs d'adresse IP, un pour un port physique (externe) et un pour un port virtuel (interne). Vous devez attribuer une adresse IP unique aux deux ports. Ces paramètres permettent à l'hôte d'établir un chemin entre chaque port et pour la HIC d'obtenir des performances optimales. Si vous n'attribuez pas d'adresse IP au port virtuel, la HIC fonctionne à environ la moitié de sa vitesse.

. Cliquez sur *Terminer*.
. Réinitialisez le port NVMe over InfiniBand en cliquant sur *Yes*.

