---
permalink: sm-settings/delete-alert-email-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, mail, server, email, addresses, alerts, 
summary: Vous pouvez supprimer le serveur de messagerie précédemment défini afin que les alertes ne soient plus envoyées aux adresses électroniques, ou vous pouvez supprimer des adresses électroniques individuelles. 
---
= Supprimez le serveur de messagerie ou les adresses e-mail pour les alertes
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer le serveur de messagerie précédemment défini afin que les alertes ne soient plus envoyées aux adresses électroniques, ou vous pouvez supprimer des adresses électroniques individuelles.

.Étapes
. Sélectionnez menu:Paramètres[alertes].
. Sélectionnez l'onglet *E-mail*.
. Dans le tableau, effectuez l'une des opérations suivantes :
+
** Pour supprimer un serveur de messagerie afin que les alertes ne soient plus envoyées aux adresses e-mail, sélectionnez la ligne du serveur de messagerie.
** Pour supprimer une adresse e-mail afin que les alertes ne soient plus envoyées à cette adresse, sélectionnez la ligne de l'adresse e-mail que vous souhaitez supprimer. Le bouton *Supprimer* dans le coin supérieur droit de la table devient disponible pour la sélection.


. Cliquez sur *Supprimer* et confirmez l'opération.

