---
permalink: sm-settings/enable-or-disable-resource-provisioning-for-new-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, resource, provisioning, 
summary: Si vous avez précédemment désactivé la fonction par défaut pour le provisionnement de ressources, vous pouvez accéder à Paramètres et la réactiver pour tous les nouveaux groupes de volumes SSD ou pools que vous créez. Vous pouvez également désactiver le paramètre à nouveau. 
---
= Activer ou désactiver le provisionnement des ressources pour les nouveaux groupes de volumes ou pools dans SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez précédemment désactivé la fonction par défaut pour le provisionnement de ressources, vous pouvez la réactiver pour tous les groupes de volumes SSD ou pools que vous créez. Vous pouvez également désactiver le paramètre à nouveau.

L'allocation de ressources est une fonctionnalité disponible sur les baies de stockage EF80, EF50, EF300/EF300C et EF600/EF600C, qui permet une mise en service immédiate des volumes sans processus d'initialisation en arrière-plan. Tous les blocs de disque affectés au volume sont désalloués (non mappés), ce qui peut améliorer la durée de vie des SSD et augmenter les performances d'écriture maximales.


NOTE: Par défaut, le provisionnement de ressources est activé sur les systèmes sur lesquels les disques prennent en charge DULBE.

.Avant de commencer
* Vous devez disposer d'une baie de stockage EF80, EF50, EF300 ou EF600.
* Vous devez disposer de groupes ou de pools de volume SSD, où tous les disques prennent en charge la fonctionnalité de restauration d'erreur DULBE (Logical Block Error Enable) de NVMe avec une gestion simplifiée ou non écrite.


.Description de la tâche
Lorsque vous réactivez le provisionnement de ressources pour les nouveaux groupes ou pools de volumes, seuls les nouveaux groupes et pools de volumes sont affectés. Tous les groupes et pools de volumes existants sur lesquels le provisionnement de ressources est activé restent inchangés.

.Étapes
. Dans le panneau de gauche, sélectionnez menu:Settings[System].
. Faites défiler jusqu'à *Paramètres supplémentaires*, puis cliquez sur *Activer/Désactiver les volumes provisionnés par ressource*.
+
La description du paramètre indique si le provisionnement de ressources est actuellement activé ou désactivé.

. Dans la boîte de dialogue, confirmer l'opération.


.Résultats
L'activation ou la désactivation du provisionnement des ressources concerne uniquement les nouveaux pools SSD ou les groupes de volumes que vous créez. Les pools ou groupes de volumes existants restent inchangés.
