---
permalink: sm-settings/faq-nvme-protocol.html 
sidebar: sidebar 
keywords:  
summary: Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question. 
---
= FAQ sur le protocole NVMe pour SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question.



== Comment interpréter les statistiques NVMe over Fabrics ?

La boîte de dialogue Afficher les statistiques NVMe over Fabrics affiche les statistiques du sous-système NVMe et de l'interface RDMA. Toutes les statistiques sont en lecture seule et ne peuvent pas être définies.

* *Statistiques du sous-système NVMe* -- affiche les statistiques du contrôleur NVMe et de sa file d'attente. Le contrôleur NVMe fournit un chemin d'accès entre un hôte et les espaces de noms de la baie de stockage. Vous pouvez consulter les statistiques du sous-système NVMe pour des éléments tels que les échecs de connexion, les réinitialisations et les arrêts de service. Pour plus d'informations sur ces statistiques, cliquez sur *Afficher la légende pour les en-têtes de tableau*.
* *Statistiques de l'interface RDMA* -- fournit des statistiques sur tous les ports NVMe over Fabrics de l'interface RDMA, qui incluent des statistiques de performances et des informations sur les erreurs de liaison associées à chaque port de commutateur. Cet onglet s'affiche uniquement lorsque les ports NVMe over Fabrics sont disponibles. Pour plus d'informations sur les statistiques, cliquez sur *Afficher la légende pour les en-têtes de tableau*.


Vous pouvez afficher chacune de ces statistiques sous forme de statistiques brutes ou en tant que statistiques de base. Les statistiques brutes sont toutes les statistiques collectées depuis le démarrage des contrôleurs. Les statistiques de référence sont des statistiques ponctuelles qui ont été recueillies depuis que vous avez défini l'heure de référence.



== Que dois-je faire d'autre pour configurer ou diagnostiquer NVMe over InfiniBand ?

Le tableau suivant répertorie les fonctions de SANtricity System Manager que vous pouvez utiliser pour configurer et gérer les sessions NVMe over InfiniBand.

[NOTE]
====
Les paramètres NVMe over InfiniBand sont disponibles uniquement si le contrôleur de votre baie de stockage est doté d'un port NVMe over InfiniBand.

====
[cols="35h,~"]
|===
| Action | Emplacement 


 a| 
Configurer les ports NVMe over InfiniBand
 a| 
. Sélectionnez *matériel*.
. Sélectionnez l'onglet *contrôleurs et composants*.
. Sélectionnez un contrôleur.
. Sélectionnez *configurer NVMe sur les ports InfiniBand*.


ou

. Sélectionnez menu:Paramètres[système].
. Faites défiler jusqu'à *NVMe over InfiniBand settings*, puis sélectionnez *Configure NVMe over InfiniBand ports*.




 a| 
Affichez les statistiques NVMe sur InfiniBand
 a| 
. Sélectionnez menu:Paramètres[système].
. Faites défiler jusqu'à *NVMe over InfiniBand settings*, puis sélectionnez *View NVMe over Fabrics Statistics*.


|===


== Que dois-je faire pour configurer ou diagnostiquer NVMe over RoCE ?

Vous pouvez configurer et gérer NVMe over RoCE à partir des pages Hardware and Settings.

[NOTE]
====
Les paramètres NVMe over RoCE sont disponibles uniquement si le contrôleur de votre baie de stockage inclut un port NVMe over RoCE.

====
[cols="35h,~"]
|===
| Action | Emplacement 


 a| 
Configurez les ports NVMe over RoCE
 a| 
. Sélectionnez *matériel*.
. Sélectionnez l'onglet *contrôleurs et composants*.
. Sélectionnez un contrôleur.
. Sélectionnez *configurer les ports NVMe over RoCE*.


ou

. Sélectionnez menu:Paramètres[système].
. Faites défiler jusqu'à *NVMe over RoCE settings*, puis sélectionnez *Configure NVMe over RoCE ports*.




 a| 
Affichez les statistiques NVMe over Fabrics
 a| 
. Sélectionnez menu:Paramètres[système].
. Faites défiler jusqu'à *Paramètres NVMe over RoCE*, puis sélectionnez *Afficher les statistiques NVMe over Fabrics*.


|===


== Pourquoi y a-t-il deux adresses IP pour un port physique ?

La baie de stockage EF600 peut inclure deux HIC, un externe et un interne.

Dans cette configuration, la HIC externe est connectée à une HIC interne auxiliaire. Chaque port physique auquel vous pouvez accéder à partir de la HIC externe possède un port virtuel associé à partir de la HIC interne.

Pour obtenir des performances maximales de 200 Go, vous devez attribuer une adresse IP unique pour les ports physiques et virtuels de sorte que l'hôte puisse établir des connexions à chacun. Si vous n'attribuez pas d'adresse IP au port virtuel, la HIC fonctionne à environ la moitié de sa vitesse.



== Pourquoi y a-t-il deux ensembles de paramètres pour un port physique ?

La baie de stockage EF600 peut inclure deux HIC, un externe et un interne.

Dans cette configuration, la HIC externe est connectée à une HIC interne auxiliaire. Chaque port physique auquel vous pouvez accéder à partir de la HIC externe possède un port virtuel associé à partir de la HIC interne.

Pour obtenir des performances maximales de 200 Go, vous devez attribuer des paramètres aux ports physiques et virtuels de sorte que l'hôte puisse établir des connexions à chacun d'entre eux. Si vous n'attribuez pas de paramètres au port virtuel, la HIC fonctionne à environ la moitié de sa vitesse.
