---
permalink: sm-settings/obtain-a-feature-key-file.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, obtain, feature, key, file, 
summary: 'Pour activer une fonction premium ou un pack de fonctionnalités sur votre matrice de stockage, vous devez d"abord obtenir un fichier de clé de fonction. Une clé n"est associée qu"à une seule baie de stockage.' 
---
= Obtenir un fichier de clé de fonction
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour activer une fonction premium ou un pack de fonctionnalités sur votre matrice de stockage, vous devez d'abord obtenir un fichier de clé de fonction. Une clé n'est associée qu'à une seule baie de stockage.

.Description de la tâche
Dans cette tâche, vous apprendrez à rassembler les informations requises pour la fonction, puis à envoyer une demande pour un fichier de clé de fonction. Informations requises :

* Numéro de série du châssis
* Identifiant d'activation de fonctionnalité
* Code d'activation de la fonction


.Étapes
. Dans System Manager, recherchez et enregistrez le numéro de série du châssis. Vous pouvez afficher ce numéro de série en plaçant votre souris sur la mosaïque du Centre de support.
. Dans System Manager, localisez l'identifiant d'activation de la fonction. Accédez au menu:Paramètres[système], puis faites défiler jusqu'à *Compléments*. Recherchez l'identifiant *Feature Enable identifier*. Notez le numéro de l'identifiant d'activation de la fonction.
. Localiser et enregistrer le code d'activation de la fonction. Pour les packs de fonctionnalités, ce code est fourni dans les instructions appropriées pour effectuer la conversion.
+
Pour les fonctionnalités Premium, vous pouvez accéder au code d'activation à partir du site de support, comme suit :

+
.. Connectez-vous à https://mysupport.netapp.com/site/global/dashboard["Support NetApp"^].
.. Accédez à *licences logicielles* pour votre produit.
.. Entrez le numéro de série du châssis de la matrice de stockage, puis cliquez sur *Go*.
.. Recherchez les codes d'activation de la fonction dans la colonne *clé de licence*.
.. Enregistrez le code d'activation de la fonction souhaitée.


. Demandez un fichier de clé de fonction en envoyant un e-mail ou un document texte à votre fournisseur de stockage avec les informations suivantes : le numéro de série du châssis, l'identifiant d'activation et le code d'activation de la fonction.
+
Vous pouvez également accéder à http://partnerspfk.netapp.com["Activation de licence NetApp : activation de la fonctionnalité Storage Array Premium"^] saisissez les informations requises pour obtenir le pack de fonctions ou de fonctionnalités. (Les instructions de ce site concernent les fonctionnalités premium et non les packs de fonctionnalités.)



.Une fois que vous avez terminé
Lorsque vous disposez d'un fichier de clé de fonction, vous pouvez activer la fonction premium ou le pack de fonctions.
