---
permalink: sm-settings/reset-management-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reset, management, certificates, 
summary: 'Vous pouvez rétablir les certificats sur les contrôleurs de l"utilisation de certificats signés par l"autorité de certification aux certificats configurés en usine et auto-signés.' 
---
= Réinitialisez les certificats de gestion
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rétablir les certificats sur les contrôleurs de l'utilisation de certificats signés par l'autorité de certification aux certificats configurés en usine et auto-signés.

.Avant de commencer
* Vous devez être connecté avec un profil utilisateur qui inclut les autorisations d'administrateur de sécurité. Sinon, les fonctions de certificat n'apparaissent pas.
* Les certificats signés CA doivent être importés au préalable.


.Description de la tâche
La fonction Réinitialiser supprime les fichiers de certificat actuellement signés par l'autorité de certification de chaque contrôleur. Les contrôleurs retournent à l'utilisation de certificats auto-signés.

.Étapes
. Sélectionnez menu:Paramètres[certificats].
. Dans l'onglet gestion des baies, sélectionnez *Réinitialiser*.
+
La boîte de dialogue confirmer la réinitialisation des certificats de gestion s'ouvre.

. Type `reset` Dans le champ, puis cliquez sur *Réinitialiser*.
+
Une fois que votre navigateur a été actualisé, le navigateur risque de bloquer l'accès au site de destination et de signaler que le site utilise HTTP strict transport Security. Cette condition survient lorsque vous revenez à des certificats auto-signés. Pour effacer la condition qui bloque l'accès à la destination, vous devez effacer les données de navigation du navigateur.



.Résultats
Les contrôleurs retournent à l'utilisation de certificats auto-signés. Par conséquent, le système invite les utilisateurs à accepter manuellement le certificat auto-signé pour leurs sessions.
