---
permalink: sm-settings/switch-from-external-to-internal-key-management.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, switch, external, internal, key, management, 
summary: 'Vous pouvez changer la méthode de gestion de la sécurité des lecteurs d"un serveur de clés externe à la méthode interne utilisée par la matrice de stockage. La clé de sécurité précédemment définie pour la gestion externe des clés est ensuite utilisée pour la gestion interne des clés.' 
---
= Passez de la gestion externe des clés à la gestion interne des clés
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez changer la méthode de gestion de la sécurité des lecteurs d'un serveur de clés externe à la méthode interne utilisée par la matrice de stockage. La clé de sécurité précédemment définie pour la gestion externe des clés est ensuite utilisée pour la gestion interne des clés.

.Description de la tâche
Dans cette tâche, vous désactivez la gestion externe des clés et téléchargez une nouvelle copie de sauvegarde sur votre hôte local. La clé existante est toujours utilisée pour la sécurité des disques, mais elle sera gérée en interne dans la baie de stockage.

.Étapes
. Sélectionnez menu:Paramètres[système].
. Sous *gestion des clés de sécurité*, sélectionnez *Désactiver la gestion externe des clés*.
+
La boîte de dialogue Désactiver la gestion des clés externes s'ouvre.

. Dans *définissez une phrase de passe/saisissez à nouveau la phrase de passe*, entrez et confirmez une phrase de passe pour la sauvegarde de la clé. La valeur peut comporter entre 8 et 32 caractères et doit comprendre chacun des éléments suivants :
+
** Une lettre majuscule (une ou plusieurs). Gardez à l'esprit que la phrase de passe est sensible à la casse.
** Un nombre (un ou plusieurs).
** Caractère non alphanumérique, tel que !, *, @ (un ou plusieurs).


+
[CAUTION]
====
_Assurez-vous d'enregistrer vos entrées pour une utilisation ultérieure_. Si vous devez déplacer un lecteur sécurisé de la matrice de stockage, vous devez connaître l'identifiant et la phrase de passe pour déverrouiller les données du lecteur.

====
. Cliquez sur *Désactiver*.
+
La clé de sauvegarde est téléchargée sur votre hôte local.

. Enregistrez votre identifiant de clé, votre phrase de passe et l'emplacement du fichier de clé téléchargé, puis cliquez sur *Fermer*.


.Résultats
La sécurité des disques est désormais gérée en interne via la baie de stockage.

.Une fois que vous avez terminé
Vous devez valider la clé de sécurité pour vous assurer que le fichier clé n'est pas corrompu.
