---
permalink: sm-support/activate-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, activate, controller, software, firmware 
summary: 'Vous pouvez choisir d"activer les fichiers de mise à niveau immédiatement ou d"attendre jusqu"à ce que le moment soit plus opportun.' 
---
= Activer le logiciel et le micrologiciel du contrôleur
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez choisir d'activer les fichiers de mise à niveau immédiatement ou d'attendre jusqu'à ce que le moment soit plus opportun.

.Description de la tâche
Vous pouvez télécharger et transférer les fichiers sans les activer. Vous pouvez choisir de l'activer ultérieurement pour les raisons suivantes :

* *Temps de jour* -- l'activation du logiciel et du micrologiciel peut prendre un certain temps, vous pouvez donc attendre que les charges d'E/S soient plus légères. Les contrôleurs basculent pendant l'activation, pour que les performances soient inférieures à la normale jusqu'à la fin de la mise à niveau.
* *Type de paquet* -- vous pouvez tester le nouveau logiciel et le nouveau micrologiciel sur une matrice de stockage avant de mettre à niveau les fichiers sur d'autres matrices de stockage.


Lorsque le logiciel ou le micrologiciel a été transféré mais n'est pas activé, une notification s'affiche dans la zone Notifications de la page d'accueil de System Manager, ainsi que sur la page Centre de mise à niveau.

[CAUTION]
====
Vous ne pouvez pas arrêter le processus d'activation après son démarrage.

====
.Étapes
. Sélectionnez menu:support [Upgrade Center].
. Dans la zone mise à niveau du logiciel du contrôleur SANtricity OS, cliquez sur *Activer* et confirmez que vous souhaitez effectuer l'opération.
+
Vous pouvez annuler l'opération pendant le contrôle d'état de pré-mise à niveau, mais pas pendant l'activation.

+
La vérification préalable à la mise à niveau commence. Si le contrôle d'intégrité de pré-mise à niveau réussit, le processus de mise à niveau procède à l'activation des fichiers. Si la vérification préalable à la mise à niveau de l'état du système échoue, utilisez le gourou de la restauration ou contactez le support technique afin de résoudre le problème. Pour certains types de conditions, le support technique peut vous conseiller de continuer la mise à niveau malgré les erreurs en cochant la case *Autoriser la mise à niveau*.

+
Une fois la vérification préalable à la mise à niveau terminée, l'activation a lieu. Le temps nécessaire à l'activation dépend de la configuration de la matrice de stockage et des composants que vous activez.

. *Facultatif:* pour afficher la liste des mises à niveau, cliquez sur *Enregistrer le journal*.
+
Le fichier est enregistré dans le dossier Téléchargements de votre navigateur portant le nom `drive_upgrade_log-timestamp.txt`.



.Une fois que vous avez terminé
* Vérifiez que tous les composants apparaissent sur la page matériel.
* Vérifiez les nouvelles versions du logiciel et du micrologiciel en cochant la boîte de dialogue Inventaire du logiciel et du micrologiciel (allez au menu:support[Upgrade Center], puis cliquez sur le lien *Software and Firmware Inventory*).
* Si vous avez mis à niveau la NVSRAM du contrôleur, tous les paramètres personnalisés que vous avez appliqués à la NVSRAM existante sont perdus pendant le processus d'activation. Vous devez à nouveau appliquer les paramètres personnalisés à la NVSRAM une fois le processus d'activation terminé.

