---
permalink: sm-support/clear-recovery-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, clear, recovery, mode 
summary: 'Après avoir restauré une configuration de matrice de stockage, utilisez l"opération Clear Recovery mode (mode de restauration) pour reprendre les E/S sur la matrice de stockage et la rétablir dans des conditions normales d"utilisation.' 
---
= Désactivez le mode de récupération
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir restauré une configuration de matrice de stockage, utilisez l'opération Clear Recovery mode (mode de restauration) pour reprendre les E/S sur la matrice de stockage et la rétablir dans des conditions normales d'utilisation.

.Avant de commencer
* Si vous souhaitez restaurer la matrice de stockage dans une configuration précédente, vous devez restaurer la configuration à partir de la sauvegarde avant de désactiver le mode de récupération.
* Vous devez effectuer des vérifications de validation ou vérifier avec le support technique pour vous assurer que la restauration a réussi. Après avoir déterminé que la restauration a réussi, le mode de récupération peut être effacé.


.Description de la tâche
La matrice de stockage contient une base de données de configuration qui inclut un enregistrement de sa configuration logique (pools, groupes de volumes, volumes, etc.). Si vous effacez intentionnellement la configuration de la matrice de stockage ou si la base de données de configuration est corrompue, la matrice de stockage passe en mode de restauration. Le mode de récupération arrête les E/S et bloque la base de données de configuration, ce qui vous donne le temps d'effectuer l'une des opérations suivantes :

* Restaurez la configuration à partir de la sauvegarde automatique enregistrée dans les périphériques Flash du contrôleur. Pour ce faire, contactez le support technique.
* Restaurez la configuration à partir d'une opération de sauvegarde de la base de données de configuration précédente. Les opérations de sauvegarde de la base de données de configuration sont effectuées via l'interface de ligne de commande (CLI).
* Reconfigurez la matrice de stockage à partir de zéro.


Après avoir restauré ou redéfini la configuration de la matrice de stockage et avoir vérifié que tout est bien, vous devez désactiver manuellement le mode de récupération.

[NOTE]
====
Vous ne pouvez pas annuler l'opération Effacer le mode de récupération après son démarrage. L'effacement du mode de récupération peut prendre beaucoup de temps. Effectuez cette opération uniquement lorsque le support technique vous y invite.

====
.Étapes
. Sélectionnez l'onglet support[Centre de support > Diagnostics].
. Sélectionnez *Effacer le mode de récupération* et confirmez que vous souhaitez effectuer cette opération.
+
Cette option apparaît uniquement si la matrice de stockage est en mode de récupération.


