---
permalink: sm-support/how-do-i-configure-the-delivery-method-for-autosupport.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, delivery, method, autosupport, 
summary: La fonction AutoSupport prend en charge les protocoles HTTPS, HTTP et SMTP pour la distribution des interventions AutoSupport au support technique. 
---
= Comment configurer la méthode de livraison pour la fonctionnalité AutoSupport ?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La fonction AutoSupport prend en charge les protocoles HTTPS, HTTP et SMTP pour la distribution des interventions AutoSupport au support technique.

.Avant de commencer
* La fonctionnalité AutoSupport doit être activée. Vous pouvez vérifier si elle est activée ou non sur la page AutoSupport.
* Un serveur DNS doit être installé et configuré sur votre réseau. L'adresse du serveur DNS doit être configurée dans System Manager (cette tâche est disponible à partir de la page Hardware).


.Description de la tâche
Étudiez les différents protocoles :

* *HTTPS* -- vous permet de vous connecter directement au serveur d'assistance technique de destination via HTTPS. Si vous souhaitez activer AutoSupport OnDemand ou diagnostic à distance, la méthode de livraison AutoSupport doit être définie sur HTTPS.
* *HTTP* -- vous permet de vous connecter directement au serveur de support technique de destination via HTTP.
* *Email* -- vous permet d'utiliser un serveur de messagerie comme méthode de livraison pour envoyer des interventions AutoSupport.


[NOTE]
====
*Différences entre les méthodes HTTPS/HTTP et E-mail*. La méthode de distribution de l'e-mail, qui utilise SMTP, présente des différences importantes par rapport aux méthodes de distribution HTTPS et HTTP. Tout d'abord, la taille des interventions pour la méthode E-mail est limitée à 5 Mo, ce qui signifie que certaines collections de données ASUP ne seront pas envoyées. Deuxièmement, la fonctionnalité AutoSupport OnDemand est disponible uniquement sur les méthodes HTPP et HTTPS.

====
.Étapes
. Sélectionnez l'onglet [Centre de support > AutoSupport].
. Sélectionnez *configurer la méthode de livraison AutoSupport*.
+
Une boîte de dialogue s'affiche, qui répertorie les méthodes de livraison d'expédition.

. Sélectionnez la méthode de livraison souhaitée, puis sélectionnez les paramètres pour cette méthode de livraison. Effectuez l'une des opérations suivantes :
+
** Si vous avez sélectionné HTTPS ou HTTP, sélectionnez l'un des paramètres de distribution suivants :
+
*** *Directement* -- ce paramètre de distribution est la sélection par défaut. Cette option vous permet de vous connecter directement au système de support technique de destination à l'aide du protocole HTTPS ou HTTP.
*** *Via serveur proxy* -- la sélection de cette option vous permet de spécifier les détails du serveur proxy HTTP requis pour établir la connexion avec le système de support technique de destination. Vous devez spécifier l'adresse hôte et le numéro de port. Toutefois, vous devez uniquement saisir les détails d'authentification de l'hôte (nom d'utilisateur et mot de passe) si nécessaire.
*** *Via le script de configuration automatique du proxy (PAC)* -- spécifiez l'emplacement d'un fichier de script PAC (Proxy Auto-Configuration). Un fichier PAC permet au système de choisir automatiquement le serveur proxy approprié pour établir une connexion avec le système d'assistance technique de destination.


** Si vous avez sélectionné E-mail, saisissez les informations suivantes :
+
*** L'adresse du serveur de messagerie en tant que nom de domaine complet, adresse IPv4 ou adresse IPv6.
*** Adresse e-mail affichée dans le champ de du courrier électronique d'intervention AutoSupport.
*** *Facultatif; si vous voulez effectuer un test de configuration.* adresse e-mail où une confirmation est envoyée lorsque le système AutoSupport reçoit l'intervention de test.
*** Si vous souhaitez crypter les messages, sélectionnez *SMTPS* ou *STARTTLS* pour le type de cryptage, puis sélectionnez le numéro de port pour les messages cryptés. Sinon, sélectionnez *aucun*.
*** Si nécessaire, entrez un nom d'utilisateur et un mot de passe pour l'authentification avec l'expéditeur sortant et le serveur de messagerie.




. Cliquez sur *Tester la configuration* pour tester la connexion au serveur de support technique à l'aide des paramètres de livraison spécifiés. Si vous avez activé la fonctionnalité AutoSupport On-Demand, le système teste également la connexion pour la livraison de l'intervention AutoSupport OnDemand.
+
Si le test de configuration échoue, vérifiez vos paramètres de configuration et relancez le test. Si le test continue à échouer, contactez le support technique.

. Cliquez sur *Enregistrer*.

