---
permalink: sm-support/retrieve-trace-buffers.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, retrieve, trace, buffers 
summary: Vous pouvez récupérer les tampons de trace depuis les contrôleurs et envoyer le fichier au support technique pour analyse. 
---
= Récupérer les tampons de trace
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez récupérer les tampons de trace depuis les contrôleurs et envoyer le fichier au support technique pour analyse.

.Description de la tâche
Le micrologiciel utilise les tampons de trace pour enregistrer le traitement, en particulier les conditions d'exception, qui peuvent être utiles pour le débogage. Vous pouvez récupérer les tampons de trace sans interrompre le fonctionnement de la matrice de stockage et avec un impact minimal sur les performances.

[NOTE]
====
Effectuez cette opération uniquement lorsque le support technique vous y invite.

====
.Étapes
. Sélectionnez l'onglet support[Centre de support > Diagnostics].
. Sélectionnez *Retrieve Trace Buffers*.
. Cochez la case en regard de chaque contrôleur pour lequel vous souhaitez récupérer les tampons de trace.
+
Vous pouvez sélectionner un ou les deux contrôleurs. Si le message d'état du contrôleur à droite d'une case à cocher est en échec ou désactivé, la case est désactivée.

. Cliquez sur *Oui*.
+
Le fichier est enregistré dans le dossier Téléchargements de votre navigateur avec le nom de fichier `trace-buffers.7z`.

. Suivez les instructions fournies par le support technique pour leur envoyer le fichier.

