---
permalink: sm-support/upgrade-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, software, firmware 
summary: 'Vous pouvez mettre à niveau le logiciel de votre matrice de stockage et, éventuellement, le micrologiciel du module d"E/S et la mémoire NVSRAM (Nonvolatile Static Random Access Memory) pour vous assurer que vous disposez de toutes les dernières fonctionnalités et correctifs de bogues.' 
---
= Mise à niveau du logiciel et du micrologiciel du contrôleur
:allow-uri-read: 


[role="lead"]
Vous pouvez mettre à niveau le logiciel de votre matrice de stockage et, éventuellement, le micrologiciel du module d'E/S et la mémoire NVSRAM (Nonvolatile Static Random Access Memory) pour vous assurer que vous disposez de toutes les dernières fonctionnalités et correctifs de bogues.

.Avant de commencer
* Vous savez si vous souhaitez mettre à niveau le firmware du module d'E/S.
+
Normalement, vous devez mettre à niveau tous les composants en même temps. Toutefois, vous pouvez décider de ne pas mettre à niveau le firmware du module d'E/S si vous ne souhaitez pas le mettre à niveau dans le cadre de la mise à niveau du logiciel SANtricity OS ou si le support technique vous a demandé de rétrograder le micrologiciel de votre module d'E/S (vous ne pouvez que le mettre à niveau à l'aide de l'interface de ligne de commande).

* Vous savez si vous voulez mettre à niveau le fichier NVSRAM du contrôleur.
+
Normalement, vous devez mettre à niveau tous les composants en même temps. Toutefois, vous pouvez décider de ne pas mettre à niveau le fichier NVSRAM du contrôleur si votre fichier a été corrigé ou est une version personnalisée et que vous ne souhaitez pas le remplacer.

* Vous savez si vous souhaitez activer votre mise à niveau de système d'exploitation dès maintenant ou ultérieurement.
+
Voici quelques raisons d'activer ultérieurement :

+
** *Temps de jour* -- l'activation du logiciel et du micrologiciel peut prendre un certain temps, vous pouvez donc attendre que les charges d'E/S soient plus légères. Les contrôleurs basculent pendant l'activation, pour que les performances soient inférieures à la normale jusqu'à la fin de la mise à niveau.
** *Type de paquet* -- vous pouvez tester le nouveau logiciel et le nouveau micrologiciel sur une matrice de stockage avant de mettre à niveau les fichiers sur d'autres matrices de stockage.


* Vous savez si vous voulez passer de disques non sécurisés ou de disques sécurisés internes pour utiliser un serveur de gestion des clés externe (KMS) pour la sécurité des disques.
* Vous savez si vous souhaitez utiliser le contrôle d'accès basé sur des rôles dans votre baie de stockage.


.Description de la tâche
Vous pouvez choisir de mettre à niveau uniquement le fichier du logiciel OS ou uniquement le fichier NVSRAM du contrôleur ou de mettre à niveau les deux fichiers.

Effectuez cette opération uniquement lorsque le support technique vous y invite.

[CAUTION]
====
*Risque de perte de données ou de détérioration de la baie de stockage* -- ne modifiez pas la matrice de stockage pendant la mise à niveau. Maintenez l'alimentation de la baie de stockage.

====
.Étapes
. Si votre matrice de stockage ne contient qu'un seul contrôleur ou si aucun pilote multivoie n'est installé, arrêtez l'activité d'E/S vers la matrice de stockage pour éviter les erreurs d'application. Si votre baie de stockage est équipée de deux contrôleurs et qu'un pilote multivoie est installé, il n'est pas nécessaire d'arrêter l'activité d'E/S.
. Sélectionnez menu:support [Upgrade Center].
. Téléchargez le nouveau fichier depuis le site de support vers votre client de gestion.
+
.. Cliquez sur *NetApp support* pour lancer le site Web de support.
.. Sur le site Web de support, cliquez sur l'onglet *Téléchargements*, puis sélectionnez *Téléchargements*.
.. Sélectionnez *logiciel de contrôleur de système d'exploitation SANtricity E-Series*.
.. Suivez les instructions restantes.


+
[NOTE]
====
Un firmware avec signature numérique est requis dans la version 8.42 et supérieure. Si vous tentez de télécharger un firmware non signé, une erreur s'affiche et le téléchargement est interrompu.

====
. Si vous NE souhaitez PAS mettre à niveau le micrologiciel du module d'E/S à ce stade, cliquez sur *suspendre la synchronisation automatique du module d'E/S.
+
Si vous possédez une baie de stockage avec un seul contrôleur, le firmware du module d'E/S n'est pas mis à niveau.

. Sous mise à niveau du logiciel SANtricity OS, cliquez sur *commencer la mise à niveau*.
+
La boîte de dialogue mise à niveau du logiciel SANtricity OS s'affiche.

. Sélectionnez un ou plusieurs fichiers pour lancer le processus de mise à niveau :
+
.. Sélectionnez le fichier du logiciel SANtricity OS en cliquant sur *Parcourir* et accédez au fichier du logiciel OS que vous avez téléchargé à partir du site Web de support.
.. Sélectionnez le fichier NVSRAM du contrôleur en cliquant sur *Parcourir* et accédez au fichier NVSRAM que vous avez téléchargé à partir du site de support. Les fichiers NVSRAM du contrôleur ont un nom de fichier similaire à `N2800-830000-000.dlp`.


+
Ces actions se produisent :

+
** Par défaut, seuls les fichiers compatibles avec la configuration actuelle de la matrice de stockage apparaissent.
** Lorsque vous sélectionnez un fichier à mettre à niveau, le nom et la taille du fichier s'affichent.


. *Facultatif:* si vous avez sélectionné un fichier logiciel SANtricity OS à mettre à niveau, vous pouvez transférer les fichiers vers le contrôleur sans les activer en cochant la case *transférer les fichiers maintenant, mais ne pas mettre à niveau (Activer la mise à niveau plus tard)*.
. Cliquez sur *Démarrer* et confirmez que vous souhaitez effectuer l'opération.
+
Vous pouvez annuler l'opération pendant le contrôle d'intégrité de pré-mise à niveau, mais pas pendant le transfert ou l'activation.

. *Facultatif:* pour afficher la liste des mises à niveau, cliquez sur *Enregistrer le journal*.
+
Le fichier est enregistré dans le dossier Téléchargements de votre navigateur portant le nom `drive_upgrade_log-timestamp.txt`.



.Une fois que vous avez terminé
* Vérifiez que tous les composants apparaissent sur la page matériel.
* Vérifiez les nouvelles versions du logiciel et du micrologiciel en cochant la boîte de dialogue Inventaire du logiciel et du micrologiciel (allez au menu:support[Upgrade Center], puis cliquez sur le lien *Software and Firmware Inventory*).
* Si vous avez mis à niveau la NVSRAM du contrôleur, tous les paramètres personnalisés que vous avez appliqués à la NVSRAM existante sont perdus pendant le processus d'activation. Vous devez à nouveau appliquer les paramètres personnalisés à la NVSRAM une fois le processus d'activation terminé.

