---
permalink: sm-support/upgrade-drive-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, drive, firmware 
summary: Vous pouvez mettre à niveau le micrologiciel de vos lecteurs pour vous assurer que vous disposez de toutes les dernières fonctionnalités et correctifs de bogues. 
---
= Mettre à niveau le micrologiciel du lecteur
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau le micrologiciel de vos lecteurs pour vous assurer que vous disposez de toutes les dernières fonctionnalités et correctifs.

.Avant de commencer
* Vous avez sauvegardé vos données à l'aide de la sauvegarde disque à disque, de la copie de volume (sur un groupe de volumes non concerné par la mise à niveau du micrologiciel planifiée) ou d'un miroir distant.
* La matrice de stockage présente un état optimal.
* Tous les disques ont un état optimal.
* Aucune modification de configuration n'est en cours sur la matrice de stockage.
* Si les lecteurs ne peuvent effectuer qu'une mise à niveau hors ligne, l'activité d'E/S de tous les volumes associés aux lecteurs est interrompue.


.Étapes
. Sélectionnez menu:support [Upgrade Center].
. Téléchargez les nouveaux fichiers du site de support sur votre client de gestion.
+
.. Sous mise à niveau du micrologiciel des disques, cliquez sur *NetApp support*.
.. Sur le site Web de support NetApp, cliquez sur l'onglet *Downloads*.
.. Sélectionnez *Disk Drive & Firmware Matrix*.
.. Suivez les instructions restantes.


. Sous mise à niveau du micrologiciel du lecteur, cliquez sur *commencer la mise à niveau*.
+
Une boîte de dialogue s'affiche, qui répertorie les fichiers du micrologiciel du lecteur actuellement utilisés.

. Extrayez (décompresser) les fichiers téléchargés depuis le site de support.
. Cliquez sur *Parcourir*, puis sélectionnez les nouveaux fichiers de micrologiciel de lecteur que vous avez téléchargés à partir du site de support.
+
Les fichiers du micrologiciel du lecteur ont un nom de fichier similaire à `D_HUC101212CSS600_30602291_MS01_2800_0002` avec l'extension de `.dlp`.

+
Vous pouvez sélectionner jusqu'à quatre fichiers de micrologiciel de lecteur, un par un. Si plusieurs fichiers de micrologiciel de lecteur sont compatibles avec le même lecteur, vous obtenez une erreur de conflit de fichier. Choisissez le fichier de micrologiciel de lecteur que vous souhaitez utiliser pour la mise à niveau et supprimez l'autre.

. Cliquez sur *Suivant*.
+
La boîte de dialogue *Sélectionner les lecteurs* apparaît, qui répertorie les lecteurs que vous pouvez mettre à niveau avec les fichiers sélectionnés.

+
Seuls les lecteurs compatibles apparaissent.

+
Le micrologiciel sélectionné pour le lecteur s'affiche dans la zone d'informations du micrologiciel proposé. Si vous devez modifier le micrologiciel, cliquez sur *Retour* pour revenir à la boîte de dialogue précédente.

. Sélectionnez le type de mise à niveau que vous souhaitez effectuer :
+
** *Online (par défaut)* -- affiche les lecteurs qui peuvent prendre en charge un téléchargement de micrologiciel _pendant que la matrice de stockage traite I/O_. Il n'est pas nécessaire d'arrêter les E/S vers les volumes associés à l'aide de ces lecteurs lorsque vous sélectionnez cette méthode de mise à niveau. Ces disques sont mis à niveau un par un, alors que la baie de stockage traite des E/S vers ces disques.
** *Hors ligne (parallèle)* -- affiche les lecteurs qui peuvent prendre en charge un téléchargement de micrologiciel _uniquement pendant que toutes les activités d'E/S sont arrêtées_ sur tous les volumes qui utilisent les lecteurs. Vous devez arrêter toutes les activités d'E/S sur les volumes qui utilisent les lecteurs que vous mettez à niveau lorsque vous sélectionnez cette méthode de mise à niveau. Les lecteurs qui ne sont pas redondants doivent être traités comme une opération hors ligne. Cette configuration inclut tous les disques associés à un cache SSD, un groupe de volumes RAID 0 ou tout pool ou groupe de volumes dégradé. La mise à niveau hors ligne (parallèle) est généralement plus rapide que la méthode en ligne (par défaut).


. Dans la première colonne du tableau, sélectionnez le ou les lecteurs que vous souhaitez mettre à niveau.
. Cliquez sur *Démarrer* et confirmez que vous souhaitez effectuer l'opération.
+
Si vous devez arrêter la mise à niveau, cliquez sur *Stop*. Tous les téléchargements de micrologiciel en cours sont terminés. Tous les téléchargements de micrologiciel qui n'ont pas démarré sont annulés.

+
[CAUTION]
====
L'arrêt de la mise à niveau du micrologiciel du lecteur peut entraîner une perte de données ou l'indisponibilité des disques.

====
. *Facultatif:* pour afficher la liste des mises à niveau, cliquez sur *Enregistrer le journal*.
+
Le fichier est enregistré dans le dossier Téléchargements de votre navigateur portant le nom `drive_upgrade_log-timestamp.txt`.

. Si l'une des erreurs suivantes se produit pendant la procédure de mise à niveau, effectuez l'action recommandée appropriée.


.Erreurs et actions recommandées
[%collapsible]
====
[cols="40h,~"]
|===
| Si vous rencontrez cette erreur de téléchargement du micrologiciel... | Puis procédez comme suit... 


 a| 
Disques affectés en panne
 a| 
L'une des raisons de la défaillance est que le lecteur ne possède pas la signature appropriée. Assurez-vous que le disque concerné est un disque autorisé. Contactez le support technique pour plus d'informations.

Lorsque vous remplacez un lecteur, assurez-vous que sa capacité est supérieure ou égale à celle du lecteur défectueux que vous remplacez.

Vous pouvez remplacer le disque défectueux alors que la matrice de stockage reçoit des E/S.



 a| 
Vérifier la matrice de stockage
 a| 
* Assurez-vous qu'une adresse IP a été attribuée à chaque contrôleur.
* Assurez-vous que tous les câbles connectés au contrôleur ne sont pas endommagés.
* Assurez-vous que tous les câbles sont bien connectés.




 a| 
Disques de secours intégrés
 a| 
Ce problème d'erreur doit être corrigé avant de pouvoir mettre à niveau le micrologiciel. Lancez System Manager et utilisez le gourou de la restauration pour résoudre le problème.



 a| 
Groupes de volumes incomplets
 a| 
Si un ou plusieurs groupes de volumes ou pools de disques sont incomplets, vous devez corriger cette condition d'erreur avant de pouvoir mettre à niveau le micrologiciel. Lancez System Manager et utilisez le gourou de la restauration pour résoudre le problème.



 a| 
Opérations exclusives \(autres que l'analyse de parité/support en arrière-plan\) actuellement en cours d'exécution sur n'importe quel groupe de volumes
 a| 
Si une ou plusieurs opérations exclusives sont en cours, les opérations doivent être effectuées avant la mise à niveau du micrologiciel. Utilisez System Manager pour surveiller la progression des opérations.



 a| 
Volumes manquants
 a| 
Vous devez corriger la condition de volume manquant avant de pouvoir mettre à niveau le micrologiciel. Lancez System Manager et utilisez le gourou de la restauration pour résoudre le problème.



 a| 
L'un ou l'autre des contrôleurs est dans un état autre que optimal
 a| 
L'un des contrôleurs de la baie de stockage doit faire attention. Ce problème doit être résolu avant la mise à niveau du firmware. Lancez System Manager et utilisez le gourou de la restauration pour résoudre le problème.



 a| 
Incohérence des informations de partition de stockage entre les graphiques d'objet du contrôleur
 a| 
Une erreur s'est produite lors de la validation des données sur les contrôleurs. Contactez le support technique pour résoudre ce problème.



 a| 
Échec de la vérification du contrôleur de base de données SPM Verify Database Controller
 a| 
Une erreur de mappage de la base de données de mappage des partitions de stockage s'est produite sur un contrôleur. Contactez le support technique pour résoudre ce problème.



 a| 
Validation de la base de données de configuration \(si prise en charge par la version du contrôleur de la matrice de stockage\)
 a| 
Une erreur de base de données de configuration s'est produite sur un contrôleur. Contactez le support technique pour résoudre ce problème.



 a| 
Vérifications liées À MEL
 a| 
Contactez le support technique pour résoudre ce problème.



 a| 
Plus de 10 événements MEL informationnels ou critiques de DDE ont été rapportés au cours des 7 derniers jours
 a| 
Contactez le support technique pour résoudre ce problème.



 a| 
Plus de 2 pages 2C des événements MEL critiques ont été rapportés au cours des 7 derniers jours
 a| 
Contactez le support technique pour résoudre ce problème.



 a| 
Plus de 2 événements MEL critiques de disque dur ont été signalés au cours des 7 derniers jours
 a| 
Contactez le support technique pour résoudre ce problème.



 a| 
Plus de 4 entrées MEL critiques au cours des 7 derniers jours
 a| 
Contactez le support technique pour résoudre ce problème.

|===
====
.Une fois que vous avez terminé
La mise à niveau du micrologiciel de votre lecteur est terminée. Vous pouvez reprendre les opérations normales.
