---
permalink: sm-support/view-software-and-firmware-inventory.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, software, firmware, inventory 
summary: 'L"inventaire des logiciels et des micrologiciels répertorie les versions de micrologiciel de chaque composant de la matrice de stockage.' 
---
= Afficher l'inventaire des logiciels et des firmwares
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'inventaire des logiciels et des micrologiciels répertorie les versions de micrologiciel de chaque composant de la matrice de stockage.

.Description de la tâche
Une matrice de stockage est composée de nombreux composants, dont des contrôleurs, des disques, des tiroirs et des modules d'entrée/sortie (IOM). Chacun de ces composants contient du firmware. Certaines versions du micrologiciel dépendent d'autres versions du micrologiciel. Pour capturer des informations sur toutes les versions de micrologiciel de votre matrice de stockage, consultez l'inventaire des logiciels et micrologiciels. Le support technique peut analyser l'inventaire des logiciels et des micrologiciels afin de détecter les incohérences de micrologiciel.

.Étapes
. Sélectionnez l'onglet support[Centre de support > Ressources de support].
. Faites défiler vers le bas jusqu'à *lancer les informations détaillées de la matrice de stockage*, puis sélectionnez *Inventaire des logiciels et micrologiciels*.
+
Le rapport d'inventaire des logiciels et micrologiciels s'affiche à l'écran.

. Pour enregistrer l'inventaire du logiciel et du micrologiciel, cliquez sur *Enregistrer*.
+
Le fichier est enregistré dans le dossier Téléchargements de votre navigateur avec le nom de fichier `firmware-inventory.txt`.

. Suivez les instructions fournies par le support technique pour leur envoyer le fichier.

