---
permalink: sm-support/what-type-of-data-is-collected-through-autosupport.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, data, collected, autosupport, ASUP 
summary: 'La fonction AutoSupport contient trois types d"intervention standard : l"envoi d"événements, les interventions planifiées et les interventions de diagnostic à la demande et à distance.' 
---
= Quel type de données est collecté grâce à la fonctionnalité AutoSupport ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La fonction AutoSupport contient trois types d'intervention standard : l'envoi d'événements, les interventions planifiées et les interventions de diagnostic à la demande et à distance.

Les données AutoSupport ne contiennent aucune donnée utilisateur.

* *Interventions d'événements*
+
Lorsque des événements se produisent sur le système qui garantit une notification proactive au support technique, la fonctionnalité AutoSupport envoie automatiquement une intervention déclenchée par un événement.

+
** Envoyé lorsqu'un événement de support sur la baie de stockage gérée se produit.
** Comprend un aperçu complet de ce qui se passait avec la baie de stockage au moment de l'événement.


* *Interventions programmées*
+
La fonction AutoSupport envoie automatiquement plusieurs interventions selon un calendrier régulier.

+
** *Interventions quotidiennes* -- envoyées une fois par jour pendant un intervalle de temps configurable par l'utilisateur. Inclut les journaux d'événements du système et les données de performances.
** *Interventions hebdomadaires* -- envoyées une fois par semaine pendant un intervalle de temps et un jour configurables par l'utilisateur. Inclut des informations sur la configuration et l'état du système.


* *Interventions de diagnostic à distance et AutoSupport OnDemand*
+
** *AutoSupport OnDemand* -- permet au support technique de demander la retransmission d'une intervention AutoSupport précédente si nécessaire pour le dépannage d'un problème. Toutes les transmissions sont lancées à partir de la baie de stockage, et non à partir du serveur AutoSupport. La baie de stockage vérifie régulièrement avec le serveur AutoSupport pour déterminer s'il existe des demandes de retransmission en attente et répond en conséquence.
** *Diagnostics à distance* -- permet au support technique de demander une nouvelle intervention AutoSupport à jour si nécessaire pour le dépannage d'un problème. Toutes les transmissions sont lancées à partir de la baie de stockage, et non à partir du serveur AutoSupport. La baie de stockage s'effectue régulièrement avec le serveur AutoSupport afin de déterminer s'il existe de nouvelles demandes en attente et répond en conséquence.



