---
permalink: san-getstarted/supported-browsers-os.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: 'Vous pouvez accéder à SANtricity à partir de différents types de navigateurs et de systèmes d"exploitation.' 
---
= Prise en charge du navigateur logiciel et du système d'exploitation SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le logiciel SANtricity prend en charge plusieurs types de navigateurs et de systèmes d'exploitation.



== Navigateurs

Les navigateurs et versions suivants sont pris en charge.

[cols="1a,1a"]
|===
| Navigateur | Version minimale 


 a| 
Google Chrome
 a| 
89



 a| 
Mozilla Firefox
 a| 
80



 a| 
Safari
 a| 
14



 a| 
Microsoft Edge
 a| 
90

|===
[NOTE]
====
Pour Unified Manager, le proxy de services Web doit être installé et accessible au navigateur. Pour plus d'informations, voir https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html["Présentation du proxy de services Web SANtricity"^]

====


== Systèmes d'exploitation

Les systèmes d'exploitation et versions suivants sont pris en charge.

[cols="1a,1a"]
|===
| Système d'exploitation | Version/architecture minimale 


 a| 
Red Hat Enterprise Linux (RHEL)
 a| 
8.x (SP8), 9.x (SP2) / 64-bit



 a| 
SUSE Linux Enterprise Server (SLES)
 a| 
12.x (SP4, SP5), 15.x (SP4, SP5) / 64-bit



 a| 
Oracle Linux (OL)
 a| 
8.x (U8), 9.x (U2) / 64-bit



 a| 
Serveur Windows
 a| 
2019, 2022, 2025 / 64-bit



 a| 
Ubuntu
 a| 
20.04, 22.04 / 64-bit

|===