---
permalink: um-certificates/change-passwords-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, passwords 
summary: Vous pouvez modifier les mots de passe utilisateur de chaque utilisateur dans Access Management. 
---
= Modifiez les mots de passe des profils utilisateur locaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les mots de passe utilisateur de chaque utilisateur dans Access Management.

.Avant de commencer
* Vous devez être connecté en tant qu'administrateur local, qui inclut les autorisations d'administrateur racine.
* Vous devez connaître le mot de passe administrateur local.


.Description de la tâche
Suivez les consignes suivantes lorsque vous choisissez un mot de passe :

* Tout nouveau mot de passe utilisateur local doit respecter ou dépasser le paramètre actuel pour un mot de passe minimum (dans Afficher/Modifier les paramètres).
* Les mots de passe sont sensibles à la casse.
* Les espaces en fin de page ne sont pas supprimés des mots de passe lorsqu'ils sont définis. Veillez à inclure des espaces s'ils étaient inclus dans le mot de passe.
* Pour renforcer la sécurité, utilisez au moins 15 caractères alphanumériques et modifiez fréquemment le mot de passe.


.Étapes
. Sélectionnez *Access Management*.
. Sélectionnez l'onglet *rôles d'utilisateur local*.
. Sélectionnez un utilisateur dans le tableau.
+
Le bouton Modifier le mot de passe devient disponible.

. Sélectionnez *Modifier le mot de passe*.
+
La boîte de dialogue modification du mot de passe s'ouvre.

. Si aucun mot de passe minimum n'est défini pour les mots de passe d'utilisateur local, vous pouvez cocher la case pour demander à l'utilisateur d'entrer un mot de passe pour accéder au système.
. Saisissez le nouveau mot de passe pour l'utilisateur sélectionné dans les deux champs.
. Entrez votre mot de passe administrateur local pour confirmer cette opération, puis cliquez sur *Modifier*.


.Résultats
Si l'utilisateur est actuellement connecté, le changement de mot de passe entraîne la fin de la session active de l'utilisateur.
