---
permalink: um-certificates/view-certificates-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, view certificates 
summary: 'Vous pouvez afficher les informations récapitulatives d"un certificat, y compris l"organisation utilisant le certificat, l"autorité qui a émis le certificat, la période de validité et les empreintes digitales (identifiants uniques).' 
---
= Afficher les certificats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les informations récapitulatives d'un certificat, y compris l'organisation utilisant le certificat, l'autorité qui a émis le certificat, la période de validité et les empreintes digitales (identifiants uniques).

.Avant de commencer
Vous devez être connecté avec un profil utilisateur qui inclut les autorisations d'administrateur de sécurité. Sinon, les fonctions de certificat n'apparaissent pas.

.Étapes
. Sélectionnez *gestion des certificats*.
. Sélectionnez l'un des onglets suivants :
+
** *Management* -- affiche le certificat pour le système hébergeant le proxy de services Web. Un certificat de gestion peut être auto-signé ou approuvé par une autorité de certification (AC). Cette fonctionnalité permet un accès sécurisé à Unified Manager.
** *Trusted* -- affiche les certificats auxquels Unified Manager peut accéder pour les matrices de stockage et les autres serveurs distants, tels qu'un serveur LDAP. Les certificats peuvent être émis par une autorité de certification (CA) ou être auto-signés.


. Pour plus d'informations sur un certificat, sélectionnez sa ligne, les points de suspension à la fin de la ligne, puis cliquez sur *View* ou *Export*.

