---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: 'Vous devez configurer SANtricity Unified Manager avec un mot de passe d"administrateur pour le protéger contre tout accès non autorisé.' 
---
= Définissez la protection par mot de passe de l'administrateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer SANtricity Unified Manager avec un mot de passe d'administrateur pour le protéger contre tout accès non autorisé.



== Mot de passe administrateur et profils utilisateur

Lorsque vous démarrez Unified Manager pour la première fois, vous êtes invité à définir un mot de passe administrateur. Tout utilisateur disposant du mot de passe administrateur peut modifier la configuration des matrices de stockage.

En plus du mot de passe administrateur, l'interface Unified Manager inclut des profils utilisateur préconfigurés avec un ou plusieurs rôles qui leur sont mappés. Pour plus d'informations, voir link:../um-certificates/how-access-management-works-unified.html["Fonctionnement de Access Management"].

Les utilisateurs et les mappages ne peuvent pas être modifiés. Seuls les mots de passe peuvent être modifiés. Pour modifier les mots de passe, voir :

* link:change-admin-password-unified.html["Modifiez le mot de passe d'administration"]
* link:../um-certificates/change-passwords-unified.html["Modifiez les mots de passe des profils utilisateur locaux"]




== Délais de connexion

Le logiciel vous demande le mot de passe une seule fois lors d'une seule session de gestion. Une session est expirée au bout de 30 minutes d'inactivité par défaut. Vous devez alors saisir à nouveau le mot de passe. Si un autre utilisateur accède au logiciel à partir d'un autre client de gestion et modifie le mot de passe pendant que votre session est en cours, vous êtes invité à saisir un mot de passe lors de la prochaine tentative d'opération de configuration ou d'affichage.

Pour des raisons de sécurité, vous ne pouvez tenter de saisir un mot de passe que cinq fois avant que le logiciel n'entre dans un état de « verrouillage ». Dans cet état, le logiciel rejette les tentatives de mot de passe suivantes. Vous devez attendre 10 minutes pour revenir à l'état « normal » avant d'essayer de saisir à nouveau un mot de passe.

Vous pouvez régler les délais de session ou désactiver complètement les délais de session. Pour plus d'informations, voir link:manage-session-timeouts-unified.html["Gérer les délais d'expiration des sessions"].
