---
permalink: um-admin/change-storage-array-passwords.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, storage, array, passwords 
summary: Vous pouvez mettre à jour les mots de passe utilisés pour afficher et accéder aux baies de stockage dans SANtricity Unified Manager. 
---
= Changer les mots de passe des matrices de stockage
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à jour les mots de passe utilisés pour afficher et accéder aux matrices de stockage dans Unified Manager.

.Avant de commencer
* Vous devez être connecté avec un profil utilisateur qui inclut les autorisations d'administrateur de stockage.
* Vous devez connaître le mot de passe actuel de la baie de stockage, qui est défini dans System Manager.


.Description de la tâche
Dans cette tâche, vous entrez le mot de passe actuel d'une matrice de stockage afin de pouvoir y accéder dans Unified Manager. Cela peut être nécessaire si le mot de passe de la baie a été modifié dans System Manager et qu'il doit maintenant être également modifié dans Unified Manager.

.Étapes
. Dans la page gérer, sélectionnez une ou plusieurs matrices de stockage.
. Menu sélection:tâches rares[fournir des mots de passe de matrice de stockage].
. Entrez le mot de passe ou les mots de passe pour chaque matrice de stockage, puis cliquez sur *Enregistrer*.

