---
permalink: um-admin/change-admin-password-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, admin, password 
summary: 'Vous pouvez modifier le mot de passe d"administration utilisé pour accéder à SANtricity Unified Manager.' 
---
= Modifiez le mot de passe d'administration
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le mot de passe d'administration utilisé pour accéder à Unified Manager.

.Avant de commencer
* Vous devez être connecté en tant qu'administrateur local, qui inclut les autorisations d'administrateur racine.
* Vous devez connaître le mot de passe d'administration actuel.


.Description de la tâche
Suivez les consignes suivantes lorsque vous choisissez un mot de passe :

* Les mots de passe sont sensibles à la casse.
* Les espaces en fin de page ne sont pas supprimés des mots de passe lorsqu'ils sont définis. Veillez à inclure des espaces s'ils étaient inclus dans le mot de passe.
* Pour renforcer la sécurité, utilisez au moins 15 caractères alphanumériques et modifiez fréquemment le mot de passe.


.Étapes
. Sélectionnez menu:Paramètres[gestion des accès].
. Sélectionnez l'onglet *rôles d'utilisateur local*.
. Sélectionnez l'utilisateur *admin* dans la table.
+
Le bouton Modifier le mot de passe devient disponible.

. Sélectionnez *Modifier le mot de passe*.
+
La boîte de dialogue modification du mot de passe s'ouvre.

. Si aucun mot de passe minimum n'est défini pour les mots de passe d'utilisateur local, cochez la case pour demander à l'utilisateur d'entrer un mot de passe pour accéder au système.
. Saisissez le nouveau mot de passe dans les deux champs.
. Entrez votre mot de passe administrateur local pour confirmer cette opération, puis cliquez sur *Modifier*.

